// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
// ignore_for_file: prefer_relative_imports
import 'package:terradart_core/terradart_core.dart';

/// Sensitive field paths for `google_bigquery_table`.
const Set<String> _googleBigqueryTableSensitive = <String>{};

/// Factory wrapper for `google_bigquery_table`.
///
/// Read-only data source on the apply-excluded leftover path
/// (synth + `terraform validate` only). Do not apply.
final class DataGoogleBigqueryTable extends Data {
  static const String tfType = 'google_bigquery_table';

  DataGoogleBigqueryTable({
    required super.localName,
    required TfArg<String> datasetId,
    TfArg<String>? project,
    required TfArg<String> tableId,
  }) : super(
         terraformType: tfType,
         argMap: {
           'dataset_id': datasetId,
           if (project != null) 'project': project,
           'table_id': tableId,
         },
       );

  @override
  Set<String> get sensitiveFields => _googleBigqueryTableSensitive;

  /// Reference to `id` attribute.
  TfRef<String> get id => TfRef.attribute<String>(this, 'id');

  /// Reference to `biglake_configuration` attribute.
  TfRef<List<Map<String, Object?>>> get biglakeConfiguration =>
      TfRef.attribute<List<Map<String, Object?>>>(
        this,
        'biglake_configuration',
      );

  /// Reference to `clustering` attribute.
  TfRef<List<String>> get clustering =>
      TfRef.attribute<List<String>>(this, 'clustering');

  /// Reference to `creation_time` attribute.
  TfRef<num> get creationTime => TfRef.attribute<num>(this, 'creation_time');

  /// Reference to `deletion_policy` attribute.
  TfRef<String> get deletionPolicy =>
      TfRef.attribute<String>(this, 'deletion_policy');

  /// Reference to `deletion_protection` attribute.
  TfRef<bool> get deletionProtection =>
      TfRef.attribute<bool>(this, 'deletion_protection');

  /// Reference to `description` attribute.
  TfRef<String> get description => TfRef.attribute<String>(this, 'description');

  /// Reference to `effective_labels` attribute.
  TfRef<Map<String, String>> get effectiveLabels =>
      TfRef.attribute<Map<String, String>>(this, 'effective_labels');

  /// Reference to `encryption_configuration` attribute.
  TfRef<List<Map<String, Object?>>> get encryptionConfiguration =>
      TfRef.attribute<List<Map<String, Object?>>>(
        this,
        'encryption_configuration',
      );

  /// Reference to `etag` attribute.
  TfRef<String> get etag => TfRef.attribute<String>(this, 'etag');

  /// Reference to `expiration_time` attribute.
  TfRef<num> get expirationTime =>
      TfRef.attribute<num>(this, 'expiration_time');

  /// Reference to `external_catalog_table_options` attribute.
  TfRef<List<Map<String, Object?>>> get externalCatalogTableOptions =>
      TfRef.attribute<List<Map<String, Object?>>>(
        this,
        'external_catalog_table_options',
      );

  /// Reference to `external_data_configuration` attribute.
  TfRef<List<Map<String, Object?>>> get externalDataConfiguration =>
      TfRef.attribute<List<Map<String, Object?>>>(
        this,
        'external_data_configuration',
      );

  /// Reference to `friendly_name` attribute.
  TfRef<String> get friendlyName =>
      TfRef.attribute<String>(this, 'friendly_name');

  /// Reference to `generated_schema_columns` attribute.
  TfRef<String> get generatedSchemaColumns =>
      TfRef.attribute<String>(this, 'generated_schema_columns');

  /// Reference to `ignore_auto_generated_schema` attribute.
  TfRef<bool> get ignoreAutoGeneratedSchema =>
      TfRef.attribute<bool>(this, 'ignore_auto_generated_schema');

  /// Reference to `ignore_schema_changes` attribute.
  TfRef<List<String>> get ignoreSchemaChanges =>
      TfRef.attribute<List<String>>(this, 'ignore_schema_changes');

  /// Reference to `labels` attribute.
  TfRef<Map<String, String>> get labels =>
      TfRef.attribute<Map<String, String>>(this, 'labels');

  /// Reference to `last_modified_time` attribute.
  TfRef<num> get lastModifiedTime =>
      TfRef.attribute<num>(this, 'last_modified_time');

  /// Reference to `location` attribute.
  TfRef<String> get location => TfRef.attribute<String>(this, 'location');

  /// Reference to `materialized_view` attribute.
  TfRef<List<Map<String, Object?>>> get materializedView =>
      TfRef.attribute<List<Map<String, Object?>>>(this, 'materialized_view');

  /// Reference to `max_staleness` attribute.
  TfRef<String> get maxStaleness =>
      TfRef.attribute<String>(this, 'max_staleness');

  /// Reference to `num_bytes` attribute.
  TfRef<num> get numBytes => TfRef.attribute<num>(this, 'num_bytes');

  /// Reference to `num_long_term_bytes` attribute.
  TfRef<num> get numLongTermBytes =>
      TfRef.attribute<num>(this, 'num_long_term_bytes');

  /// Reference to `num_rows` attribute.
  TfRef<num> get numRows => TfRef.attribute<num>(this, 'num_rows');

  /// Reference to `range_partitioning` attribute.
  TfRef<List<Map<String, Object?>>> get rangePartitioning =>
      TfRef.attribute<List<Map<String, Object?>>>(this, 'range_partitioning');

  /// Reference to `require_partition_filter` attribute.
  TfRef<bool> get requirePartitionFilter =>
      TfRef.attribute<bool>(this, 'require_partition_filter');

  /// Reference to `resource_tags` attribute.
  TfRef<Map<String, String>> get resourceTags =>
      TfRef.attribute<Map<String, String>>(this, 'resource_tags');

  /// Reference to `schema` attribute.
  TfRef<String> get schema => TfRef.attribute<String>(this, 'schema');

  /// Reference to `schema_foreign_type_info` attribute.
  TfRef<List<Map<String, Object?>>> get schemaForeignTypeInfo =>
      TfRef.attribute<List<Map<String, Object?>>>(
        this,
        'schema_foreign_type_info',
      );

  /// Reference to `self_link` attribute.
  TfRef<String> get selfLink => TfRef.attribute<String>(this, 'self_link');

  /// Reference to `table_constraints` attribute.
  TfRef<List<Map<String, Object?>>> get tableConstraints =>
      TfRef.attribute<List<Map<String, Object?>>>(this, 'table_constraints');

  /// Reference to `table_metadata_view` attribute.
  TfRef<String> get tableMetadataView =>
      TfRef.attribute<String>(this, 'table_metadata_view');

  /// Reference to `table_replication_info` attribute.
  TfRef<List<Map<String, Object?>>> get tableReplicationInfo =>
      TfRef.attribute<List<Map<String, Object?>>>(
        this,
        'table_replication_info',
      );

  /// Reference to `terraform_labels` attribute.
  TfRef<Map<String, String>> get terraformLabels =>
      TfRef.attribute<Map<String, String>>(this, 'terraform_labels');

  /// Reference to `time_partitioning` attribute.
  TfRef<List<Map<String, Object?>>> get timePartitioning =>
      TfRef.attribute<List<Map<String, Object?>>>(this, 'time_partitioning');

  /// Reference to `type` attribute.
  TfRef<String> get type => TfRef.attribute<String>(this, 'type');

  /// Reference to `view` attribute.
  TfRef<List<Map<String, Object?>>> get view =>
      TfRef.attribute<List<Map<String, Object?>>>(this, 'view');
}
