// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
// ignore_for_file: prefer_relative_imports
import 'package:terradart_core/terradart_core.dart';

// `data.google_project` is intentionally NOT regenerated by
// `tool/regen_curated.dart` — data sources don't have a schema-generation
// requirement in v0.0.x (the regen pipeline targets resource bodies). To
// preserve the v0.0.x surface of `GoogleProject`, we inline both the
// `$GoogleProject` schemantic-style abstract and the sensitive set here.
//
// When future adds data-source codegen support, this file will swap to
// importing from `lib/src/generated/data_google_project.schema.dart` and
// the inline stubs below will be deleted — same migration pattern as the
// curated resource factories now follow.

/// Sensitive field paths for `google_project`.
const Set<String> _googleProjectSensitive = <String>{};

/// Data source for `data.google_project`.
///
/// Use to look up the active project's `number`, `name`, etc., for
/// downstream references (e.g. CMEK service-account email composition).
///
/// ```dart
/// final current = stack.addData(GoogleProject(localName: 'current'));
/// final cmekBinding = GooglePubsubTopicIamMember(
///   localName: 'pubsub_cmek',
///   topic: TfArg.ref(topic.nameRef),
///   role: TfArg.literal('roles/cloudkms.cryptoKeyEncrypterDecrypter'),
///   member: TfArg.literal(
///     'serviceAccount:service-${current.number.interpolation}@gcp-sa-pubsub.iam.gserviceaccount.com',
///   ),
/// );
/// ```
///
/// Composition: extends `Data<$GoogleProject>` (the `Data<S>` base in
/// `terradart`). Synth emits this under `data.google_project.<localName>`
/// (vs `resource.…` for `Resource<S>`).
final class GoogleProject extends Data {
  // ignore: constant_identifier_names
  static const String $tfType = 'google_project';

  GoogleProject({required super.localName, TfArg<String>? projectId})
    : super(
        terraformType: $tfType,
        argMap: {if (projectId != null) 'project_id': projectId},
      );

  @override
  // ignore: non_constant_identifier_names
  Set<String> get $sensitiveFields => _googleProjectSensitive;

  TfRef<String> get number => TfRef.attribute<String>(this, 'number');
  TfRef<String> get name => TfRef.attribute<String>(this, 'name');
  TfRef<String> get projectIdRef => TfRef.attribute<String>(this, 'project_id');
  TfRef<String> get id => TfRef.attribute<String>(this, 'id');
}
