name: terradart_example_network_security_dns_threat_quickstart
description: Network Security DNS threat detector (DNS Armor) end-to-end example.
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  terradart_core: ^0.25.0
  terradart_google: ^0.25.0

dev_dependencies:
  lints: ^6.0.0
