/// Static catalog of all curated terradart_google factories.
///
/// Consumed by terradart_agent (the terradart-mcp server). The
/// [terradartCatalog] list is generated by `terradart wrap`.
library;

export 'src/catalog_entry.dart';
export 'src/_catalog.g.dart' show terradartCatalog;
