/// Static catalog of all curated terradart_google factories.
///
/// Consumed by terradart_migrate (sensitive arguments) and the coverage page
/// generator (`tool/render_coverage_page.dart`). The [terradartCatalog] list is
/// generated by `terradart wrap`.
library;

export 'src/catalog_entry.dart';
export 'src/_catalog.g.dart' show terradartCatalog;
