// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
/// Sensitive Data Protection (DLP) — inspect / de-identify templates,
/// stored info types, and job triggers.
library;

export 'src/dlp/google_data_loss_prevention_deidentify_template.dart'
    show GoogleDataLossPreventionDeidentifyTemplate;
export 'src/dlp/google_data_loss_prevention_discovery_config.dart'
    show
        DataLossPreventionDiscoveryConfigActions,
        DataLossPreventionDiscoveryConfigActionsExportData,
        DataLossPreventionDiscoveryConfigActionsExportDataProfileTable,
        DataLossPreventionDiscoveryConfigActionsExportDataSampleFindingsTable,
        DataLossPreventionDiscoveryConfigActionsPubSubNotification,
        DataLossPreventionDiscoveryConfigActionsPubSubNotificationDetailOfMessage,
        DataLossPreventionDiscoveryConfigActionsPubSubNotificationEvent,
        DataLossPreventionDiscoveryConfigActionsPubSubNotificationPubsubCondition,
        DataLossPreventionDiscoveryConfigActionsPubSubNotificationPubsubConditionExpressions,
        DataLossPreventionDiscoveryConfigActionsPubSubNotificationPubsubConditionExpressionsConditions,
        DataLossPreventionDiscoveryConfigActionsPubSubNotificationPubsubConditionExpressionsConditionsMinimumRiskScore,
        DataLossPreventionDiscoveryConfigActionsPubSubNotificationPubsubConditionExpressionsConditionsMinimumSensitivityScore,
        DataLossPreventionDiscoveryConfigActionsPubSubNotificationPubsubConditionExpressionsLogicalOperator,
        DataLossPreventionDiscoveryConfigActionsPublishToChronicle,
        DataLossPreventionDiscoveryConfigActionsPublishToDataplexCatalog,
        DataLossPreventionDiscoveryConfigActionsPublishToScc,
        DataLossPreventionDiscoveryConfigActionsTagResources,
        DataLossPreventionDiscoveryConfigActionsTagResourcesProfileGenerationsToTag,
        DataLossPreventionDiscoveryConfigActionsTagResourcesTagConditions,
        DataLossPreventionDiscoveryConfigActionsTagResourcesTagConditionsSensitivityScore,
        DataLossPreventionDiscoveryConfigActionsTagResourcesTagConditionsSensitivityScoreScore,
        DataLossPreventionDiscoveryConfigActionsTagResourcesTagConditionsTag,
        DataLossPreventionDiscoveryConfigOrgConfig,
        DataLossPreventionDiscoveryConfigOrgConfigLocation,
        DataLossPreventionDiscoveryConfigOtherCloudStartingLocation,
        DataLossPreventionDiscoveryConfigOtherCloudStartingLocationAwsLocation,
        DataLossPreventionDiscoveryConfigStatus,
        DataLossPreventionDiscoveryConfigTargets,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTarget,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetCadence,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetCadenceInspectTemplateModifiedCadence,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetCadenceInspectTemplateModifiedCadenceFrequency,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetCadenceSchemaModifiedCadence,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetCadenceSchemaModifiedCadenceFrequency,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetCadenceSchemaModifiedCadenceTypes,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetCadenceTableModifiedCadence,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetCadenceTableModifiedCadenceFrequency,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetConditions,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetConditionsOrConditions,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetConditionsTypeCollection,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetConditionsTypes,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetConditionsTypesTypes,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetDisabled,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetFilter,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetFilterOtherTables,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetFilterTableReference,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetFilterTables,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetFilterTablesIncludeRegexes,
        DataLossPreventionDiscoveryConfigTargetsBigQueryTargetFilterTablesIncludeRegexesPatterns,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTarget,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetConditions,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetConditionsDatabaseEngines,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetConditionsTypes,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetDisabled,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetFilter,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetFilterCollection,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetFilterCollectionIncludeRegexes,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetFilterCollectionIncludeRegexesPatterns,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetFilterDatabaseResourceReference,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetFilterOthers,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetGenerationCadence,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetGenerationCadenceInspectTemplateModifiedCadence,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetGenerationCadenceInspectTemplateModifiedCadenceFrequency,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetGenerationCadenceRefreshFrequency,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetGenerationCadenceSchemaModifiedCadence,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetGenerationCadenceSchemaModifiedCadenceFrequency,
        DataLossPreventionDiscoveryConfigTargetsCloudSqlTargetGenerationCadenceSchemaModifiedCadenceTypes,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTarget,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetConditions,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetConditionsCloudStorageConditions,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetConditionsCloudStorageConditionsIncludedBucketAttributes,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetConditionsCloudStorageConditionsIncludedObjectAttributes,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetDisabled,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetFilter,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetFilterCloudStorageResourceReference,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetFilterCollection,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetFilterCollectionIncludeRegexes,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetFilterCollectionIncludeRegexesPatterns,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetFilterCollectionIncludeRegexesPatternsCloudStorageRegex,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetFilterCollectionIncludeTags,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetFilterCollectionIncludeTagsTagFilters,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetFilterOthers,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetGenerationCadence,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetGenerationCadenceInspectTemplateModifiedCadence,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetGenerationCadenceInspectTemplateModifiedCadenceFrequency,
        DataLossPreventionDiscoveryConfigTargetsCloudStorageTargetGenerationCadenceRefreshFrequency,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTarget,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetConditions,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetConditionsAmazonS3BucketConditions,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetConditionsAmazonS3BucketConditionsBucketTypes,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetConditionsAmazonS3BucketConditionsObjectStorageClasses,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetDataSourceType,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetDisabled,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetFilter,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetFilterCollection,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetFilterCollectionIncludeRegexes,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetFilterCollectionIncludeRegexesPatterns,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetFilterCollectionIncludeRegexesPatternsAmazonS3BucketRegex,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetFilterCollectionIncludeRegexesPatternsAmazonS3BucketRegexAwsAccountRegex,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetFilterOthers,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetFilterSingleResource,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetFilterSingleResourceAmazonS3Bucket,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetFilterSingleResourceAmazonS3BucketAwsAccount,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetGenerationCadence,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetGenerationCadenceInspectTemplateModifiedCadence,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetGenerationCadenceInspectTemplateModifiedCadenceFrequency,
        DataLossPreventionDiscoveryConfigTargetsOtherCloudTargetGenerationCadenceRefreshFrequency,
        DataLossPreventionDiscoveryConfigTargetsSecretsTarget,
        GoogleDataLossPreventionDiscoveryConfig;
export 'src/dlp/google_data_loss_prevention_inspect_template.dart'
    show GoogleDataLossPreventionInspectTemplate;
export 'src/dlp/google_data_loss_prevention_job_trigger.dart'
    show DataLossPreventionJobTriggerStatus, GoogleDataLossPreventionJobTrigger;
export 'src/dlp/google_data_loss_prevention_stored_info_type.dart'
    show
        DataLossPreventionStoredInfoTypeDefinition,
        DataLossPreventionStoredInfoTypeDictionary,
        DataLossPreventionStoredInfoTypeLargeCustomDictionary,
        DataLossPreventionStoredInfoTypeRegex,
        GoogleDataLossPreventionStoredInfoType;
