// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
/// Transcoder API — reusable job templates (JobConfig metadata). Creating
/// a template does not transcode media; jobs that run a template bill
/// output-minute SKUs and are not curated here.
library;

export 'src/transcoder/google_transcoder_job.dart'
    show
        GoogleTranscoderJob,
        TranscoderJobConfig,
        TranscoderJobConfigAdBreaks,
        TranscoderJobConfigEditList,
        TranscoderJobConfigElementaryStreams,
        TranscoderJobConfigElementaryStreamsAudioStream,
        TranscoderJobConfigElementaryStreamsVideoStream,
        TranscoderJobConfigElementaryStreamsVideoStreamH264,
        TranscoderJobConfigElementaryStreamsVideoStreamH264Hlg,
        TranscoderJobConfigElementaryStreamsVideoStreamH264Sdr,
        TranscoderJobConfigEncryptions,
        TranscoderJobConfigEncryptionsAes128,
        TranscoderJobConfigEncryptionsDrmSystems,
        TranscoderJobConfigEncryptionsDrmSystemsClearkey,
        TranscoderJobConfigEncryptionsDrmSystemsFairplay,
        TranscoderJobConfigEncryptionsDrmSystemsPlayready,
        TranscoderJobConfigEncryptionsDrmSystemsWidevine,
        TranscoderJobConfigEncryptionsMpegCenc,
        TranscoderJobConfigEncryptionsSampleAes,
        TranscoderJobConfigEncryptionsSecretManagerKeySource,
        TranscoderJobConfigInputs,
        TranscoderJobConfigManifests,
        TranscoderJobConfigManifestsType,
        TranscoderJobConfigMuxStreams,
        TranscoderJobConfigMuxStreamsSegmentSettings,
        TranscoderJobConfigOutput,
        TranscoderJobConfigOverlays,
        TranscoderJobConfigOverlaysAnimations,
        TranscoderJobConfigOverlaysAnimationsAnimationFade,
        TranscoderJobConfigOverlaysAnimationsAnimationFadeFadeType,
        TranscoderJobConfigOverlaysAnimationsAnimationFadeXy,
        TranscoderJobConfigOverlaysImage,
        TranscoderJobConfigPubsubDestination;
export 'src/transcoder/google_transcoder_job_template.dart'
    show
        GoogleTranscoderJobTemplate,
        TranscoderJobTemplateConfig,
        TranscoderJobTemplateConfigAdBreaks,
        TranscoderJobTemplateConfigEditList,
        TranscoderJobTemplateConfigElementaryStreams,
        TranscoderJobTemplateConfigElementaryStreamsAudioStream,
        TranscoderJobTemplateConfigElementaryStreamsVideoStream,
        TranscoderJobTemplateConfigElementaryStreamsVideoStreamH264,
        TranscoderJobTemplateConfigElementaryStreamsVideoStreamH264Hlg,
        TranscoderJobTemplateConfigElementaryStreamsVideoStreamH264Sdr,
        TranscoderJobTemplateConfigEncryptions,
        TranscoderJobTemplateConfigEncryptionsAes128,
        TranscoderJobTemplateConfigEncryptionsDrmSystems,
        TranscoderJobTemplateConfigEncryptionsDrmSystemsClearkey,
        TranscoderJobTemplateConfigEncryptionsDrmSystemsFairplay,
        TranscoderJobTemplateConfigEncryptionsDrmSystemsPlayready,
        TranscoderJobTemplateConfigEncryptionsDrmSystemsWidevine,
        TranscoderJobTemplateConfigEncryptionsMpegCenc,
        TranscoderJobTemplateConfigEncryptionsSampleAes,
        TranscoderJobTemplateConfigEncryptionsSecretManagerKeySource,
        TranscoderJobTemplateConfigInputs,
        TranscoderJobTemplateConfigManifests,
        TranscoderJobTemplateConfigManifestsType,
        TranscoderJobTemplateConfigMuxStreams,
        TranscoderJobTemplateConfigMuxStreamsSegmentSettings,
        TranscoderJobTemplateConfigOutput,
        TranscoderJobTemplateConfigOverlays,
        TranscoderJobTemplateConfigOverlaysAnimations,
        TranscoderJobTemplateConfigOverlaysAnimationsAnimationFade,
        TranscoderJobTemplateConfigOverlaysAnimationsAnimationFadeFadeType,
        TranscoderJobTemplateConfigOverlaysAnimationsAnimationFadeXy,
        TranscoderJobTemplateConfigOverlaysImage,
        TranscoderJobTemplateConfigPubsubDestination;
