name: terradart_example_artifact_registry_quickstart
description: Artifact Registry project config + Docker repo + download rule + location tag binding.
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  terradart_core: ^0.25.1
  terradart_google: ^0.25.1

dev_dependencies:
  lints: ^6.0.0
