name: terradart_example_dialogflow_quickstart
description: terradart example — Dialogflow CX SIP trunk.
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  terradart_core: ^0.25.2
  terradart_google: ^0.25.2

dev_dependencies:
  lints: ^6.0.0
