/// Static catalog of all curated terradart_cloudflare factories.
///
/// Consumed by terradart_coverage (and any tool that matches Terraform types
/// against the curated set). The [terradartCatalog] list is generated by
/// `terradart wrap`; [CatalogEntry] and [CatalogKind] are hand-written.
library;

export 'src/catalog_entry.dart';
export 'src/_catalog.g.dart' show terradartCatalog;
