/// Migration-manifest runtime types for terradart_cloudflare.
///
/// Consumed by `terradart migrate` (the HCL → Dart migrator, #80). The
/// [MigrateManifest] value itself — `terradartMigrateManifest` in
/// `src/_migrate_manifest.g.dart` — is generated by
/// `terradart wrap --migrate-manifest` and exported from here once the
/// package commits it (#658).
library;

export 'src/migrate_manifest_entry.dart';
