// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
import 'catalog_entry.dart';

const List<CatalogEntry> terradartCatalog = <CatalogEntry>[
  CatalogEntry(
    tfType: 'aws_caller_identity',
    className: 'DataAwsCallerIdentity',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `aws_caller_identity`.',
    constructorParams: <String>['localName'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `aws_caller_identity`.\n\nThe AWS account, user ID and ARN the provider authenticated as. Read\n[accountId] instead of hard-coding the account number in ARNs.',
  ),
  CatalogEntry(
    tfType: 'aws_cloudwatch_log_group',
    className: 'AwsCloudwatchLogGroup',
    barrel: 'cloudwatch',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `aws_cloudwatch_log_group`.',
    constructorParams: <String>[
      'localName',
      'deletionProtectionEnabled',
      'kmsKeyId',
      'logGroupClass',
      'name',
      'namePrefix',
      'region',
      'retentionInDays',
      'skipDestroy',
      'tags',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `aws_cloudwatch_log_group`.\n\nAWS **CloudWatch Logs log group**. Declare a Lambda function\'s group\n(`/aws/lambda/<function name>`) yourself to control\n`retentionInDays`; otherwise Lambda creates it on first invocation\nwith no expiry, outside Terraform.',
  ),
  CatalogEntry(
    tfType: 'aws_iam_policy_document',
    className: 'DataAwsIamPolicyDocument',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `aws_iam_policy_document`.',
    constructorParams: <String>[
      'localName',
      'overrideJson',
      'overridePolicyDocuments',
      'policyId',
      'sourceJson',
      'sourcePolicyDocuments',
      'version',
      'statement',
    ],
    nestedTypes: <String>[
      'DataIamPolicyDocumentStatement',
      'DataIamPolicyDocumentStatementCondition',
      'DataIamPolicyDocumentStatementNotPrincipals',
      'DataIamPolicyDocumentStatementPrincipals',
    ],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `aws_iam_policy_document`.\n\nBuilds an IAM policy document from typed statements. Terraform\nrenders it to JSON; read that through [json] and pass it to a trust\npolicy (`AwsIamRole.assumeRolePolicy`) or an inline policy.\n\nEach [DataIamPolicyDocumentStatement] carries `actions`, `resources`,\n`effect`, and typed `principals` / `condition` blocks.',
  ),
  CatalogEntry(
    tfType: 'aws_iam_role',
    className: 'AwsIamRole',
    barrel: 'iam',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `aws_iam_role`.',
    constructorParams: <String>[
      'localName',
      'assumeRolePolicy',
      'description',
      'forceDetachPolicies',
      'managedPolicyArns',
      'maxSessionDuration',
      'name',
      'namePrefix',
      'path',
      'permissionsBoundary',
      'tags',
      'inlinePolicy',
    ],
    nestedTypes: <String>['IamRoleInlinePolicy'],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `aws_iam_role`.\n\nAWS **IAM role** — the identity a Lambda function, ECS task, or other\nAWS service assumes at runtime.\n\n`assumeRolePolicy` is the trust policy JSON. Build it with a\n[DataAwsIamPolicyDocument] and pass `TfArg.ref(doc.json)`, so the\nstatements are typed Dart rather than a hand-written JSON string.\nAttach managed policies with [AwsIamRolePolicyAttachment].',
  ),
  CatalogEntry(
    tfType: 'aws_iam_role_policy_attachment',
    className: 'AwsIamRolePolicyAttachment',
    barrel: 'iam',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `aws_iam_role_policy_attachment`.',
    constructorParams: <String>['localName', 'policyArn', 'role'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `aws_iam_role_policy_attachment`.\n\nAttaches one managed IAM policy to an [AwsIamRole]. Additive: other\nattachments on the role are left alone.\n\n`role` takes the role **name** (`TfArg.ref(role.nameRef)`), not its ARN.\nAWS-managed policies use ARNs such as\n`arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole`.',
  ),
  CatalogEntry(
    tfType: 'aws_lambda_function',
    className: 'AwsLambdaFunction',
    barrel: 'lambda',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `aws_lambda_function`.',
    constructorParams: <String>[
      'localName',
      'architectures',
      'codeSha256',
      'codeSigningConfigArn',
      'description',
      'filename',
      'functionName',
      'handler',
      'imageUri',
      'kmsKeyArn',
      'layers',
      'memorySize',
      'packageType',
      'publish',
      'publishTo',
      'region',
      'replaceSecurityGroupsOnDestroy',
      'replacementSecurityGroupIds',
      'reservedConcurrentExecutions',
      'role',
      'runtime',
      's3Bucket',
      's3Key',
      's3ObjectVersion',
      'skipDestroy',
      'sourceCodeHash',
      'sourceKmsKeyArn',
      'tags',
      'timeout',
      'useResourceTimeoutForPropagation',
      'capacityProviderConfig',
      'deadLetterConfig',
      'durableConfig',
      'environment',
      'ephemeralStorage',
      'fileSystemConfig',
      'imageConfig',
      'loggingConfig',
      'snapStart',
      'tenancyConfig',
      'tracingConfig',
      'vpcConfig',
    ],
    nestedTypes: <String>[
      'LambdaFunctionCapacityProviderConfig',
      'LambdaFunctionCapacityProviderConfigLambdaManagedInstancesCapacityProviderConfig',
      'LambdaFunctionDeadLetterConfig',
      'LambdaFunctionDurableConfig',
      'LambdaFunctionEnvironment',
      'LambdaFunctionEphemeralStorage',
      'LambdaFunctionFileSystemConfig',
      'LambdaFunctionImageConfig',
      'LambdaFunctionLoggingConfig',
      'LambdaFunctionSnapStart',
      'LambdaFunctionTenancyConfig',
      'LambdaFunctionTracingConfig',
      'LambdaFunctionVpcConfig',
    ],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `aws_lambda_function`.\n\nAWS **Lambda function**. A Dart backend runs on the `provided.al2023`\ncustom runtime: compile it with `dart compile exe` to a binary named\n`bootstrap`, zip it, and pass the zip as `filename` with\n`handler: TfArg.literal(\'bootstrap\')`.\n\n`role` takes the execution role\'s ARN (`TfArg.ref(role.arn)`).\nSupply the code through exactly one of `filename`, `s3Bucket` +\n`s3Key`, or `imageUri`; the Dart API does not enforce that choice,\n`terraform validate` does. Pair `sourceCodeHash` with `filename` so a\nrebuilt zip redeploys.',
  ),
  CatalogEntry(
    tfType: 'aws_lambda_function_url',
    className: 'AwsLambdaFunctionUrl',
    barrel: 'lambda',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `aws_lambda_function_url`.',
    constructorParams: <String>[
      'localName',
      'authorizationType',
      'functionName',
      'invokeMode',
      'qualifier',
      'region',
      'cors',
    ],
    nestedTypes: <String>['LambdaFunctionUrlCors'],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `aws_lambda_function_url`.\n\nA dedicated HTTPS endpoint for an [AwsLambdaFunction], without API\nGateway in front.\n\n`authorizationType: TfArg.literal(\'NONE\')` makes the URL public;\n`AWS_IAM` requires SigV4-signed callers. Read the endpoint through\n[functionUrl].',
  ),
];
