// GENERATED FILE - DO NOT EDIT
// Regenerate with `terradart wrap --migrate-manifest <this file>` (lanes: tool/providers.yaml).
import '../migrate_manifest.dart';

const MigrateManifest awsMigrateManifest = MigrateManifest(
  package: 'terradart_aws',
  entries: <MigrateEntry>[
    MigrateEntry(
      tfType: 'aws_caller_identity',
      className: 'DataAwsCallerIdentity',
      barrel: 'data',
      kind: CatalogKind.dataSource,
      slots: <MigrateSlot>[],
      getters: <MigrateGetter>[
        MigrateGetter(tfName: 'id', dartName: 'id', dartType: 'String'),
        MigrateGetter(
          tfName: 'account_id',
          dartName: 'accountId',
          dartType: 'String',
        ),
        MigrateGetter(tfName: 'arn', dartName: 'arn', dartType: 'String'),
        MigrateGetter(
          tfName: 'user_id',
          dartName: 'userId',
          dartType: 'String',
        ),
      ],
    ),
    MigrateEntry(
      tfType: 'aws_cloudwatch_log_group',
      className: 'AwsCloudwatchLogGroup',
      barrel: 'cloudwatch',
      kind: CatalogKind.resource,
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'deletion_protection_enabled',
          dartName: 'deletionProtectionEnabled',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'bool',
        ),
        MigrateSlot(
          tfName: 'kms_key_id',
          dartName: 'kmsKeyId',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'log_group_class',
          dartName: 'logGroupClass',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'name',
          dartName: 'name',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'name_prefix',
          dartName: 'namePrefix',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'region',
          dartName: 'region',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'retention_in_days',
          dartName: 'retentionInDays',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'num',
        ),
        MigrateSlot(
          tfName: 'skip_destroy',
          dartName: 'skipDestroy',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'bool',
        ),
        MigrateSlot(
          tfName: 'tags',
          dartName: 'tags',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'Map<String, String>',
        ),
      ],
      getters: <MigrateGetter>[
        MigrateGetter(tfName: 'name', dartName: 'nameRef', dartType: 'String'),
        MigrateGetter(tfName: 'id', dartName: 'id', dartType: 'String'),
        MigrateGetter(tfName: 'arn', dartName: 'arn', dartType: 'String'),
      ],
    ),
    MigrateEntry(
      tfType: 'aws_iam_policy_document',
      className: 'DataAwsIamPolicyDocument',
      barrel: 'data',
      kind: CatalogKind.dataSource,
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'override_json',
          dartName: 'overrideJson',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'override_policy_documents',
          dartName: 'overridePolicyDocuments',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<String>',
        ),
        MigrateSlot(
          tfName: 'policy_id',
          dartName: 'policyId',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'source_json',
          dartName: 'sourceJson',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'source_policy_documents',
          dartName: 'sourcePolicyDocuments',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<String>',
        ),
        MigrateSlot(
          tfName: 'version',
          dartName: 'version',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'statement',
          dartName: 'statement',
          kind: MigrateSlotKind.helper,
          required: false,
          repeated: true,
          wrapped: false,
          helper: 'DataIamPolicyDocumentStatement',
        ),
      ],
      getters: <MigrateGetter>[
        MigrateGetter(tfName: 'id', dartName: 'id', dartType: 'String'),
        MigrateGetter(tfName: 'json', dartName: 'json', dartType: 'String'),
        MigrateGetter(
          tfName: 'minified_json',
          dartName: 'minifiedJson',
          dartType: 'String',
        ),
      ],
    ),
    MigrateEntry(
      tfType: 'aws_iam_role',
      className: 'AwsIamRole',
      barrel: 'iam',
      kind: CatalogKind.resource,
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'assume_role_policy',
          dartName: 'assumeRolePolicy',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'description',
          dartName: 'description',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'force_detach_policies',
          dartName: 'forceDetachPolicies',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'bool',
        ),
        MigrateSlot(
          tfName: 'managed_policy_arns',
          dartName: 'managedPolicyArns',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<String>',
        ),
        MigrateSlot(
          tfName: 'max_session_duration',
          dartName: 'maxSessionDuration',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'num',
        ),
        MigrateSlot(
          tfName: 'name',
          dartName: 'name',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'name_prefix',
          dartName: 'namePrefix',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'path',
          dartName: 'path',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'permissions_boundary',
          dartName: 'permissionsBoundary',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'tags',
          dartName: 'tags',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'Map<String, String>',
        ),
        MigrateSlot(
          tfName: 'inline_policy',
          dartName: 'inlinePolicy',
          kind: MigrateSlotKind.helper,
          required: false,
          repeated: true,
          wrapped: false,
          helper: 'IamRoleInlinePolicy',
        ),
      ],
      getters: <MigrateGetter>[
        MigrateGetter(tfName: 'name', dartName: 'nameRef', dartType: 'String'),
        MigrateGetter(tfName: 'id', dartName: 'id', dartType: 'String'),
        MigrateGetter(tfName: 'arn', dartName: 'arn', dartType: 'String'),
        MigrateGetter(
          tfName: 'create_date',
          dartName: 'createDate',
          dartType: 'String',
        ),
        MigrateGetter(
          tfName: 'unique_id',
          dartName: 'uniqueId',
          dartType: 'String',
        ),
      ],
    ),
    MigrateEntry(
      tfType: 'aws_iam_role_policy_attachment',
      className: 'AwsIamRolePolicyAttachment',
      barrel: 'iam',
      kind: CatalogKind.resource,
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'policy_arn',
          dartName: 'policyArn',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'role',
          dartName: 'role',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
      ],
      getters: <MigrateGetter>[
        MigrateGetter(tfName: 'id', dartName: 'id', dartType: 'String'),
      ],
    ),
    MigrateEntry(
      tfType: 'aws_lambda_function',
      className: 'AwsLambdaFunction',
      barrel: 'lambda',
      kind: CatalogKind.resource,
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'architectures',
          dartName: 'architectures',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<String>',
        ),
        MigrateSlot(
          tfName: 'code_sha256',
          dartName: 'codeSha256',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'code_signing_config_arn',
          dartName: 'codeSigningConfigArn',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'description',
          dartName: 'description',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'filename',
          dartName: 'filename',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'function_name',
          dartName: 'functionName',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'handler',
          dartName: 'handler',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'image_uri',
          dartName: 'imageUri',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'kms_key_arn',
          dartName: 'kmsKeyArn',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'layers',
          dartName: 'layers',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<String>',
        ),
        MigrateSlot(
          tfName: 'memory_size',
          dartName: 'memorySize',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'num',
        ),
        MigrateSlot(
          tfName: 'package_type',
          dartName: 'packageType',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'publish',
          dartName: 'publish',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'bool',
        ),
        MigrateSlot(
          tfName: 'publish_to',
          dartName: 'publishTo',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'region',
          dartName: 'region',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'replace_security_groups_on_destroy',
          dartName: 'replaceSecurityGroupsOnDestroy',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'bool',
        ),
        MigrateSlot(
          tfName: 'replacement_security_group_ids',
          dartName: 'replacementSecurityGroupIds',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<String>',
        ),
        MigrateSlot(
          tfName: 'reserved_concurrent_executions',
          dartName: 'reservedConcurrentExecutions',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'num',
        ),
        MigrateSlot(
          tfName: 'role',
          dartName: 'role',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'runtime',
          dartName: 'runtime',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 's3_bucket',
          dartName: 's3Bucket',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 's3_key',
          dartName: 's3Key',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 's3_object_version',
          dartName: 's3ObjectVersion',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'skip_destroy',
          dartName: 'skipDestroy',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'bool',
        ),
        MigrateSlot(
          tfName: 'source_code_hash',
          dartName: 'sourceCodeHash',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'source_kms_key_arn',
          dartName: 'sourceKmsKeyArn',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'tags',
          dartName: 'tags',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'Map<String, String>',
        ),
        MigrateSlot(
          tfName: 'timeout',
          dartName: 'timeout',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'num',
        ),
        MigrateSlot(
          tfName: 'use_resource_timeout_for_propagation',
          dartName: 'useResourceTimeoutForPropagation',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'bool',
        ),
        MigrateSlot(
          tfName: 'capacity_provider_config',
          dartName: 'capacityProviderConfig',
          kind: MigrateSlotKind.helper,
          required: false,
          wrapped: false,
          helper: 'LambdaFunctionCapacityProviderConfig',
        ),
        MigrateSlot(
          tfName: 'dead_letter_config',
          dartName: 'deadLetterConfig',
          kind: MigrateSlotKind.helper,
          required: false,
          wrapped: false,
          helper: 'LambdaFunctionDeadLetterConfig',
        ),
        MigrateSlot(
          tfName: 'durable_config',
          dartName: 'durableConfig',
          kind: MigrateSlotKind.helper,
          required: false,
          wrapped: false,
          helper: 'LambdaFunctionDurableConfig',
        ),
        MigrateSlot(
          tfName: 'environment',
          dartName: 'environment',
          kind: MigrateSlotKind.helper,
          required: false,
          wrapped: false,
          helper: 'LambdaFunctionEnvironment',
        ),
        MigrateSlot(
          tfName: 'ephemeral_storage',
          dartName: 'ephemeralStorage',
          kind: MigrateSlotKind.helper,
          required: false,
          wrapped: false,
          helper: 'LambdaFunctionEphemeralStorage',
        ),
        MigrateSlot(
          tfName: 'file_system_config',
          dartName: 'fileSystemConfig',
          kind: MigrateSlotKind.helper,
          required: false,
          wrapped: false,
          helper: 'LambdaFunctionFileSystemConfig',
        ),
        MigrateSlot(
          tfName: 'image_config',
          dartName: 'imageConfig',
          kind: MigrateSlotKind.helper,
          required: false,
          wrapped: false,
          helper: 'LambdaFunctionImageConfig',
        ),
        MigrateSlot(
          tfName: 'logging_config',
          dartName: 'loggingConfig',
          kind: MigrateSlotKind.helper,
          required: false,
          wrapped: false,
          helper: 'LambdaFunctionLoggingConfig',
        ),
        MigrateSlot(
          tfName: 'snap_start',
          dartName: 'snapStart',
          kind: MigrateSlotKind.helper,
          required: false,
          wrapped: false,
          helper: 'LambdaFunctionSnapStart',
        ),
        MigrateSlot(
          tfName: 'tenancy_config',
          dartName: 'tenancyConfig',
          kind: MigrateSlotKind.helper,
          required: false,
          wrapped: false,
          helper: 'LambdaFunctionTenancyConfig',
        ),
        MigrateSlot(
          tfName: 'tracing_config',
          dartName: 'tracingConfig',
          kind: MigrateSlotKind.helper,
          required: false,
          wrapped: false,
          helper: 'LambdaFunctionTracingConfig',
        ),
        MigrateSlot(
          tfName: 'vpc_config',
          dartName: 'vpcConfig',
          kind: MigrateSlotKind.helper,
          required: false,
          wrapped: false,
          helper: 'LambdaFunctionVpcConfig',
        ),
      ],
      getters: <MigrateGetter>[
        MigrateGetter(tfName: 'id', dartName: 'id', dartType: 'String'),
        MigrateGetter(tfName: 'arn', dartName: 'arn', dartType: 'String'),
        MigrateGetter(
          tfName: 'invoke_arn',
          dartName: 'invokeArn',
          dartType: 'String',
        ),
        MigrateGetter(
          tfName: 'last_modified',
          dartName: 'lastModified',
          dartType: 'String',
        ),
        MigrateGetter(
          tfName: 'qualified_arn',
          dartName: 'qualifiedArn',
          dartType: 'String',
        ),
        MigrateGetter(
          tfName: 'qualified_invoke_arn',
          dartName: 'qualifiedInvokeArn',
          dartType: 'String',
        ),
        MigrateGetter(
          tfName: 'response_streaming_invoke_arn',
          dartName: 'responseStreamingInvokeArn',
          dartType: 'String',
        ),
        MigrateGetter(
          tfName: 'signing_job_arn',
          dartName: 'signingJobArn',
          dartType: 'String',
        ),
        MigrateGetter(
          tfName: 'signing_profile_version_arn',
          dartName: 'signingProfileVersionArn',
          dartType: 'String',
        ),
        MigrateGetter(
          tfName: 'source_code_size',
          dartName: 'sourceCodeSize',
          dartType: 'num',
        ),
        MigrateGetter(
          tfName: 'version',
          dartName: 'version',
          dartType: 'String',
        ),
      ],
    ),
    MigrateEntry(
      tfType: 'aws_lambda_function_url',
      className: 'AwsLambdaFunctionUrl',
      barrel: 'lambda',
      kind: CatalogKind.resource,
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'authorization_type',
          dartName: 'authorizationType',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'function_name',
          dartName: 'functionName',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'invoke_mode',
          dartName: 'invokeMode',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'qualifier',
          dartName: 'qualifier',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'region',
          dartName: 'region',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'cors',
          dartName: 'cors',
          kind: MigrateSlotKind.helper,
          required: false,
          wrapped: false,
          helper: 'LambdaFunctionUrlCors',
        ),
      ],
      getters: <MigrateGetter>[
        MigrateGetter(tfName: 'id', dartName: 'id', dartType: 'String'),
        MigrateGetter(
          tfName: 'function_arn',
          dartName: 'functionArn',
          dartType: 'String',
        ),
        MigrateGetter(
          tfName: 'function_url',
          dartName: 'functionUrl',
          dartType: 'String',
        ),
        MigrateGetter(tfName: 'url_id', dartName: 'urlId', dartType: 'String'),
      ],
    ),
  ],
  helpers: <String, MigrateHelper>{
    'DataIamPolicyDocumentStatement': MigrateHelper(
      className: 'DataIamPolicyDocumentStatement',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'actions',
          dartName: 'actions',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'effect',
          dartName: 'effect',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'not_actions',
          dartName: 'notActions',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'not_resources',
          dartName: 'notResources',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'resources',
          dartName: 'resources',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'sid',
          dartName: 'sid',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'condition',
          dartName: 'condition',
          kind: MigrateSlotKind.helper,
          required: false,
          repeated: true,
          wrapped: false,
          helper: 'DataIamPolicyDocumentStatementCondition',
        ),
        MigrateSlot(
          tfName: 'not_principals',
          dartName: 'notPrincipals',
          kind: MigrateSlotKind.helper,
          required: false,
          repeated: true,
          wrapped: false,
          helper: 'DataIamPolicyDocumentStatementNotPrincipals',
        ),
        MigrateSlot(
          tfName: 'principals',
          dartName: 'principals',
          kind: MigrateSlotKind.helper,
          required: false,
          repeated: true,
          wrapped: false,
          helper: 'DataIamPolicyDocumentStatementPrincipals',
        ),
      ],
    ),
    'DataIamPolicyDocumentStatementCondition': MigrateHelper(
      className: 'DataIamPolicyDocumentStatementCondition',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'test',
          dartName: 'test',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'values',
          dartName: 'values',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'variable',
          dartName: 'variable',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
      ],
    ),
    'DataIamPolicyDocumentStatementNotPrincipals': MigrateHelper(
      className: 'DataIamPolicyDocumentStatementNotPrincipals',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'identifiers',
          dartName: 'identifiers',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'type',
          dartName: 'type',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
      ],
    ),
    'DataIamPolicyDocumentStatementPrincipals': MigrateHelper(
      className: 'DataIamPolicyDocumentStatementPrincipals',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'identifiers',
          dartName: 'identifiers',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'type',
          dartName: 'type',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
      ],
    ),
    'IamRoleInlinePolicy': MigrateHelper(
      className: 'IamRoleInlinePolicy',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'name',
          dartName: 'name',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'policy',
          dartName: 'policy',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
      ],
    ),
    'LambdaFunctionCapacityProviderConfig': MigrateHelper(
      className: 'LambdaFunctionCapacityProviderConfig',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'lambda_managed_instances_capacity_provider_config',
          dartName: 'lambdaManagedInstancesCapacityProviderConfig',
          kind: MigrateSlotKind.helper,
          required: true,
          wrapped: false,
          helper:
              'LambdaFunctionCapacityProviderConfigLambdaManagedInstancesCapacityProviderConfig',
        ),
      ],
    ),
    'LambdaFunctionCapacityProviderConfigLambdaManagedInstancesCapacityProviderConfig':
        MigrateHelper(
          className:
              'LambdaFunctionCapacityProviderConfigLambdaManagedInstancesCapacityProviderConfig',
          slots: <MigrateSlot>[
            MigrateSlot(
              tfName: 'capacity_provider_arn',
              dartName: 'capacityProviderArn',
              kind: MigrateSlotKind.scalar,
              required: true,
              dartType: 'String',
            ),
            MigrateSlot(
              tfName: 'execution_environment_memory_gib_per_vcpu',
              dartName: 'executionEnvironmentMemoryGibPerVcpu',
              kind: MigrateSlotKind.scalar,
              required: false,
              dartType: 'num',
            ),
            MigrateSlot(
              tfName: 'per_execution_environment_max_concurrency',
              dartName: 'perExecutionEnvironmentMaxConcurrency',
              kind: MigrateSlotKind.scalar,
              required: false,
              dartType: 'num',
            ),
          ],
        ),
    'LambdaFunctionDeadLetterConfig': MigrateHelper(
      className: 'LambdaFunctionDeadLetterConfig',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'target_arn',
          dartName: 'targetArn',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
      ],
    ),
    'LambdaFunctionDurableConfig': MigrateHelper(
      className: 'LambdaFunctionDurableConfig',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'execution_timeout',
          dartName: 'executionTimeout',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'num',
        ),
        MigrateSlot(
          tfName: 'retention_period',
          dartName: 'retentionPeriod',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'num',
        ),
      ],
    ),
    'LambdaFunctionEnvironment': MigrateHelper(
      className: 'LambdaFunctionEnvironment',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'variables',
          dartName: 'variables',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'Map<String, String>',
        ),
      ],
    ),
    'LambdaFunctionEphemeralStorage': MigrateHelper(
      className: 'LambdaFunctionEphemeralStorage',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'size',
          dartName: 'size',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'num',
        ),
      ],
    ),
    'LambdaFunctionFileSystemConfig': MigrateHelper(
      className: 'LambdaFunctionFileSystemConfig',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'arn',
          dartName: 'arn',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'local_mount_path',
          dartName: 'localMountPath',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
      ],
    ),
    'LambdaFunctionImageConfig': MigrateHelper(
      className: 'LambdaFunctionImageConfig',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'command',
          dartName: 'command',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'entry_point',
          dartName: 'entryPoint',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'working_directory',
          dartName: 'workingDirectory',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
      ],
    ),
    'LambdaFunctionLoggingConfig': MigrateHelper(
      className: 'LambdaFunctionLoggingConfig',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'application_log_level',
          dartName: 'applicationLogLevel',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'log_format',
          dartName: 'logFormat',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'log_group',
          dartName: 'logGroup',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
        MigrateSlot(
          tfName: 'system_log_level',
          dartName: 'systemLogLevel',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'String',
        ),
      ],
    ),
    'LambdaFunctionSnapStart': MigrateHelper(
      className: 'LambdaFunctionSnapStart',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'apply_on',
          dartName: 'applyOn',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
      ],
    ),
    'LambdaFunctionTenancyConfig': MigrateHelper(
      className: 'LambdaFunctionTenancyConfig',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'tenant_isolation_mode',
          dartName: 'tenantIsolationMode',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
      ],
    ),
    'LambdaFunctionTracingConfig': MigrateHelper(
      className: 'LambdaFunctionTracingConfig',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'mode',
          dartName: 'mode',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'String',
        ),
      ],
    ),
    'LambdaFunctionUrlCors': MigrateHelper(
      className: 'LambdaFunctionUrlCors',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'allow_credentials',
          dartName: 'allowCredentials',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'bool',
        ),
        MigrateSlot(
          tfName: 'allow_headers',
          dartName: 'allowHeaders',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'allow_methods',
          dartName: 'allowMethods',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'allow_origins',
          dartName: 'allowOrigins',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'expose_headers',
          dartName: 'exposeHeaders',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'max_age',
          dartName: 'maxAge',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'num',
        ),
      ],
    ),
    'LambdaFunctionVpcConfig': MigrateHelper(
      className: 'LambdaFunctionVpcConfig',
      slots: <MigrateSlot>[
        MigrateSlot(
          tfName: 'ipv6_allowed_for_dual_stack',
          dartName: 'ipv6AllowedForDualStack',
          kind: MigrateSlotKind.scalar,
          required: false,
          dartType: 'bool',
        ),
        MigrateSlot(
          tfName: 'security_group_ids',
          dartName: 'securityGroupIds',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'List<Object?>',
        ),
        MigrateSlot(
          tfName: 'subnet_ids',
          dartName: 'subnetIds',
          kind: MigrateSlotKind.scalar,
          required: true,
          dartType: 'List<Object?>',
        ),
      ],
    ),
  },
  enums: <String, MigrateEnum>{},
);
