/// Compute quickstart -- Phase 4.5.1 end-to-end example.
///
/// Defines a `NetworkStack` that provisions:
/// - a custom-mode VPC network (`main-vpc`),
/// - a regional external IPv4 address for a load balancer (`lb-vip-prod`),
///
/// demonstrating the `RoutingMode` / `AddressType` / `NetworkTier` enums
/// generated by Phase 4.5 Wave 0; enum values passed directly (Phase 4.5.1).
///
/// Wave 34 adds Cloud Filestore (NFS) on `main-vpc` plus a regional backup.
///
/// Wave 5 Batch 4 adds three compute-resource-scoped IAM member bindings
/// (instance, subnetwork, disk) -- each demonstrates the
/// "tightly scope permissions to a single VM / subnet / disk" pattern that
/// keeps service projects and tenants from over-reaching.
library;

import 'package:terradart_core/terradart_core.dart';
import 'package:terradart_google/compute.dart';
import 'package:terradart_google/data.dart';
import 'package:terradart_google/filestore.dart';
import 'package:terradart_google/iam.dart';
import 'package:terradart_google/project.dart';
import 'package:terradart_google/provider.dart';
import 'package:terradart_google/time.dart';

/// Network stack: a VPC + a public IP for a load balancer.
final class NetworkStack extends Stack {
  NetworkStack({required String projectId})
      : super(
          providers: [
            GoogleProvider(project: projectId, region: 'asia-northeast1'),
            const TimeProvider(),
          ],
        ) {
    // Enable the Compute + Filestore APIs and wait for propagation before
    // the resources below apply; otherwise apply fails with SERVICE_DISABLED.
    // Every API-gated resource below carries `dependsOn: apiDeps`.
    final apiDeps = Apis.enable(
      this,
      barrels: [Barrels.compute, Barrels.filestore],
      propagationDelay: const Duration(seconds: 60),
    );

    // Look up the live project so IAM bindings can reference the real
    // Google APIs service agent (`<number>@cloudservices.gserviceaccount.com`)
    // instead of a hardcoded, non-existent project number. The cloudservices
    // agent always exists for a project, so the binding is valid once the
    // real number is interpolated. Data source + IAM members are not
    // API-gated, so no `dependsOn: apiDeps` is required here.
    final current = addData(
      GoogleProject(
        localName: 'current',
        projectId: TfArg.literal(projectId),
      ),
    );

    // Service accounts that the instance- and disk-scoped IAM bindings below
    // grant access to. We create them in-stack (rather than referencing a
    // Google Group or an out-of-band SA that does not exist) so apply
    // succeeds end to end. SAs are not API-gated.
    final oncallSre = add(
      GoogleServiceAccount(
        localName: 'oncall_sre',
        accountId: TfArg.literal('oncall-sre'),
        displayName: TfArg.literal('On-call SRE (bastion power-cycle)'),
      ),
    );

    final mainVpc = GoogleComputeNetwork(
      localName: 'main',
      name: TfArg.literal('main-vpc'),
      // Custom-mode VPC: no auto-subnets, explicit subnetwork resources.
      autoCreateSubnetworks: TfArg.literal(false),
      routingMode: TfArg.literal(RoutingMode.regional),
      dependsOn: apiDeps,
    );
    add(mainVpc);

    add(
      GoogleComputeAddress(
        localName: 'lb_vip',
        name: TfArg.literal('lb-vip-prod'),
        region: TfArg.literal('asia-northeast1'),
        addressType: TfArg.literal(AddressType.external),
        networkTier: TfArg.literal(NetworkTier.premium),
        ipVersion: TfArg.literal(IpVersion.ipv4),
        dependsOn: apiDeps,
      ),
    );

    // ---- Subnetwork for Shared VPC IAM demo -------------------------------
    //
    // A workload subnet that a service project will attach VMs to. The
    // binding below grants the service project's compute SA the right to
    // *only* this subnet rather than the whole VPC.

    final workloadSubnet = GoogleComputeSubnetwork(
      localName: 'workload',
      name: TfArg.literal('workload-subnet'),
      region: TfArg.literal('asia-northeast1'),
      network: TfArg.ref(mainVpc.id),
      ipCidrRange: TfArg.literal('10.10.0.0/20'),
      dependsOn: apiDeps,
    );
    add(workloadSubnet);

    add(
      GoogleComputeRouter(
        localName: 'edge_router',
        name: TfArg.literal('edge-router'),
        region: TfArg.literal('asia-northeast1'),
        network: TfArg.ref(mainVpc.id),
        description: TfArg.literal('Cloud Router for private egress'),
        bgp: ComputeRouterBgp(
          advertiseMode: ComputeRouterBgpAdvertiseMode.defaultMode,
          asn: TfArg.literal(64514),
        ),
        dependsOn: apiDeps,
      ),
    );

    // ---- Wave 34: Filestore NFS on main-vpc -------------------------------

    final sharedNfs = add(
      GoogleFilestoreInstance(
        localName: 'shared_nfs',
        name: TfArg.literal('shared-nfs'),
        tier: TfArg.literal(FilestoreInstanceTier.basicHdd),
        // Basic-tier Filestore is zonal — location must be a zone, not a region.
        location: TfArg.literal('asia-northeast1-a'),
        fileShares: FilestoreInstanceFileShare(
          name: TfArg.literal('share1'),
          capacityGb: TfArg.literal(1024),
        ),
        networks: [
          FilestoreInstanceNetwork(
            network: TfArg.ref(mainVpc.id),
            modes: const [FilestoreInstanceNetworkMode.modeIpv4],
          ),
        ],
        dependsOn: apiDeps,
      ),
    );

    // GoogleFilestoreSnapshot is intentionally omitted: snapshots are not
    // supported on the BASIC_HDD tier (basic tiers support backups, not
    // snapshots — snapshots are for the zonal / high-scale-SSD / enterprise
    // tiers). Creating one 404s. Tracked in tool/example_debt.yaml.
    //
    // Backups, by contrast, ARE supported on basic tiers. A Filestore backup
    // is a regional resource, so its `location` is the region
    // (`asia-northeast1`) that contains the instance's zone
    // (`asia-northeast1-a`), not the zone itself.
    add(
      GoogleFilestoreBackup(
        localName: 'share_backup',
        name: TfArg.literal('share-backup-1'),
        location: TfArg.literal('asia-northeast1'),
        sourceInstance: TfArg.ref(sharedNfs.id),
        sourceFileShare: TfArg.literal('share1'),
      ),
    );

    // ---- IAM: subnetwork-scoped networkUser (Shared VPC) ------------------
    //
    // The classic Shared-VPC pattern: each service project's compute SA
    // gets `roles/compute.networkUser` on the exact subnets it can attach
    // to. Keeps cross-project tenants from spilling into the wrong region.

    add(
      GoogleComputeSubnetworkIamMember(
        localName: 'workload_subnet_user',
        subnetwork: TfArg.ref(workloadSubnet.nameRef),
        role: TfArg.literal('roles/compute.networkUser'),
        // Google APIs service agent for this project. Interpolate the real
        // project number from the `google_project` data source so the
        // member resolves to an identity that actually exists.
        member: TfArg.literal(
          'serviceAccount:${current.number.interpolation}'
          '@cloudservices.gserviceaccount.com',
        ),
      ),
    );

    // ---- Bastion VM with instance-scoped IAM ------------------------------
    //
    // A single jump-host VM that an on-call group can power-cycle. The
    // binding grants `roles/compute.instanceAdmin.v1` on *only* this VM,
    // avoiding a project-wide compute admin role for what is really a
    // one-host operation.

    final bastion = GoogleComputeInstance(
      localName: 'bastion',
      name: TfArg.literal('ops-bastion'),
      machineType: TfArg.literal('e2-small'),
      zone: TfArg.literal('asia-northeast1-a'),
      bootDisk: ComputeInstanceBootDisk(
        initializeParams: ComputeInstanceInitializeParams(
          image: TfArg.literal('debian-cloud/debian-12'),
        ),
      ),
      networkInterface: [
        ComputeInstanceNetworkInterface(
          subnetwork: TfArg.ref(workloadSubnet.selfLink),
        ),
      ],
      networkPerformanceConfig: const ComputeInstanceNetworkPerformanceConfig(
        totalEgressBandwidthTier:
            ComputeInstanceNetworkPerformanceConfigTotalEgressBandwidthTier
                .platformDefault,
      ),
      dependsOn: apiDeps,
    );
    add(bastion);

    add(
      GoogleComputeInstanceIamMember(
        localName: 'bastion_admin',
        instanceName: TfArg.ref(bastion.nameRef),
        role: TfArg.literal('roles/compute.instanceAdmin.v1'),
        // Google Groups can't be created via Terraform, so a `group:` member
        // referencing a non-existent group fails apply. Bind an in-stack SA
        // instead via its pre-formatted `serviceAccount:<email>` member.
        member: TfArg.ref(oncallSre.iamMember),
        zone: TfArg.literal('asia-northeast1-a'),
        dependsOn: [ResourceDependency(oncallSre)],
      ),
    );

    // ---- Disk-scoped IAM (backup-only access) -----------------------------
    //
    // Disk-scoped IAM (`google_compute_disk_iam_member`) needs a real disk to
    // attach to, but `google_compute_disk` is not curated yet, so there is no
    // applyable disk to bind in-stack. The binding is tracked in
    // tool/example_debt.yaml until a curated disk resource lands; re-add it
    // here (pointing at the in-stack disk) then.
  }
}
