/// Compute quickstart -- Phase 4.5 Wave 0 end-to-end example.
///
/// Defines a `NetworkStack` that provisions:
/// - a custom-mode VPC network (`main-vpc`),
/// - a regional external IPv4 address for a load balancer (`lb-vip-prod`),
///
/// demonstrating the `RoutingMode` / `AddressType` / `NetworkTier` enums
/// generated by Phase 4.5 Wave 0.
library;

import 'dart:convert' as dart_convert;
import 'dart:io';

import 'package:terradart_core/terradart_core.dart';
import 'package:terradart_google/terradart_google.dart';

/// Network stack: a VPC + a public IP for a load balancer.
class NetworkStack extends Stack {
  NetworkStack({required String projectId})
      : super(
          providers: [
            GoogleProvider(project: projectId, region: 'asia-northeast1'),
          ],
        ) {
    add(
      GoogleComputeNetwork(
        localName: 'main',
        name: TfArg.literal('main-vpc'),
        // Custom-mode VPC: no auto-subnets, explicit subnetwork resources.
        autoCreateSubnetworks: TfArg.literal(false),
        routingMode: TfArg.literal(RoutingMode.regional.terraformValue),
      ),
    );

    add(
      GoogleComputeAddress(
        localName: 'lb_vip',
        name: TfArg.literal('lb-vip-prod'),
        region: TfArg.literal('asia-northeast1'),
        addressType: TfArg.literal(AddressType.external.terraformValue),
        networkTier: TfArg.literal(NetworkTier.premium.terraformValue),
        ipVersion: TfArg.literal(IpVersion.ipv4.terraformValue),
      ),
    );
  }

  @override
  Future<void> synth({required String outDir}) async {
    final result = StackSynth.synth(this);
    await Directory(outDir).create(recursive: true);
    final tfFile = File('$outDir/main.tf.json');
    await tfFile.writeAsString(
      const dart_convert.JsonEncoder.withIndent('  ').convert(result.tfJson),
    );
  }
}
