/// Compute quickstart -- Phase 4.5.1 end-to-end example.
///
/// Defines a `NetworkStack` that provisions:
/// - a custom-mode VPC network (`main-vpc`) with a workload subnet,
/// - a regional external IPv4 address for a load balancer (`lb-vip-prod`),
/// - a Cloud Router interface, BGP peer, and Cloud NAT for private egress,
///
/// demonstrating the `RoutingMode` / `AddressType` / `NetworkTier` enums
/// generated by Phase 4.5 Wave 0; enum values passed directly (Phase 4.5.1).
///
/// Wave 34 adds Cloud Filestore (NFS) on `main-vpc` plus a regional backup.
///
/// Wave 5 Batch 4 adds three compute-resource-scoped IAM member bindings
/// (instance, subnetwork, disk) -- each demonstrates the
/// "tightly scope permissions to a single VM / subnet / disk" pattern that
/// keeps service projects and tenants from over-reaching.
///
/// Wave adds bulk per-instance MIG config, network firewall policy IAM
/// member, and a zonal VM extension policy (Ops Agent).
///
/// Regional network firewall policy + rule + IAM member extend the global
/// network firewall policy demo for the regional surface.
///
/// Also covers a zonal `GoogleComputeInstantSnapshot` (+ IAM member), a
/// durable `GoogleComputeSnapshot` (+ IAM member), and a custom
/// `GoogleComputeImage` (+ IAM member) promoted from that snapshot,
/// alongside the regional instant-snapshot demo.
///
/// Unmanaged instance groups (`GoogleComputeInstanceGroup` + membership +
/// named port), `GoogleComputeAttachedDisk`,
/// `GoogleComputeInstanceFromTemplate`, and
/// `GoogleComputeDiskAsyncReplication` round out the zonal Compute surface.
///
/// Also covers network firewall association/rule/`with_rules` (global +
/// regional), a PSC `GoogleComputeNetworkAttachment`, NEG
/// `GoogleComputeNetworkEndpoints`, legacy
/// `GoogleComputeHttpHealthCheck` / `GoogleComputeHttpsHealthCheck`, a
/// legacy `GoogleComputeTargetPool` / `GoogleComputeTargetInstance`,
/// Cloud Router NAT extra IPs + BGP route policy, regional health
/// aggregation policy, regional instance template + region MIG
/// per-instance config, zonal per-instance config, and resource-policy
/// attachments (instance + regional disk).
library;

import 'dart:convert';

import 'package:terradart_core/terradart_core.dart';
import 'package:terradart_google/compute.dart';
import 'package:terradart_google/data.dart';
import 'package:terradart_google/filestore.dart';
import 'package:terradart_google/iam.dart';
import 'package:terradart_google/iap.dart';
import 'package:terradart_google/project.dart';
import 'package:terradart_google/provider.dart';
import 'package:terradart_time/terradart_time.dart';

String _iamPolicyDataJson({required String role, required String member}) {
  return jsonEncode({
    'bindings': [
      {
        'role': role,
        'members': [member],
      },
    ],
  });
}

/// Network stack: a VPC + a public IP for a load balancer.
final class NetworkStack extends Stack {
  NetworkStack({required String projectId})
    : super(
        providers: [
          GoogleProvider(project: projectId, region: 'asia-northeast1'),
          const TimeProvider(),
        ],
      ) {
    // Enable the Compute + Filestore APIs and wait for propagation before
    // the resources below apply; otherwise apply fails with SERVICE_DISABLED.
    // Every API-gated resource below carries `dependsOn: apiDeps`.
    final apiDeps = Apis.enable(
      this,
      barrels: [Barrels.compute, Barrels.filestore, Barrels.iapApi],
      propagationDelay: const Duration(seconds: 60),
    );

    // Look up the live project so IAM bindings can reference the real
    // Google APIs service agent (`<number>@cloudservices.gserviceaccount.com`)
    // instead of a hardcoded, non-existent project number. The cloudservices
    // agent always exists for a project, so the binding is valid once the
    // real number is interpolated. Data source + IAM members are not
    // API-gated, so no `dependsOn: apiDeps` is required here.
    final current = addData(
      GoogleProject(localName: 'current', projectId: .literal(projectId)),
    );

    // Service accounts that the instance- and disk-scoped IAM bindings below
    // grant access to. We create them in-stack (rather than referencing a
    // Google Group or an out-of-band SA that does not exist) so apply
    // succeeds end to end. SAs are not API-gated.
    final oncallSre = add(
      GoogleServiceAccount(
        localName: 'oncall_sre',
        accountId: .literal('oncall-sre'),
        displayName: .literal('On-call SRE (bastion power-cycle)'),
      ),
    );

    final mainVpc = GoogleComputeNetwork(
      localName: 'main',
      name: .literal('main-vpc'),
      // Custom-mode VPC: no auto-subnets, explicit subnetwork resources.
      autoCreateSubnetworks: .literal(false),
      routingMode: .literal(.regional),
      dependsOn: apiDeps,
    );
    add(mainVpc);

    add(
      GoogleComputeAddress(
        localName: 'lb_vip',
        name: .literal('lb-vip-prod'),
        region: .literal('asia-northeast1'),
        addressType: .literal(.external),
        networkTier: .literal(.premium),
        ipVersion: .literal(.ipv4),
        dependsOn: apiDeps,
      ),
    );

    // ---- Subnetwork for Shared VPC IAM demo -------------------------------
    //
    // A workload subnet that a service project will attach VMs to. The
    // binding below grants the service project's compute SA the right to
    // *only* this subnet rather than the whole VPC.

    final workloadSubnet = GoogleComputeSubnetwork(
      localName: 'workload',
      name: .literal('workload-subnet'),
      region: .literal('asia-northeast1'),
      network: mainVpc.ref,
      ipCidrRange: .literal('10.10.0.0/20'),
      dependsOn: apiDeps,
    );
    add(workloadSubnet);

    final edgeRouter = add(
      GoogleComputeRouter(
        localName: 'edge_router',
        name: .literal('edge-router'),
        region: .literal('asia-northeast1'),
        network: .network(mainVpc.ref),
        description: .literal('Cloud Router for private egress'),
        bgp: ComputeRouterBgp(
          advertiseMode: ComputeRouterBgpAdvertiseMode.defaultMode,
          asn: .literal(64514),
        ),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeRouterInterface(
        localName: 'edge_router_if0',
        name: .literal('edge-router-if0'),
        router: edgeRouter.ref,
        region: .literal('asia-northeast1'),
        ipRange: .literal('169.254.0.1/30'),
        dependsOn: [ResourceDependency(edgeRouter)],
      ),
    );

    add(
      GoogleComputeRouterPeer(
        localName: 'edge_router_peer0',
        name: .literal('edge-router-peer0'),
        router: edgeRouter.ref,
        interface: .literal('edge-router-if0'),
        peerAsn: .literal(65001),
        region: .literal('asia-northeast1'),
        peerIpAddress: .literal('169.254.0.2'),
        dependsOn: [ResourceDependency(edgeRouter)],
      ),
    );

    final egressNatIp0 = add(
      GoogleComputeAddress(
        localName: 'egress_nat_ip0',
        name: .literal('egress-nat-ip0'),
        region: .literal('asia-northeast1'),
        addressType: .literal(.external),
        dependsOn: apiDeps,
      ),
    );

    final egressNatIp1 = add(
      GoogleComputeAddress(
        localName: 'egress_nat_ip1',
        name: .literal('egress-nat-ip1'),
        region: .literal('asia-northeast1'),
        addressType: .literal(.external),
        dependsOn: apiDeps,
      ),
    );

    final egressNat = add(
      GoogleComputeRouterNat(
        localName: 'egress_nat',
        name: .literal('egress-nat'),
        router: edgeRouter.ref,
        region: .literal('asia-northeast1'),
        natIpAllocateOption: .literal(.manualOnly),
        initialNatIps: .literal([egressNatIp0.ref]),
        sourceSubnetworkIpRangesToNat: .literal(
          ComputeRouterNatSourceSubnetworkIpRangesToNat
              .allSubnetworksAllIpRanges,
        ),
        dependsOn: [
          ResourceDependency(edgeRouter),
          ResourceDependency(egressNatIp0),
        ],
      ),
    );

    add(
      GoogleComputeRouterNatAddress(
        localName: 'egress_nat_extra_ip',
        router: edgeRouter.ref,
        routerNat: egressNat.ref,
        region: .literal('asia-northeast1'),
        natIps: .literal([egressNatIp1.ref]),
        dependsOn: [
          ResourceDependency(egressNat),
          ResourceDependency(egressNatIp1),
        ],
      ),
    );

    add(
      GoogleComputeRouterRoutePolicy(
        localName: 'edge_export_policy',
        name: .literal('edge-export-policy'),
        router: edgeRouter.ref,
        region: .literal('asia-northeast1'),
        type: .literal(.routePolicyTypeExport),
        terms: [
          ComputeRouterRoutePolicyTerms(
            priority: .literal(1),
            match: ComputeRouterRoutePolicyMatch(
              expression: .literal("destination == '10.10.0.0/20'"),
            ),
            actions: [
              ComputeRouterRoutePolicyActions(expression: .literal('accept()')),
            ],
          ),
        ],
        dependsOn: [ResourceDependency(edgeRouter)],
      ),
    );

    // ---- Wave 34: Filestore NFS on main-vpc -------------------------------

    final sharedNfs = add(
      GoogleFilestoreInstance(
        localName: 'shared_nfs',
        name: .literal('shared-nfs'),
        tier: .literal(.basicHdd),
        // Basic-tier Filestore is zonal — location must be a zone, not a region.
        location: .literal('asia-northeast1-a'),
        fileShares: FilestoreInstanceFileShares(
          name: .literal('share1'),
          capacityGb: .literal(1024),
        ),
        networks: [
          FilestoreInstanceNetworks(
            network: mainVpc.ref,
            modes: [.literal(.modeIpv4)],
          ),
        ],
        dependsOn: apiDeps,
      ),
    );

    // GoogleFilestoreSnapshot lives in filestore_quickstart: snapshot-capable
    // tiers need High Scale SSD / ZONAL / Enterprise pools that
    // terradart-validate lacks in asia-northeast1 (quota 0).
    //
    // Backups ARE supported on basic tiers. A Filestore backup is a regional
    // is a regional resource, so its `location` is the region
    // (`asia-northeast1`) that contains the instance's zone
    // (`asia-northeast1-a`), not the zone itself.
    add(
      GoogleFilestoreBackup(
        localName: 'share_backup',
        name: .literal('share-backup-1'),
        location: .literal('asia-northeast1'),
        sourceInstance: sharedNfs.ref,
        sourceFileShare: .literal('share1'),
      ),
    );

    // ---- IAM: subnetwork-scoped networkUser (Shared VPC) ------------------
    //
    // The classic Shared-VPC pattern: each service project's compute SA
    // gets `roles/compute.networkUser` on the exact subnets it can attach
    // to. Keeps cross-project tenants from spilling into the wrong region.

    add(
      GoogleComputeSubnetworkIamMember(
        localName: 'workload_subnet_user',
        subnetwork: workloadSubnet.ref,
        role: .literal('roles/compute.networkUser'),
        // Google APIs service agent for this project. Interpolate the real
        // project number from the `google_project` data source so the
        // member resolves to an identity that actually exists.
        member: .literal(
          'serviceAccount:${current.number.interpolation}'
          '@cloudservices.gserviceaccount.com',
        ),
      ),
    );

    // ---- Bastion VM with instance-scoped IAM ------------------------------
    //
    // A single jump-host VM that an on-call group can power-cycle. The
    // binding grants `roles/compute.instanceAdmin.v1` on *only* this VM,
    // avoiding a project-wide compute admin role for what is really a
    // one-host operation.

    final bastion = GoogleComputeInstance(
      localName: 'bastion',
      name: .literal('ops-bastion'),
      machineType: .literal('e2-small'),
      zone: .literal('asia-northeast1-a'),
      bootDisk: ComputeInstanceBootDisk(
        initializeParams: ComputeInstanceInitializeParams(
          image: .literal('debian-cloud/debian-12'),
        ),
      ),
      networkInterface: [
        ComputeInstanceNetworkInterface(subnetwork: workloadSubnet.ref),
      ],
      networkPerformanceConfig: ComputeInstanceNetworkPerformanceConfig(
        totalEgressBandwidthTier: .literal(.platformDefault),
      ),
      dependsOn: apiDeps,
    );
    add(bastion);

    add(
      GoogleComputeInstanceIamMember(
        localName: 'bastion_admin',
        instanceName: .ref(bastion.nameRef),
        role: .literal('roles/compute.instanceAdmin.v1'),
        // Google Groups can't be created via Terraform, so a `group:` member
        // referencing a non-existent group fails apply. Bind an in-stack SA
        // instead via its pre-formatted `serviceAccount:<email>` member.
        member: .ref(oncallSre.iamMember),
        zone: .literal('asia-northeast1-a'),
        dependsOn: [ResourceDependency(oncallSre)],
      ),
    );

    // IAP TCP forwarding to the bastion (project-scoped tunnel instance path).
    add(
      GoogleIapTunnelInstanceIamMember(
        localName: 'bastion_iap_tunnel',
        instance: .ref(bastion.nameRef),
        role: .literal('roles/iap.tunnelResourceAccessor'),
        member: .ref(oncallSre.iamMember),
        zone: .literal('asia-northeast1-a'),
        dependsOn: [
          ResourceDependency(bastion),
          ResourceDependency(oncallSre),
          ...apiDeps,
        ],
      ),
    );

    // ---- Regional disk + instant snapshot IAM --------------------------------
    //
    // Regional instant snapshots require a regional persistent disk as their
    // source (`google_compute_region_disk`). We snapshot the disk, then grant
    // the on-call SA read access on the snapshot resource itself — the
    // fine-grained "backup operator can see the snapshot but not mutate the
    // disk" pattern.

    final backupDisk = add(
      GoogleComputeRegionDisk(
        localName: 'backup_data',
        name: .literal('backup-data'),
        region: .literal('asia-northeast1'),
        type: .literal('pd-balanced'),
        size: .literal(10),
        replicaZones: .literal(['asia-northeast1-a', 'asia-northeast1-b']),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeRegionDiskIamMember(
        localName: 'backup_disk_viewer',
        name: .ref(backupDisk.nameRef),
        role: .literal('roles/compute.viewer'),
        member: .ref(oncallSre.iamMember),
        region: .literal('asia-northeast1'),
        dependsOn: [
          ResourceDependency(backupDisk),
          ResourceDependency(oncallSre),
        ],
      ),
    );

    final bastionInstant = add(
      GoogleComputeRegionInstantSnapshot(
        localName: 'bastion_instant',
        name: .literal('bastion-instant-1'),
        sourceDisk: backupDisk.ref,
        region: .literal('asia-northeast1'),
        dependsOn: [ResourceDependency(backupDisk)],
      ),
    );

    add(
      GoogleComputeRegionInstantSnapshotIamMember(
        localName: 'bastion_instant_viewer',
        name: .ref(bastionInstant.nameRef),
        role: .literal('roles/compute.viewer'),
        member: .ref(oncallSre.iamMember),
        region: .literal('asia-northeast1'),
        dependsOn: [
          ResourceDependency(oncallSre),
          ResourceDependency(bastionInstant),
        ],
      ),
    );

    final bastionInstantBinding = add(
      GoogleComputeRegionInstantSnapshotIamBinding(
        localName: 'bastion_instant_binding',
        name: .ref(bastionInstant.nameRef),
        role: .literal('roles/compute.viewer'),
        members: .literal([oncallSre.iamMember.interpolation]),
        region: .literal('asia-northeast1'),
        dependsOn: [
          ResourceDependency(oncallSre),
          ResourceDependency(bastionInstant),
        ],
      ),
    );

    add(
      GoogleComputeRegionInstantSnapshotIamPolicy(
        localName: 'bastion_instant_policy',
        name: .ref(bastionInstant.nameRef),
        policyData: .literal(
          _iamPolicyDataJson(
            role: 'roles/compute.viewer',
            member:
                'serviceAccount:oncall-sre@$projectId.iam.gserviceaccount.com',
          ),
        ),
        region: .literal('asia-northeast1'),
        dependsOn: [
          ResourceDependency(bastionInstant),
          ResourceDependency(bastionInstantBinding),
        ],
      ),
    );

    // ---- Zonal disk + disk-scoped IAM (backup-only access) ------------------
    //
    // A standalone zonal PD that backup tooling can read without project-wide
    // compute admin. The binding grants `roles/compute.viewer` on *only* this
    // disk — the instance-scoped admin above stays untouched.

    final scratchDisk = add(
      GoogleComputeDisk(
        localName: 'ops_scratch',
        name: .literal('ops-scratch'),
        zone: .literal('asia-northeast1-a'),
        type: .literal('pd-balanced'),
        size: .literal(10),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeDiskIamMember(
        localName: 'scratch_disk_viewer',
        name: .ref(scratchDisk.nameRef),
        role: .literal('roles/compute.viewer'),
        member: .ref(oncallSre.iamMember),
        zone: .literal('asia-northeast1-a'),
        dependsOn: [
          ResourceDependency(scratchDisk),
          ResourceDependency(oncallSre),
        ],
      ),
    );

    // Zonal Instant Snapshot of the empty pd-balanced disk (Compute Instant
    // Snapshot IAM parent). Zone must match the source disk.
    final scratchInstant = add(
      GoogleComputeInstantSnapshot(
        localName: 'scratch_instant',
        name: .literal('ops-scratch-instant'),
        sourceDisk: scratchDisk.ref,
        zone: .literal('asia-northeast1-a'),
        dependsOn: [ResourceDependency(scratchDisk)],
      ),
    );

    add(
      GoogleComputeInstantSnapshotIamMember(
        localName: 'scratch_instant_viewer',
        name: .ref(scratchInstant.nameRef),
        role: .literal('roles/compute.viewer'),
        member: .ref(oncallSre.iamMember),
        zone: .literal('asia-northeast1-a'),
        dependsOn: [
          ResourceDependency(oncallSre),
          ResourceDependency(scratchInstant),
        ],
      ),
    );

    // Durable PD Snapshot of the scratch disk (Compute Snapshot IAM parent).
    // Exactly one source: disk self-link (not the instant snapshot).
    final scratchSnapshot = add(
      GoogleComputeSnapshot(
        localName: 'scratch_snapshot',
        name: .literal('ops-scratch-snapshot'),
        source: .disk(sourceDisk: .ref(scratchDisk.selfLink)),
        storageLocations: .literal(['asia-northeast1']),
        dependsOn: [ResourceDependency(scratchDisk)],
      ),
    );

    add(
      GoogleComputeSnapshotIamMember(
        localName: 'scratch_snapshot_viewer',
        name: .ref(scratchSnapshot.nameRef),
        role: .literal('roles/compute.viewer'),
        member: .ref(oncallSre.iamMember),
        dependsOn: [
          ResourceDependency(oncallSre),
          ResourceDependency(scratchSnapshot),
        ],
      ),
    );

    // Custom Image from the PD Snapshot (Compute Image IAM parent).
    final scratchImage = add(
      GoogleComputeImage(
        localName: 'scratch_image',
        name: .literal('ops-scratch-image'),
        source: .snapshot(sourceSnapshot: .ref(scratchSnapshot.selfLink)),
        family: .literal('ops-scratch'),
        storageLocations: .literal(['asia-northeast1']),
        dependsOn: [ResourceDependency(scratchSnapshot)],
      ),
    );

    add(
      GoogleComputeImageIamMember(
        localName: 'scratch_image_viewer',
        image: .ref(scratchImage.nameRef),
        role: .literal('roles/compute.viewer'),
        member: .ref(oncallSre.iamMember),
        dependsOn: [
          ResourceDependency(oncallSre),
          ResourceDependency(scratchImage),
        ],
      ),
    );

    // ---- Bulk per-instance MIG config ---------------------------------------
    //
    // A zonal MIG in BULK target-size mode plus a bulk per-instance config
    // that names the VMs the MIG should create in one shot (the Terraform
    // replacement for multiple PerInstanceConfig resources).

    final bulkWorkerTemplate = add(
      GoogleComputeInstanceTemplate(
        localName: 'bulk_worker_template',
        namePrefix: .literal('bulk-worker-'),
        machineType: .literal('e2-micro'),
        disk: [
          ComputeInstanceTemplateDisk(
            boot: .literal(true),
            sourceImage: .literal('debian-cloud/debian-12'),
            autoDelete: .literal(true),
          ),
        ],
        networkInterface: [
          ComputeInstanceTemplateNetworkInterface(
            network: mainVpc.ref,
            subnetwork: workloadSubnet.ref,
          ),
        ],
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeInstanceTemplateIamMember(
        localName: 'bulk_worker_template_viewer',
        name: .ref(bulkWorkerTemplate.nameRef),
        role: .literal('roles/compute.viewer'),
        member: .ref(oncallSre.iamMember),
        dependsOn: [
          ResourceDependency(bulkWorkerTemplate),
          ResourceDependency(oncallSre),
        ],
      ),
    );

    final bulkWorkersMig = add(
      GoogleComputeInstanceGroupManager(
        localName: 'bulk_workers',
        name: .literal('bulk-workers'),
        zone: .literal('asia-northeast1-a'),
        baseInstanceName: .literal('bulk-worker'),
        versions: [
          ComputeInstanceGroupManagerVersion(
            name: .literal('default'),
            instanceTemplate: .ref(bulkWorkerTemplate.selfLink),
          ),
        ],
        // Do NOT set target_size_policies.mode=BULK explicitly: the GA API
        // rejects it ("Bulk mode is not supported for this Managed Instance
        // Group") — upstream's own example attaches bulk per-instance configs
        // to a plain MIG and only ignores target_size drift.
        lifecycle: const LifecycleOptions(ignoreChanges: ['target_size']),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeBulkPerInstanceConfig(
        localName: 'bulk_workers_cfg',
        instanceGroupManager: bulkWorkersMig.ref,
        zone: .literal('asia-northeast1-a'),
        instances: [
          ComputeBulkPerInstanceConfigInstances(
            name: .literal('bulk-worker-1'),
          ),
        ],
        dependsOn: [ResourceDependency(bulkWorkersMig)],
      ),
    );

    // Stateful per-instance config on a dedicated zonal MIG (metadata only).
    final picDemoMig = add(
      GoogleComputeInstanceGroupManager(
        localName: 'pic_demo',
        name: .literal('pic-demo'),
        zone: .literal('asia-northeast1-a'),
        baseInstanceName: .literal('pic-demo'),
        versions: [
          ComputeInstanceGroupManagerVersion(
            name: .literal('default'),
            instanceTemplate: .ref(bulkWorkerTemplate.selfLink),
          ),
        ],
        lifecycle: const LifecycleOptions(ignoreChanges: ['target_size']),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputePerInstanceConfig(
        localName: 'pic_demo_1',
        instanceGroupManager: picDemoMig.ref,
        name: .literal('pic-demo-1'),
        zone: .literal('asia-northeast1-a'),
        preservedState: ComputePerInstanceConfigPreservedState(
          metadata: .literal({'role': 'pic-demo'}),
        ),
        removeInstanceOnDestroy: .literal(true),
        dependsOn: [ResourceDependency(picDemoMig)],
      ),
    );

    // ---- Network firewall policy IAM member -------------------------------
    //
    // A global network firewall policy plus a resource-scoped IAM member so
    // the on-call SA can read the policy without project-wide network admin.

    final edgeFirewallPolicy = add(
      GoogleComputeNetworkFirewallPolicy(
        localName: 'ops_edge_policy',
        name: .literal('ops-edge-policy'),
        description: .literal('Global network firewall policy (IAM demo)'),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeNetworkFirewallPolicyIamMember(
        localName: 'ops_edge_policy_viewer',
        name: .ref(edgeFirewallPolicy.nameRef),
        role: .literal('roles/compute.viewer'),
        member: .ref(oncallSre.iamMember),
        dependsOn: [
          ResourceDependency(edgeFirewallPolicy),
          ResourceDependency(oncallSre),
        ],
      ),
    );

    add(
      GoogleComputeNetworkFirewallPolicyAssociation(
        localName: 'ops_edge_policy_assoc',
        name: .literal('ops-edge-policy-assoc'),
        firewallPolicy: edgeFirewallPolicy.ref,
        attachmentTarget: mainVpc.ref,
        dependsOn: [
          ResourceDependency(edgeFirewallPolicy),
          ResourceDependency(mainVpc),
        ],
      ),
    );

    add(
      GoogleComputeNetworkFirewallPolicyRule(
        localName: 'ops_edge_allow_https',
        firewallPolicy: edgeFirewallPolicy.ref,
        priority: .literal(1000),
        action: .literal('allow'),
        direction: .literal(.ingress),
        ruleName: .literal('allow-https'),
        description: .literal('Allow ingress TCP 443 (global demo)'),
        match: ComputeNetworkFirewallPolicyRuleMatch(
          srcIpRanges: .literal(['0.0.0.0/0']),
          layer4Configs: [
            ComputeNetworkFirewallPolicyRuleLayer4Configs(
              ipProtocol: .literal('tcp'),
              ports: .literal(['443']),
            ),
          ],
        ),
        dependsOn: [ResourceDependency(edgeFirewallPolicy)],
      ),
    );

    // Embedded-rules variant of a global network firewall policy (separate
    // from the split policy + rule factories above).
    add(
      GoogleComputeNetworkFirewallPolicyWithRules(
        localName: 'ops_edge_with_rules',
        name: .literal('ops-edge-with-rules'),
        description: .literal('Global firewall policy with embedded rules'),
        rule: [
          ComputeNetworkFirewallPolicyWithRulesRule(
            action: .literal('allow'),
            direction: .literal(.ingress),
            priority: .literal(1000),
            ruleName: .literal('allow-https'),
            match: ComputeNetworkFirewallPolicyWithRulesMatch(
              srcIpRanges: .literal(['0.0.0.0/0']),
              layer4Config: [
                ComputeNetworkFirewallPolicyWithRulesLayer4Config(
                  ipProtocol: .literal('tcp'),
                  ports: .literal(['443']),
                ),
              ],
            ),
          ),
        ],
        dependsOn: apiDeps,
      ),
    );

    // ---- PSC network attachment + NEG endpoints + legacy HTTP HC ----------

    add(
      GoogleComputeNetworkAttachment(
        localName: 'ops_psc_attachment',
        name: .literal('ops-psc-attachment'),
        region: .literal('asia-northeast1'),
        connectionPreference: .literal(.acceptAutomatic),
        subnetworks: .literal([workloadSubnet.ref]),
        dependsOn: [ResourceDependency(workloadSubnet), ...apiDeps],
      ),
    );

    final bastionNeg = add(
      GoogleComputeNetworkEndpointGroup(
        localName: 'ops_bastion_neg',
        name: .literal('ops-bastion-neg'),
        zone: .literal('asia-northeast1-a'),
        network: mainVpc.ref,
        subnetwork: workloadSubnet.ref,
        networkEndpointType: .literal(.gceVmIpPort),
        defaultPort: .literal(80),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeNetworkEndpoints(
        localName: 'ops_bastion_neg_eps',
        networkEndpointGroup: bastionNeg.ref,
        zone: .literal('asia-northeast1-a'),
        networkEndpoints: [
          ComputeNetworkEndpoints(
            instance: bastion.ref,
            port: .literal(80),
          ),
        ],
        dependsOn: [
          ResourceDependency(bastionNeg),
          ResourceDependency(bastion),
        ],
      ),
    );

    final legacyHttpHc = add(
      GoogleComputeHttpHealthCheck(
        localName: 'ops_legacy_http_hc',
        name: .literal('ops-legacy-http-hc'),
        requestPath: .literal('/'),
        port: .literal(80),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeHttpsHealthCheck(
        localName: 'ops_legacy_https_hc',
        name: .literal('ops-legacy-https-hc'),
        requestPath: .literal('/'),
        port: .literal(443),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeTargetPool(
        localName: 'ops_legacy_target_pool',
        name: .literal('ops-legacy-target-pool'),
        region: .literal('asia-northeast1'),
        description: .literal('Legacy NLB target pool (demo)'),
        instances: .literal([bastion.selfLink.interpolation]),
        healthChecks: .literal([legacyHttpHc.selfLink.interpolation]),
        dependsOn: [
          ResourceDependency(bastion),
          ResourceDependency(legacyHttpHc),
        ],
      ),
    );

    add(
      GoogleComputeTargetInstance(
        localName: 'ops_bastion_target',
        name: .literal('ops-bastion-target'),
        instance: bastion.ref,
        zone: .literal('asia-northeast1-a'),
        description: .literal('Protocol-forwarding target for the bastion'),
        natPolicy: .literal(.noNat),
        dependsOn: [ResourceDependency(bastion)],
      ),
    );

    // ---- Regional network firewall policy + rule + IAM --------------------
    //
    // Mirrors the global policy demo above for the regional surface: a
    // policy, one ingress allow rule (TCP 443), and a viewer IAM member.

    final regionalFirewallPolicy = add(
      GoogleComputeRegionNetworkFirewallPolicy(
        localName: 'ops_regional_edge_policy',
        name: .literal('ops-regional-edge-policy'),
        region: .literal('asia-northeast1'),
        description: .literal(
          'Regional network firewall policy (rule + IAM demo)',
        ),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeRegionNetworkFirewallPolicyRule(
        localName: 'ops_regional_allow_https',
        firewallPolicy: regionalFirewallPolicy.ref,
        region: .literal('asia-northeast1'),
        priority: .literal(1000),
        action: .literal('allow'),
        direction: .literal(.ingress),
        ruleName: .literal('allow-https'),
        description: .literal('Allow ingress TCP 443 (demo)'),
        match: ComputeRegionNetworkFirewallPolicyRuleMatch(
          srcIpRanges: .literal(['0.0.0.0/0']),
          layer4Configs: [
            ComputeRegionNetworkFirewallPolicyRuleLayer4Configs(
              ipProtocol: .literal('tcp'),
              ports: .literal(['443']),
            ),
          ],
        ),
        dependsOn: [ResourceDependency(regionalFirewallPolicy)],
      ),
    );

    add(
      GoogleComputeRegionNetworkFirewallPolicyIamMember(
        localName: 'ops_regional_edge_policy_viewer',
        name: .ref(regionalFirewallPolicy.nameRef),
        region: .literal('asia-northeast1'),
        role: .literal('roles/compute.viewer'),
        member: .ref(oncallSre.iamMember),
        dependsOn: [
          ResourceDependency(regionalFirewallPolicy),
          ResourceDependency(oncallSre),
        ],
      ),
    );

    add(
      GoogleComputeRegionNetworkFirewallPolicyAssociation(
        localName: 'ops_regional_edge_policy_assoc',
        name: .literal('ops-regional-edge-policy-assoc'),
        firewallPolicy: regionalFirewallPolicy.ref,
        attachmentTarget: mainVpc.ref,
        region: .literal('asia-northeast1'),
        dependsOn: [
          ResourceDependency(regionalFirewallPolicy),
          ResourceDependency(mainVpc),
        ],
      ),
    );

    add(
      GoogleComputeRegionNetworkFirewallPolicyWithRules(
        localName: 'ops_regional_edge_with_rules',
        name: .literal('ops-regional-edge-with-rules'),
        region: .literal('asia-northeast1'),
        description: .literal('Regional firewall policy with embedded rules'),
        rule: [
          ComputeRegionNetworkFirewallPolicyWithRulesRule(
            action: .literal('allow'),
            direction: .literal(.ingress),
            priority: .literal(1000),
            ruleName: .literal('allow-https'),
            match: ComputeRegionNetworkFirewallPolicyWithRulesMatch(
              srcIpRanges: .literal(['0.0.0.0/0']),
              layer4Config: [
                ComputeRegionNetworkFirewallPolicyWithRulesLayer4Config(
                  ipProtocol: .literal('tcp'),
                  ports: .literal(['443']),
                ),
              ],
            ),
          ),
        ],
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeRegionHealthAggregationPolicy(
        localName: 'ops_health_agg',
        name: .literal('ops-health-agg'),
        region: .literal('asia-northeast1'),
        policyType: .literal(.backendServicePolicy),
        healthyPercentThreshold: .literal(60),
        minHealthyThreshold: .literal(1),
        description: .literal('Regional health aggregation policy (demo)'),
        dependsOn: apiDeps,
      ),
    );

    // ---- Attached disk + unmanaged IG + instance-from-template ------------
    //
    // Extra PD attached to the bastion; an unmanaged instance group that
    // claims the bastion via membership + a named port for LB targeting;
    // and a one-off VM cloned from the bulk-worker template.

    final bastionDataDisk = add(
      GoogleComputeDisk(
        localName: 'bastion_data',
        name: .literal('ops-bastion-data'),
        zone: .literal('asia-northeast1-a'),
        type: .literal('pd-balanced'),
        size: .literal(10),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeAttachedDisk(
        localName: 'bastion_data_attach',
        disk: .ref(bastionDataDisk.selfLink),
        instance: .ref(bastion.selfLink),
        zone: .literal('asia-northeast1-a'),
        dependsOn: [
          ResourceDependency(bastion),
          ResourceDependency(bastionDataDisk),
        ],
      ),
    );

    final opsUnmanagedGroup = add(
      GoogleComputeInstanceGroup(
        localName: 'ops_unmanaged',
        name: .literal('ops-unmanaged'),
        zone: .literal('asia-northeast1-a'),
        network: mainVpc.ref,
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeInstanceGroupMembership(
        localName: 'ops_unmanaged_bastion',
        instance: bastion.ref,
        instanceGroup: opsUnmanagedGroup.ref,
        zone: .literal('asia-northeast1-a'),
        dependsOn: [
          ResourceDependency(bastion),
          ResourceDependency(opsUnmanagedGroup),
        ],
      ),
    );

    add(
      GoogleComputeInstanceGroupNamedPort(
        localName: 'ops_unmanaged_http',
        group: opsUnmanagedGroup.ref,
        name: .literal('http'),
        port: .literal(80),
        zone: .literal('asia-northeast1-a'),
        dependsOn: [ResourceDependency(opsUnmanagedGroup)],
      ),
    );

    add(
      GoogleComputeInstanceFromTemplate(
        localName: 'templated_worker',
        name: .literal('templated-worker'),
        sourceInstanceTemplate: .ref(bulkWorkerTemplate.selfLink),
        zone: .literal('asia-northeast1-a'),
        dependsOn: [ResourceDependency(bulkWorkerTemplate), ...apiDeps],
      ),
    );

    // ---- Disk async replication (cross-region) ----------------------------
    //
    // Primary PD in asia-northeast1-a, secondary of the same size/type in
    // asia-northeast2-a (Osaka). The replication resource only wires the
    // relationship — both disks must already exist.

    final asyncPrimary = add(
      GoogleComputeDisk(
        localName: 'async_primary',
        name: .literal('ops-async-primary'),
        zone: .literal('asia-northeast1-a'),
        type: .literal('pd-balanced'),
        size: .literal(10),
        dependsOn: apiDeps,
      ),
    );

    final asyncSecondary = add(
      GoogleComputeDisk(
        localName: 'async_secondary',
        name: .literal('ops-async-secondary'),
        zone: .literal('asia-northeast2-a'),
        type: .literal('pd-balanced'),
        size: .literal(10),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeDiskAsyncReplication(
        localName: 'async_replication',
        primaryDisk: .ref(asyncPrimary.id),
        secondaryDisk: ComputeDiskAsyncReplicationSecondaryDisk(
          disk: .ref(asyncSecondary.id),
        ),
        dependsOn: [
          ResourceDependency(asyncPrimary),
          ResourceDependency(asyncSecondary),
        ],
      ),
    );

    // ---- Regional template + region MIG PIC + policy attachments ----------
    //
    // A region-scoped instance template feeding a regional MIG with one
    // stateful per-instance config; an instance-schedule policy attached to
    // the bastion; and a daily snapshot schedule attached to the regional
    // backup disk.

    final regionalWorkerTemplate = add(
      GoogleComputeRegionInstanceTemplate(
        localName: 'regional_worker_template',
        namePrefix: .literal('reg-worker-'),
        region: .literal('asia-northeast1'),
        machineType: .literal('e2-micro'),
        disk: [
          ComputeRegionInstanceTemplateDisk(
            boot: .literal(true),
            sourceImage: .literal('debian-cloud/debian-12'),
            autoDelete: .literal(true),
          ),
        ],
        networkInterface: [
          ComputeRegionInstanceTemplateNetworkInterface(
            network: mainVpc.ref,
            subnetwork: workloadSubnet.ref,
          ),
        ],
        dependsOn: apiDeps,
      ),
    );

    final regionalPicMig = add(
      GoogleComputeRegionInstanceGroupManager(
        localName: 'regional_pic_demo',
        name: .literal('regional-pic-demo'),
        region: .literal('asia-northeast1'),
        baseInstanceName: .literal('regional-pic'),
        distributionPolicyZones: .literal(['asia-northeast1-a']),
        versions: [
          ComputeRegionInstanceGroupManagerVersion(
            name: .literal('default'),
            instanceTemplate: .ref(regionalWorkerTemplate.selfLink),
          ),
        ],
        lifecycle: const LifecycleOptions(ignoreChanges: ['target_size']),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeRegionPerInstanceConfig(
        localName: 'regional_pic_1',
        regionInstanceGroupManager: regionalPicMig.ref,
        name: .literal('regional-pic-1'),
        region: .literal('asia-northeast1'),
        preservedState: ComputeRegionPerInstanceConfigPreservedState(
          metadata: .literal({'role': 'regional-pic-demo'}),
        ),
        removeInstanceOnDestroy: .literal(true),
        dependsOn: [ResourceDependency(regionalPicMig)],
      ),
    );

    final bastionSchedulePolicy = add(
      GoogleComputeResourcePolicy(
        localName: 'bastion_schedule',
        name: .literal('ops-bastion-schedule'),
        region: .literal('asia-northeast1'),
        kind: .instanceSchedulePolicy(
          ComputeResourcePolicyInstanceSchedulePolicy(
            timeZone: .literal('Asia/Tokyo'),
            vmStartSchedule: ComputeResourcePolicyVmStartSchedule(
              schedule: .literal('0 9 * * 1-5'),
            ),
            vmStopSchedule: ComputeResourcePolicyVmStopSchedule(
              schedule: .literal('0 18 * * 1-5'),
            ),
          ),
        ),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeResourcePolicyAttachment(
        localName: 'bastion_schedule_attach',
        instance: bastion.ref,
        name: bastionSchedulePolicy.ref,
        zone: .literal('asia-northeast1-a'),
        deletionPolicy: .literal('ABANDON'),
        dependsOn: [
          ResourceDependency(bastion),
          ResourceDependency(bastionSchedulePolicy),
        ],
      ),
    );

    final backupSnapshotPolicy = add(
      GoogleComputeResourcePolicy(
        localName: 'backup_daily_snapshots',
        name: .literal('ops-backup-daily-snapshots'),
        region: .literal('asia-northeast1'),
        kind: .snapshotSchedulePolicy(
          ComputeResourcePolicySnapshotSchedulePolicy(
            schedule: .dailySchedule(
              ComputeResourcePolicyDailySchedule(
                daysInCycle: .literal(1),
                startTime: .literal('04:00'),
              ),
            ),
            retentionPolicy: ComputeResourcePolicyRetentionPolicy(
              maxRetentionDays: .literal(3),
              onSourceDiskDelete: .literal(.applyRetentionPolicy),
            ),
          ),
        ),
        dependsOn: apiDeps,
      ),
    );

    add(
      GoogleComputeRegionDiskResourcePolicyAttachment(
        localName: 'backup_disk_snapshots',
        disk: backupDisk.ref,
        name: backupSnapshotPolicy.ref,
        region: .literal('asia-northeast1'),
        deletionPolicy: .literal('DELETE'),
        dependsOn: [
          ResourceDependency(backupDisk),
          ResourceDependency(backupSnapshotPolicy),
        ],
      ),
    );

    // ---- Zonal VM extension policy (Ops Agent) ----------------------------

    add(
      GoogleComputeZoneVmExtensionPolicy(
        localName: 'ops_agent_zone_policy',
        name: .literal('ops-agent-zone-policy'),
        zone: .literal('asia-northeast1-a'),
        extensionPolicies: [
          ComputeZoneVmExtensionPolicyExtensionPolicies(
            extensionName: .literal('ops-agent'),
            pinnedVersion: .literal('2.66.0'),
          ),
        ],
        description: .literal('Zonal Ops Agent extension policy (demo)'),
        dependsOn: apiDeps,
      ),
    );
  }
}
