name: terradart_example_firebase_data_connect_quickstart
description: Firebase Data Connect quickstart -- serverless GraphQL backend service.
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  terradart_core:
    path: ../../packages/terradart_core
  terradart_google:
    path: ../../packages/terradart_google

dev_dependencies:
  lints: ^6.0.0
