// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
import 'catalog_entry.dart';

const List<CatalogEntry> terradartCatalog = <CatalogEntry>[
  CatalogEntry(
    tfType: 'google_active_directory_peering',
    className: 'GoogleActiveDirectoryPeering',
    barrel: 'active_directory',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_active_directory_peering`.',
    constructorParams: <String>[
      'localName',
      'authorizedNetwork',
      'deletionPolicy',
      'domainResource',
      'labels',
      'peeringId',
      'project',
      'status',
      'statusMessage',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_active_directory_peering`.',
  ),
  CatalogEntry(
    tfType: 'google_api_gateway_api',
    className: 'GoogleApiGatewayApi',
    barrel: 'api_gateway',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_api_gateway_api`.',
    constructorParams: <String>[
      'localName',
      'apiId',
      'deletionPolicy',
      'displayName',
      'labels',
      'managedService',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_api_gateway_api`.',
  ),
  CatalogEntry(
    tfType: 'google_api_gateway_api_config',
    className: 'GoogleApiGatewayApiConfig',
    barrel: 'api_gateway',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_api_gateway_api_config`.',
    constructorParams: <String>[
      'localName',
      'api',
      'apiConfigId',
      'apiConfigIdPrefix',
      'deletionPolicy',
      'displayName',
      'labels',
      'project',
      'gatewayConfig',
      'grpcServices',
      'managedServiceConfigs',
      'openapiDocuments',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_api_gateway_api_config`.',
  ),
  CatalogEntry(
    tfType: 'google_api_gateway_api_config_iam_binding',
    className: 'GoogleApiGatewayApiConfigIamBinding',
    barrel: 'api_gateway',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_api_gateway_api_config_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'api',
      'apiConfig',
      'members',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_api_gateway_api_config_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a API Gateway API Config.\n\nReplaces the entire member list for that role. Prefer\n[GoogleApiGatewayApiConfigIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_api_gateway_api_config_iam_member',
    className: 'GoogleApiGatewayApiConfigIamMember',
    barrel: 'api_gateway',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_api_gateway_api_config_iam_member`.',
    constructorParams: <String>[
      'localName',
      'api',
      'apiConfig',
      'member',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_api_gateway_api_config_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_api_gateway_api_config_iam_policy',
    className: 'GoogleApiGatewayApiConfigIamPolicy',
    barrel: 'api_gateway',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_api_gateway_api_config_iam_policy`.',
    constructorParams: <String>[
      'localName',
      'api',
      'apiConfig',
      'policyData',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_api_gateway_api_config_iam_policy`.\n\nAuthoritative IAM policy for a API Gateway API Config.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleApiGatewayApiConfigIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_api_gateway_api_iam_binding',
    className: 'GoogleApiGatewayApiIamBinding',
    barrel: 'api_gateway',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_api_gateway_api_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'api',
      'members',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_api_gateway_api_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a API Gateway API.\n\nReplaces the entire member list for that role. Prefer\n[GoogleApiGatewayApiIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_api_gateway_api_iam_member',
    className: 'GoogleApiGatewayApiIamMember',
    barrel: 'api_gateway',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_api_gateway_api_iam_member`.',
    constructorParams: <String>[
      'localName',
      'api',
      'member',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_api_gateway_api_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_api_gateway_api_iam_policy',
    className: 'GoogleApiGatewayApiIamPolicy',
    barrel: 'api_gateway',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_api_gateway_api_iam_policy`.',
    constructorParams: <String>['localName', 'api', 'policyData', 'project'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_api_gateway_api_iam_policy`.\n\nAuthoritative IAM policy for a API Gateway API.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleApiGatewayApiIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_api_gateway_gateway',
    className: 'GoogleApiGatewayGateway',
    barrel: 'api_gateway',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_api_gateway_gateway`.',
    constructorParams: <String>[
      'localName',
      'apiConfig',
      'deletionPolicy',
      'displayName',
      'gatewayId',
      'labels',
      'project',
      'region',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_api_gateway_gateway`.',
  ),
  CatalogEntry(
    tfType: 'google_api_gateway_gateway_iam_binding',
    className: 'GoogleApiGatewayGatewayIamBinding',
    barrel: 'api_gateway',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_api_gateway_gateway_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'gateway',
      'members',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_api_gateway_gateway_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a API Gateway Gateway.\n\nReplaces the entire member list for that role. Prefer\n[GoogleApiGatewayGatewayIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_api_gateway_gateway_iam_member',
    className: 'GoogleApiGatewayGatewayIamMember',
    barrel: 'api_gateway',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_api_gateway_gateway_iam_member`.',
    constructorParams: <String>[
      'localName',
      'gateway',
      'member',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_api_gateway_gateway_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_api_gateway_gateway_iam_policy',
    className: 'GoogleApiGatewayGatewayIamPolicy',
    barrel: 'api_gateway',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_api_gateway_gateway_iam_policy`.',
    constructorParams: <String>[
      'localName',
      'gateway',
      'policyData',
      'project',
      'region',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_api_gateway_gateway_iam_policy`.\n\nAuthoritative IAM policy for a API Gateway Gateway.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleApiGatewayGatewayIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_artifact_registry_vpcsc_config',
    className: 'GoogleArtifactRegistryVpcscConfig',
    barrel: 'artifact_registry',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_artifact_registry_vpcsc_config`.',
    constructorParams: <String>[
      'localName',
      'location',
      'project',
      'vpcscPolicy',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_artifact_registry_vpcsc_config`.',
  ),
  CatalogEntry(
    tfType: 'google_biglake_hive_catalog',
    className: 'GoogleBiglakeHiveCatalog',
    barrel: 'biglake',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_biglake_hive_catalog`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'description',
      'locationUri',
      'name',
      'primaryLocation',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_biglake_hive_catalog`.',
  ),
  CatalogEntry(
    tfType: 'google_biglake_hive_catalog_iam_binding',
    className: 'GoogleBiglakeHiveCatalogIamBinding',
    barrel: 'biglake',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_biglake_hive_catalog_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'members',
      'name',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_biglake_hive_catalog_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Biglake Hive Catalog.\n\nReplaces the entire member list for that role. Prefer\n[GoogleBiglakeHiveCatalogIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_biglake_hive_catalog_iam_member',
    className: 'GoogleBiglakeHiveCatalogIamMember',
    barrel: 'biglake',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_biglake_hive_catalog_iam_member`.',
    constructorParams: <String>[
      'localName',
      'member',
      'name',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_biglake_hive_catalog_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_biglake_hive_catalog_iam_policy',
    className: 'GoogleBiglakeHiveCatalogIamPolicy',
    barrel: 'biglake',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_biglake_hive_catalog_iam_policy`.',
    constructorParams: <String>['localName', 'name', 'policyData', 'project'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_biglake_hive_catalog_iam_policy`.\n\nAuthoritative IAM policy for a Biglake Hive Catalog.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleBiglakeHiveCatalogIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_biglake_hive_database',
    className: 'GoogleBiglakeHiveDatabase',
    barrel: 'biglake',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_biglake_hive_database`.',
    constructorParams: <String>[
      'localName',
      'catalog',
      'deletionPolicy',
      'description',
      'locationUri',
      'name',
      'parameters',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_biglake_hive_database`.',
  ),
  CatalogEntry(
    tfType: 'google_biglake_hive_database_iam_binding',
    className: 'GoogleBiglakeHiveDatabaseIamBinding',
    barrel: 'biglake',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_biglake_hive_database_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'catalog',
      'members',
      'name',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_biglake_hive_database_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Biglake Hive Database.\n\nReplaces the entire member list for that role. Prefer\n[GoogleBiglakeHiveDatabaseIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_biglake_hive_database_iam_member',
    className: 'GoogleBiglakeHiveDatabaseIamMember',
    barrel: 'biglake',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_biglake_hive_database_iam_member`.',
    constructorParams: <String>[
      'localName',
      'catalog',
      'member',
      'name',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_biglake_hive_database_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_biglake_hive_database_iam_policy',
    className: 'GoogleBiglakeHiveDatabaseIamPolicy',
    barrel: 'biglake',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_biglake_hive_database_iam_policy`.',
    constructorParams: <String>[
      'localName',
      'catalog',
      'name',
      'policyData',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_biglake_hive_database_iam_policy`.\n\nAuthoritative IAM policy for a Biglake Hive Database.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleBiglakeHiveDatabaseIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_biglake_hive_table',
    className: 'GoogleBiglakeHiveTable',
    barrel: 'biglake',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_biglake_hive_table`.',
    constructorParams: <String>[
      'localName',
      'catalog',
      'database',
      'deletionPolicy',
      'description',
      'name',
      'parameters',
      'project',
      'viewExpandedText',
      'viewOriginalText',
      'partitionKeys',
      'storageDescriptor',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_biglake_hive_table`.',
  ),
  CatalogEntry(
    tfType: 'google_biglake_hive_table_iam_binding',
    className: 'GoogleBiglakeHiveTableIamBinding',
    barrel: 'biglake',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_biglake_hive_table_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'catalog',
      'database',
      'members',
      'name',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_biglake_hive_table_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Biglake Hive Table.\n\nReplaces the entire member list for that role. Prefer\n[GoogleBiglakeHiveTableIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_biglake_hive_table_iam_member',
    className: 'GoogleBiglakeHiveTableIamMember',
    barrel: 'biglake',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_biglake_hive_table_iam_member`.',
    constructorParams: <String>[
      'localName',
      'catalog',
      'database',
      'member',
      'name',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_biglake_hive_table_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_biglake_hive_table_iam_policy',
    className: 'GoogleBiglakeHiveTableIamPolicy',
    barrel: 'biglake',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_biglake_hive_table_iam_policy`.',
    constructorParams: <String>[
      'localName',
      'catalog',
      'database',
      'name',
      'policyData',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_biglake_hive_table_iam_policy`.\n\nAuthoritative IAM policy for a Biglake Hive Table.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleBiglakeHiveTableIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_bigquery_analytics_hub_data_exchange_subscription',
    className: 'GoogleBigqueryAnalyticsHubDataExchangeSubscription',
    barrel: 'bigquery',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_bigquery_analytics_hub_data_exchange_subscription`.',
    constructorParams: <String>[
      'localName',
      'dataExchangeId',
      'dataExchangeLocation',
      'dataExchangeProject',
      'deletionPolicy',
      'location',
      'project',
      'refreshPolicy',
      'subscriberContact',
      'subscriptionId',
      'destinationDataset',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_bigquery_analytics_hub_data_exchange_subscription`.',
  ),
  CatalogEntry(
    tfType: 'google_ces_evaluation',
    className: 'GoogleCesEvaluation',
    barrel: 'ces',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_ces_evaluation`.',
    constructorParams: <String>[
      'localName',
      'app',
      'deletionPolicy',
      'description',
      'displayName',
      'evaluationId',
      'location',
      'project',
      'tags',
      'golden',
      'scenario',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_ces_evaluation`.',
  ),
  CatalogEntry(
    tfType: 'google_ces_security_settings',
    className: 'GoogleCesSecuritySettings',
    barrel: 'ces',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_ces_security_settings`.',
    constructorParams: <String>[
      'localName',
      'location',
      'project',
      'endpointControlPolicy',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_ces_security_settings`.',
  ),
  CatalogEntry(
    tfType: 'google_chronicle_soar_domain',
    className: 'GoogleChronicleSoarDomain',
    barrel: 'chronicle',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_chronicle_soar_domain`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'displayName',
      'environmentsJson',
      'instance',
      'location',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_chronicle_soar_domain`.',
  ),
  CatalogEntry(
    tfType: 'google_cloud_identity_policy',
    className: 'GoogleCloudIdentityPolicy',
    barrel: 'identity',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_cloud_identity_policy`.',
    constructorParams: <String>[
      'localName',
      'customer',
      'deletionPolicy',
      'policyQuery',
      'setting',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_cloud_identity_policy`.',
  ),
  CatalogEntry(
    tfType: 'google_compute_backend_bucket_iam_binding',
    className: 'GoogleComputeBackendBucketIamBinding',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_compute_backend_bucket_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'members',
      'name',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_backend_bucket_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Compute Backend Bucket.\n\nReplaces the entire member list for that role. Prefer\n[GoogleComputeBackendBucketIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_compute_backend_bucket_iam_member',
    className: 'GoogleComputeBackendBucketIamMember',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_compute_backend_bucket_iam_member`.',
    constructorParams: <String>[
      'localName',
      'member',
      'name',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_backend_bucket_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_compute_backend_bucket_iam_policy',
    className: 'GoogleComputeBackendBucketIamPolicy',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_compute_backend_bucket_iam_policy`.',
    constructorParams: <String>['localName', 'name', 'policyData', 'project'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_backend_bucket_iam_policy`.\n\nAuthoritative IAM policy for a Compute Backend Bucket.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleComputeBackendBucketIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_compute_backend_service_iam_binding',
    className: 'GoogleComputeBackendServiceIamBinding',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_compute_backend_service_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'members',
      'name',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_backend_service_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Compute Backend Service.\n\nReplaces the entire member list for that role. Prefer\n[GoogleComputeBackendServiceIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_compute_backend_service_iam_member',
    className: 'GoogleComputeBackendServiceIamMember',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_compute_backend_service_iam_member`.',
    constructorParams: <String>[
      'localName',
      'member',
      'name',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_backend_service_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_compute_backend_service_iam_policy',
    className: 'GoogleComputeBackendServiceIamPolicy',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_compute_backend_service_iam_policy`.',
    constructorParams: <String>['localName', 'name', 'policyData', 'project'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_backend_service_iam_policy`.\n\nAuthoritative IAM policy for a Compute Backend Service.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleComputeBackendServiceIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_compute_future_reservation',
    className: 'GoogleComputeFutureReservation',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_compute_future_reservation`.',
    constructorParams: <String>[
      'localName',
      'autoCreatedReservationsDeleteTime',
      'autoDeleteAutoCreatedReservations',
      'deletionPolicy',
      'deploymentType',
      'description',
      'name',
      'namePrefix',
      'planningStatus',
      'project',
      'reservationMode',
      'reservationName',
      'schedulingType',
      'specificReservationRequired',
      'zone',
      'aggregateReservation',
      'autoCreatedReservationsDuration',
      'commitmentInfo',
      'params',
      'shareSettings',
      'specificSkuProperties',
      'timeWindow',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_compute_future_reservation`.',
  ),
  CatalogEntry(
    tfType: 'google_compute_instance_from_machine_image',
    className: 'GoogleComputeInstanceFromMachineImage',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_compute_instance_from_machine_image`.',
    constructorParams: <String>[
      'localName',
      'allowStoppingForUpdate',
      'canIpForward',
      'deletionPolicy',
      'deletionProtection',
      'description',
      'desiredStatus',
      'enableDisplay',
      'eraseWindowsVssSignature',
      'hostname',
      'keyRevocationActionType',
      'labels',
      'machineType',
      'metadata',
      'metadataStartupScript',
      'minCpuPlatform',
      'name',
      'partnerMetadata',
      'project',
      'resourcePolicies',
      'sourceMachineImage',
      'tags',
      'zone',
      'advancedMachineFeatures',
      'confidentialInstanceConfig',
      'guestAccelerator',
      'instanceEncryptionKey',
      'networkInterface',
      'networkPerformanceConfig',
      'params',
      'reservationAffinity',
      'scheduling',
      'serviceAccount',
      'shieldedInstanceConfig',
      'sourceMachineImageEncryptionKey',
      'workloadIdentityConfig',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[
      'source_machine_image_encryption_key.raw_key',
      'source_machine_image_encryption_key.rsa_encrypted_key',
    ],
    docComment:
        'Factory wrapper for `google_compute_instance_from_machine_image`.',
  ),
  CatalogEntry(
    tfType: 'google_compute_machine_image',
    className: 'GoogleComputeMachineImage',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_compute_machine_image`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'description',
      'guestFlush',
      'name',
      'project',
      'sourceInstance',
      'machineImageEncryptionKey',
      'params',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['machine_image_encryption_key.raw_key'],
    docComment: 'Factory wrapper for `google_compute_machine_image`.',
  ),
  CatalogEntry(
    tfType: 'google_compute_machine_image_iam_binding',
    className: 'GoogleComputeMachineImageIamBinding',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_compute_machine_image_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'machineImage',
      'members',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_machine_image_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Compute Machine Image.\n\nReplaces the entire member list for that role. Prefer\n[GoogleComputeMachineImageIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_compute_machine_image_iam_member',
    className: 'GoogleComputeMachineImageIamMember',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_compute_machine_image_iam_member`.',
    constructorParams: <String>[
      'localName',
      'machineImage',
      'member',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_machine_image_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_compute_machine_image_iam_policy',
    className: 'GoogleComputeMachineImageIamPolicy',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_compute_machine_image_iam_policy`.',
    constructorParams: <String>[
      'localName',
      'machineImage',
      'policyData',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_machine_image_iam_policy`.\n\nAuthoritative IAM policy for a Compute Machine Image.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleComputeMachineImageIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_compute_network_edge_security_service',
    className: 'GoogleComputeNetworkEdgeSecurityService',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_compute_network_edge_security_service`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'description',
      'name',
      'project',
      'region',
      'securityPolicy',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_network_edge_security_service`.',
  ),
  CatalogEntry(
    tfType: 'google_compute_network_firewall_policy_packet_mirroring_rule',
    className: 'GoogleComputeNetworkFirewallPolicyPacketMirroringRule',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_compute_network_firewall_policy_packet_mirroring_rule`.',
    constructorParams: <String>[
      'localName',
      'action',
      'deletionPolicy',
      'description',
      'direction',
      'disabled',
      'firewallPolicy',
      'priority',
      'project',
      'ruleName',
      'securityProfileGroup',
      'tlsInspect',
      'match',
      'targetSecureTags',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_network_firewall_policy_packet_mirroring_rule`.',
  ),
  CatalogEntry(
    tfType: 'google_compute_region_backend_bucket',
    className: 'GoogleComputeRegionBackendBucket',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_compute_region_backend_bucket`.',
    constructorParams: <String>[
      'localName',
      'bucketName',
      'deletionPolicy',
      'description',
      'loadBalancingScheme',
      'name',
      'project',
      'region',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_compute_region_backend_bucket`.',
  ),
  CatalogEntry(
    tfType: 'google_compute_region_backend_bucket_iam_binding',
    className: 'GoogleComputeRegionBackendBucketIamBinding',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_compute_region_backend_bucket_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'members',
      'name',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_region_backend_bucket_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Compute Region Backend Bucket.\n\nReplaces the entire member list for that role. Prefer\n[GoogleComputeRegionBackendBucketIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_compute_region_backend_bucket_iam_member',
    className: 'GoogleComputeRegionBackendBucketIamMember',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_compute_region_backend_bucket_iam_member`.',
    constructorParams: <String>[
      'localName',
      'member',
      'name',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_region_backend_bucket_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_compute_region_backend_bucket_iam_policy',
    className: 'GoogleComputeRegionBackendBucketIamPolicy',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_compute_region_backend_bucket_iam_policy`.',
    constructorParams: <String>[
      'localName',
      'name',
      'policyData',
      'project',
      'region',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_region_backend_bucket_iam_policy`.\n\nAuthoritative IAM policy for a Compute Region Backend Bucket.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleComputeRegionBackendBucketIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_compute_region_backend_service_iam_binding',
    className: 'GoogleComputeRegionBackendServiceIamBinding',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_compute_region_backend_service_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'members',
      'name',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_region_backend_service_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Compute Region Backend Service.\n\nReplaces the entire member list for that role. Prefer\n[GoogleComputeRegionBackendServiceIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_compute_region_backend_service_iam_member',
    className: 'GoogleComputeRegionBackendServiceIamMember',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_compute_region_backend_service_iam_member`.',
    constructorParams: <String>[
      'localName',
      'member',
      'name',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_region_backend_service_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_compute_region_backend_service_iam_policy',
    className: 'GoogleComputeRegionBackendServiceIamPolicy',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_compute_region_backend_service_iam_policy`.',
    constructorParams: <String>[
      'localName',
      'name',
      'policyData',
      'project',
      'region',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_region_backend_service_iam_policy`.\n\nAuthoritative IAM policy for a Compute Region Backend Service.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleComputeRegionBackendServiceIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_compute_region_network_policy',
    className: 'GoogleComputeRegionNetworkPolicy',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_compute_region_network_policy`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'description',
      'name',
      'project',
      'region',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_compute_region_network_policy`.',
  ),
  CatalogEntry(
    tfType: 'google_compute_region_network_policy_traffic_classification_rule',
    className: 'GoogleComputeRegionNetworkPolicyTrafficClassificationRule',
    barrel: 'compute',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_compute_region_network_policy_traffic_classification_rule`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'description',
      'disabled',
      'networkPolicy',
      'priority',
      'project',
      'region',
      'ruleName',
      'targetServiceAccounts',
      'action',
      'match',
      'targetSecureTags',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_compute_region_network_policy_traffic_classification_rule`.',
  ),
  CatalogEntry(
    tfType: 'google_dataflow_flex_template_job',
    className: 'GoogleDataflowFlexTemplateJob',
    barrel: 'dataflow',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_dataflow_flex_template_job`.',
    constructorParams: <String>[
      'localName',
      'additionalExperiments',
      'additionalPipelineOptions',
      'autoscalingAlgorithm',
      'containerSpecGcsPath',
      'createIgnoreAlreadyExists',
      'deletionPolicy',
      'enableStreamingEngine',
      'ipConfiguration',
      'kmsKeyName',
      'labels',
      'launcherMachineType',
      'machineType',
      'maxWorkers',
      'name',
      'network',
      'numWorkers',
      'onDelete',
      'parameters',
      'project',
      'region',
      'sdkContainerImage',
      'serviceAccountEmail',
      'skipWaitOnJobTermination',
      'stagingLocation',
      'subnetwork',
      'tempLocation',
      'transformNameMapping',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_dataflow_flex_template_job`.',
  ),
  CatalogEntry(
    tfType: 'google_dataform_config',
    className: 'GoogleDataformConfig',
    barrel: 'dataform',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_dataform_config`.',
    constructorParams: <String>[
      'localName',
      'defaultKmsKeyName',
      'project',
      'region',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_dataform_config`.',
  ),
  CatalogEntry(
    tfType: 'google_dataform_repository_release_config',
    className: 'GoogleDataformRepositoryReleaseConfig',
    barrel: 'dataform',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_dataform_repository_release_config`.',
    constructorParams: <String>[
      'localName',
      'cronSchedule',
      'deletionPolicy',
      'disabled',
      'gitCommitish',
      'name',
      'project',
      'region',
      'repository',
      'timeZone',
      'codeCompilationConfig',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_dataform_repository_release_config`.',
  ),
  CatalogEntry(
    tfType: 'google_dataform_repository_workflow_config',
    className: 'GoogleDataformRepositoryWorkflowConfig',
    barrel: 'dataform',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_dataform_repository_workflow_config`.',
    constructorParams: <String>[
      'localName',
      'cronSchedule',
      'deletionPolicy',
      'disabled',
      'name',
      'project',
      'region',
      'releaseConfig',
      'repository',
      'timeZone',
      'invocationConfig',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_dataform_repository_workflow_config`.',
  ),
  CatalogEntry(
    tfType: 'google_dataplex_data_asset',
    className: 'GoogleDataplexDataAsset',
    barrel: 'dataplex',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_dataplex_data_asset`.',
    constructorParams: <String>[
      'localName',
      'dataAssetId',
      'dataProductId',
      'deletionPolicy',
      'labels',
      'location',
      'project',
      'resource',
      'accessGroupConfigs',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_dataplex_data_asset`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_ai_logic_config',
    className: 'GoogleFirebaseAiLogicConfig',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_ai_logic_config`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'location',
      'project',
      'generativeLanguageConfig',
      'telemetryConfig',
      'trafficFilter',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['generative_language_config.api_key'],
    docComment: 'Factory wrapper for `google_firebase_ai_logic_config`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_ai_logic_prompt_template',
    className: 'GoogleFirebaseAiLogicPromptTemplate',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_ai_logic_prompt_template`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'displayName',
      'location',
      'project',
      'regionalPropagationDisabled',
      'templateId',
      'templateString',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_firebase_ai_logic_prompt_template`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_ai_logic_prompt_template_lock',
    className: 'GoogleFirebaseAiLogicPromptTemplateLock',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_firebase_ai_logic_prompt_template_lock`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'location',
      'project',
      'regionalPropagationDisabled',
      'templateId',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_firebase_ai_logic_prompt_template_lock`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_android_app',
    className: 'GoogleFirebaseAndroidApp',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_android_app`.',
    constructorParams: <String>[
      'localName',
      'apiKeyId',
      'deletionPolicy',
      'displayName',
      'packageName',
      'project',
      'sha1Hashes',
      'sha256Hashes',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_firebase_android_app`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_apple_app',
    className: 'GoogleFirebaseAppleApp',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_apple_app`.',
    constructorParams: <String>[
      'localName',
      'apiKeyId',
      'appStoreId',
      'bundleId',
      'deletionPolicy',
      'displayName',
      'project',
      'teamId',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_firebase_apple_app`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_database_instance',
    className: 'GoogleFirebaseDatabaseInstance',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_database_instance`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'desiredState',
      'instanceId',
      'project',
      'region',
      'type',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_firebase_database_instance`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_extensions_instance',
    className: 'GoogleFirebaseExtensionsInstance',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_extensions_instance`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'instanceId',
      'project',
      'config',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_firebase_extensions_instance`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_hosting_channel',
    className: 'GoogleFirebaseHostingChannel',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_hosting_channel`.',
    constructorParams: <String>[
      'localName',
      'channelId',
      'deletionPolicy',
      'expireTime',
      'labels',
      'retainedReleaseCount',
      'siteId',
      'ttl',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_firebase_hosting_channel`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_hosting_custom_domain',
    className: 'GoogleFirebaseHostingCustomDomain',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_hosting_custom_domain`.',
    constructorParams: <String>[
      'localName',
      'certPreference',
      'customDomain',
      'deletionPolicy',
      'project',
      'redirectTarget',
      'siteId',
      'waitDnsVerification',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_firebase_hosting_custom_domain`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_hosting_release',
    className: 'GoogleFirebaseHostingRelease',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_hosting_release`.',
    constructorParams: <String>[
      'localName',
      'channelId',
      'message',
      'siteId',
      'type',
      'versionName',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_firebase_hosting_release`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_hosting_site',
    className: 'GoogleFirebaseHostingSite',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_hosting_site`.',
    constructorParams: <String>[
      'localName',
      'appId',
      'deletionPolicy',
      'project',
      'siteId',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_firebase_hosting_site`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_hosting_version',
    className: 'GoogleFirebaseHostingVersion',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_hosting_version`.',
    constructorParams: <String>['localName', 'siteId', 'config'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_firebase_hosting_version`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_project',
    className: 'GoogleFirebaseProject',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_project`.',
    constructorParams: <String>['localName', 'project'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_firebase_project`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_storage_bucket',
    className: 'GoogleFirebaseStorageBucket',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_storage_bucket`.',
    constructorParams: <String>[
      'localName',
      'bucketId',
      'deletionPolicy',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_firebase_storage_bucket`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_storage_default_bucket',
    className: 'GoogleFirebaseStorageDefaultBucket',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_storage_default_bucket`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'location',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_firebase_storage_default_bucket`.',
  ),
  CatalogEntry(
    tfType: 'google_firebase_web_app',
    className: 'GoogleFirebaseWebApp',
    barrel: 'firebase',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_firebase_web_app`.',
    constructorParams: <String>[
      'localName',
      'apiKeyId',
      'deletionPolicy',
      'displayName',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_firebase_web_app`.',
  ),
  CatalogEntry(
    tfType: 'google_folder_service_identity',
    className: 'GoogleFolderServiceIdentity',
    barrel: 'folder',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_folder_service_identity`.',
    constructorParams: <String>['localName', 'folder', 'service'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_folder_service_identity`.',
  ),
  CatalogEntry(
    tfType: 'google_gke_hub_membership_rbac_role_binding',
    className: 'GoogleGkeHubMembershipRbacRoleBinding',
    barrel: 'container',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_gke_hub_membership_rbac_role_binding`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'location',
      'membershipId',
      'membershipRbacRoleBindingId',
      'project',
      'user',
      'role',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_gke_hub_membership_rbac_role_binding`.',
  ),
  CatalogEntry(
    tfType: 'google_kms_folder_kaj_policy_config',
    className: 'GoogleKmsFolderKajPolicyConfig',
    barrel: 'kms',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_kms_folder_kaj_policy_config`.',
    constructorParams: <String>[
      'localName',
      'folder',
      'defaultKeyAccessJustificationPolicy',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_kms_folder_kaj_policy_config`.',
  ),
  CatalogEntry(
    tfType: 'google_kms_organization_kaj_policy_config',
    className: 'GoogleKmsOrganizationKajPolicyConfig',
    barrel: 'kms',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_kms_organization_kaj_policy_config`.',
    constructorParams: <String>[
      'localName',
      'organization',
      'defaultKeyAccessJustificationPolicy',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_kms_organization_kaj_policy_config`.',
  ),
  CatalogEntry(
    tfType: 'google_kms_project_kaj_policy_config',
    className: 'GoogleKmsProjectKajPolicyConfig',
    barrel: 'kms',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_kms_project_kaj_policy_config`.',
    constructorParams: <String>[
      'localName',
      'project',
      'defaultKeyAccessJustificationPolicy',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_kms_project_kaj_policy_config`.',
  ),
  CatalogEntry(
    tfType: 'google_network_security_authorization_policy',
    className: 'GoogleNetworkSecurityAuthorizationPolicy',
    barrel: 'network',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_network_security_authorization_policy`.',
    constructorParams: <String>[
      'localName',
      'action',
      'deletionPolicy',
      'description',
      'labels',
      'location',
      'name',
      'project',
      'rules',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_network_security_authorization_policy`.',
  ),
  CatalogEntry(
    tfType: 'google_network_security_sac_attachment',
    className: 'GoogleNetworkSecuritySacAttachment',
    barrel: 'network',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_network_security_sac_attachment`.',
    constructorParams: <String>[
      'localName',
      'country',
      'deletionPolicy',
      'labels',
      'location',
      'name',
      'nccGateway',
      'project',
      'sacRealm',
      'timeZone',
      'symantecOptions',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_network_security_sac_attachment`.',
  ),
  CatalogEntry(
    tfType: 'google_network_security_sac_realm',
    className: 'GoogleNetworkSecuritySacRealm',
    barrel: 'network',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_network_security_sac_realm`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'labels',
      'name',
      'project',
      'securityService',
      'symantecOptions',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_network_security_sac_realm`.',
  ),
  CatalogEntry(
    tfType: 'google_network_services_service_lb_policies',
    className: 'GoogleNetworkServicesServiceLbPolicies',
    barrel: 'network',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_network_services_service_lb_policies`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'description',
      'labels',
      'loadBalancingAlgorithm',
      'location',
      'name',
      'project',
      'autoCapacityDrain',
      'failoverConfig',
      'isolationConfig',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_network_services_service_lb_policies`.',
  ),
  CatalogEntry(
    tfType: 'google_observability_folder_settings',
    className: 'GoogleObservabilityFolderSettings',
    barrel: 'observability',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_observability_folder_settings`.',
    constructorParams: <String>[
      'localName',
      'defaultStorageLocation',
      'folder',
      'kmsKeyName',
      'location',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_observability_folder_settings`.',
  ),
  CatalogEntry(
    tfType: 'google_observability_organization_settings',
    className: 'GoogleObservabilityOrganizationSettings',
    barrel: 'observability',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_observability_organization_settings`.',
    constructorParams: <String>[
      'localName',
      'defaultStorageLocation',
      'kmsKeyName',
      'location',
      'organization',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_observability_organization_settings`.',
  ),
  CatalogEntry(
    tfType: 'google_observability_project_settings',
    className: 'GoogleObservabilityProjectSettings',
    barrel: 'observability',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_observability_project_settings`.',
    constructorParams: <String>[
      'localName',
      'defaultStorageLocation',
      'kmsKeyName',
      'location',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_observability_project_settings`.',
  ),
  CatalogEntry(
    tfType: 'google_organization_service_identity',
    className: 'GoogleOrganizationServiceIdentity',
    barrel: 'organization',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_organization_service_identity`.',
    constructorParams: <String>['localName', 'organization', 'service'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_organization_service_identity`.',
  ),
  CatalogEntry(
    tfType: 'google_os_config_guest_policies',
    className: 'GoogleOsConfigGuestPolicies',
    barrel: 'os_config',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_os_config_guest_policies`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'description',
      'etag',
      'guestPolicyId',
      'project',
      'assignment',
      'packageRepositories',
      'packages',
      'recipes',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_os_config_guest_policies`.',
  ),
  CatalogEntry(
    tfType: 'google_privileged_access_manager_settings',
    className: 'GooglePrivilegedAccessManagerSettings',
    barrel: 'privileged_access_manager',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_privileged_access_manager_settings`.',
    constructorParams: <String>[
      'localName',
      'location',
      'parent',
      'emailNotificationSettings',
      'serviceAccountApproverSettings',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_privileged_access_manager_settings`.',
  ),
  CatalogEntry(
    tfType: 'google_project_service_identity',
    className: 'GoogleProjectServiceIdentity',
    barrel: 'project',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_project_service_identity`.',
    constructorParams: <String>['localName', 'service', 'project'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_project_service_identity`.\n\nProject **service identity** (beta-only) — provisions the per-service\nservice agent (e.g. the Pub/Sub or Cloud Build agent) ahead of first\nuse, so IAM grants on that agent never race its lazy creation.\n\nFree: the identity is account metadata with no billed resource behind\nit. Terraform destroy removes only the Terraform record — the service\nagent itself persists (upstream behavior).\n\nThe [member] / [email] outputs feed IAM grants directly:\n`GoogleProjectIamMember(member: identity.member, ...)`.',
  ),
  CatalogEntry(
    tfType: 'google_runtimeconfig_config',
    className: 'GoogleRuntimeconfigConfig',
    barrel: 'runtimeconfig',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_runtimeconfig_config`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'description',
      'name',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_runtimeconfig_config`.',
  ),
  CatalogEntry(
    tfType: 'google_runtimeconfig_config_iam_binding',
    className: 'GoogleRuntimeconfigConfigIamBinding',
    barrel: 'runtimeconfig',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_runtimeconfig_config_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'config',
      'members',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_runtimeconfig_config_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Runtimeconfig Config.\n\nReplaces the entire member list for that role. Prefer\n[GoogleRuntimeconfigConfigIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_runtimeconfig_config_iam_member',
    className: 'GoogleRuntimeconfigConfigIamMember',
    barrel: 'runtimeconfig',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_runtimeconfig_config_iam_member`.',
    constructorParams: <String>[
      'localName',
      'config',
      'member',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_runtimeconfig_config_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_runtimeconfig_config_iam_policy',
    className: 'GoogleRuntimeconfigConfigIamPolicy',
    barrel: 'runtimeconfig',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_runtimeconfig_config_iam_policy`.',
    constructorParams: <String>['localName', 'config', 'policyData', 'project'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_runtimeconfig_config_iam_policy`.\n\nAuthoritative IAM policy for a Runtimeconfig Config.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleRuntimeconfigConfigIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_runtimeconfig_variable',
    className: 'GoogleRuntimeconfigVariable',
    barrel: 'runtimeconfig',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_runtimeconfig_variable`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'name',
      'parent',
      'project',
      'text',
      'value',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['text', 'value'],
    docComment: 'Factory wrapper for `google_runtimeconfig_variable`.',
  ),
  CatalogEntry(
    tfType: 'google_saas_runtime_release',
    className: 'GoogleSaasRuntimeRelease',
    barrel: 'saas_runtime',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_saas_runtime_release`.',
    constructorParams: <String>[
      'localName',
      'annotations',
      'deletionPolicy',
      'labels',
      'location',
      'project',
      'releaseId',
      'unitKind',
      'blueprint',
      'inputVariableDefaults',
      'releaseRequirements',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_saas_runtime_release`.',
  ),
  CatalogEntry(
    tfType: 'google_saas_runtime_rollout_kind',
    className: 'GoogleSaasRuntimeRolloutKind',
    barrel: 'saas_runtime',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_saas_runtime_rollout_kind`.',
    constructorParams: <String>[
      'localName',
      'annotations',
      'deletionPolicy',
      'labels',
      'location',
      'project',
      'rolloutKindId',
      'rolloutOrchestrationStrategy',
      'unitFilter',
      'unitKind',
      'updateUnitKindStrategy',
      'errorBudget',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_saas_runtime_rollout_kind`.',
  ),
  CatalogEntry(
    tfType: 'google_saas_runtime_saas',
    className: 'GoogleSaasRuntimeSaas',
    barrel: 'saas_runtime',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_saas_runtime_saas`.',
    constructorParams: <String>[
      'localName',
      'annotations',
      'deletionPolicy',
      'labels',
      'location',
      'project',
      'saasId',
      'locations',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_saas_runtime_saas`.',
  ),
  CatalogEntry(
    tfType: 'google_saas_runtime_tenant',
    className: 'GoogleSaasRuntimeTenant',
    barrel: 'saas_runtime',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_saas_runtime_tenant`.',
    constructorParams: <String>[
      'localName',
      'annotations',
      'consumerResource',
      'deletionPolicy',
      'labels',
      'location',
      'project',
      'saas',
      'tenantId',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_saas_runtime_tenant`.',
  ),
  CatalogEntry(
    tfType: 'google_saas_runtime_unit',
    className: 'GoogleSaasRuntimeUnit',
    barrel: 'saas_runtime',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_saas_runtime_unit`.',
    constructorParams: <String>[
      'localName',
      'annotations',
      'deletionPolicy',
      'labels',
      'location',
      'managementMode',
      'project',
      'tenant',
      'unitId',
      'unitKind',
      'maintenance',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_saas_runtime_unit`.',
  ),
  CatalogEntry(
    tfType: 'google_saas_runtime_unit_kind',
    className: 'GoogleSaasRuntimeUnitKind',
    barrel: 'saas_runtime',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_saas_runtime_unit_kind`.',
    constructorParams: <String>[
      'localName',
      'annotations',
      'defaultRelease',
      'deletionPolicy',
      'labels',
      'location',
      'project',
      'saas',
      'unitKindId',
      'dependencies',
      'inputVariableMappings',
      'outputVariableMappings',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_saas_runtime_unit_kind`.',
  ),
  CatalogEntry(
    tfType: 'google_saas_runtime_unit_operation',
    className: 'GoogleSaasRuntimeUnitOperation',
    barrel: 'saas_runtime',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_saas_runtime_unit_operation`.',
    constructorParams: <String>[
      'localName',
      'annotations',
      'deletionPolicy',
      'labels',
      'location',
      'project',
      'unit',
      'unitOperationId',
      'waitForCompletion',
      'deprovision',
      'provision',
      'upgrade',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_saas_runtime_unit_operation`.',
  ),
  CatalogEntry(
    tfType: 'google_security_scanner_scan_config',
    className: 'GoogleSecurityScannerScanConfig',
    barrel: 'security_scanner',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_security_scanner_scan_config`.',
    constructorParams: <String>[
      'localName',
      'blacklistPatterns',
      'deletionPolicy',
      'displayName',
      'exportToSecurityCommandCenter',
      'ignoreHttpStatusErrors',
      'maxQps',
      'project',
      'startingUrls',
      'targetPlatforms',
      'userAgent',
      'authentication',
      'schedule',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[
      'authentication.custom_account.password',
      'authentication.google_account.password',
    ],
    docComment: 'Factory wrapper for `google_security_scanner_scan_config`.',
  ),
  CatalogEntry(
    tfType: 'google_service_usage_consumer_quota_override',
    className: 'GoogleServiceUsageConsumerQuotaOverride',
    barrel: 'service_usage',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_service_usage_consumer_quota_override`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'dimensions',
      'force',
      'limit',
      'metric',
      'overrideValue',
      'project',
      'service',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_service_usage_consumer_quota_override`.',
  ),
  CatalogEntry(
    tfType: 'google_tags_tag_binding_collection',
    className: 'GoogleTagsTagBindingCollection',
    barrel: 'tags',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_tags_tag_binding_collection`.',
    constructorParams: <String>[
      'localName',
      'fullResourceName',
      'location',
      'tags',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_tags_tag_binding_collection`.',
  ),
  CatalogEntry(
    tfType: 'google_tpu_v2_queued_resource',
    className: 'GoogleTpuV2QueuedResource',
    barrel: 'tpu',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_tpu_v2_queued_resource`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'name',
      'project',
      'zone',
      'tpu',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_tpu_v2_queued_resource`.',
  ),
  CatalogEntry(
    tfType: 'google_tpu_v2_vm',
    className: 'GoogleTpuV2Vm',
    barrel: 'tpu',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_tpu_v2_vm`.',
    constructorParams: <String>[
      'localName',
      'acceleratorType',
      'cidrBlock',
      'deletionPolicy',
      'description',
      'labels',
      'metadata',
      'name',
      'project',
      'runtimeVersion',
      'tags',
      'zone',
      'acceleratorConfig',
      'dataDisks',
      'networkConfig',
      'networkConfigs',
      'schedulingConfig',
      'serviceAccount',
      'shieldedInstanceConfig',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_tpu_v2_vm`.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_endpoint_iam_binding',
    className: 'GoogleVertexAiEndpointIamBinding',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_vertex_ai_endpoint_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'endpoint',
      'location',
      'members',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_endpoint_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Vertex Ai Endpoint.\n\nReplaces the entire member list for that role. Prefer\n[GoogleVertexAiEndpointIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_endpoint_iam_member',
    className: 'GoogleVertexAiEndpointIamMember',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_vertex_ai_endpoint_iam_member`.',
    constructorParams: <String>[
      'localName',
      'endpoint',
      'location',
      'member',
      'project',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_vertex_ai_endpoint_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_endpoint_iam_policy',
    className: 'GoogleVertexAiEndpointIamPolicy',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_vertex_ai_endpoint_iam_policy`.',
    constructorParams: <String>[
      'localName',
      'endpoint',
      'location',
      'policyData',
      'project',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_endpoint_iam_policy`.\n\nAuthoritative IAM policy for a Vertex Ai Endpoint.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleVertexAiEndpointIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_feature_group_iam_binding',
    className: 'GoogleVertexAiFeatureGroupIamBinding',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_vertex_ai_feature_group_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'featureGroup',
      'members',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_feature_group_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Vertex Ai Feature Group.\n\nReplaces the entire member list for that role. Prefer\n[GoogleVertexAiFeatureGroupIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_feature_group_iam_member',
    className: 'GoogleVertexAiFeatureGroupIamMember',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_vertex_ai_feature_group_iam_member`.',
    constructorParams: <String>[
      'localName',
      'featureGroup',
      'member',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_feature_group_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_feature_group_iam_policy',
    className: 'GoogleVertexAiFeatureGroupIamPolicy',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_vertex_ai_feature_group_iam_policy`.',
    constructorParams: <String>[
      'localName',
      'featureGroup',
      'policyData',
      'project',
      'region',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_feature_group_iam_policy`.\n\nAuthoritative IAM policy for a Vertex Ai Feature Group.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleVertexAiFeatureGroupIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_feature_online_store_featureview_iam_binding',
    className: 'GoogleVertexAiFeatureOnlineStoreFeatureviewIamBinding',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_vertex_ai_feature_online_store_featureview_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'featureOnlineStore',
      'featureView',
      'members',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_feature_online_store_featureview_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Vertex Ai Feature Online Store Featureview.\n\nReplaces the entire member list for that role. Prefer\n[GoogleVertexAiFeatureOnlineStoreFeatureviewIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_feature_online_store_featureview_iam_member',
    className: 'GoogleVertexAiFeatureOnlineStoreFeatureviewIamMember',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_vertex_ai_feature_online_store_featureview_iam_member`.',
    constructorParams: <String>[
      'localName',
      'featureOnlineStore',
      'featureView',
      'member',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_feature_online_store_featureview_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_feature_online_store_featureview_iam_policy',
    className: 'GoogleVertexAiFeatureOnlineStoreFeatureviewIamPolicy',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_vertex_ai_feature_online_store_featureview_iam_policy`.',
    constructorParams: <String>[
      'localName',
      'featureOnlineStore',
      'featureView',
      'policyData',
      'project',
      'region',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_feature_online_store_featureview_iam_policy`.\n\nAuthoritative IAM policy for a Vertex Ai Feature Online Store Featureview.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleVertexAiFeatureOnlineStoreFeatureviewIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_feature_online_store_iam_binding',
    className: 'GoogleVertexAiFeatureOnlineStoreIamBinding',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_vertex_ai_feature_online_store_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'featureOnlineStore',
      'members',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_feature_online_store_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Vertex Ai Feature Online Store.\n\nReplaces the entire member list for that role. Prefer\n[GoogleVertexAiFeatureOnlineStoreIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_feature_online_store_iam_member',
    className: 'GoogleVertexAiFeatureOnlineStoreIamMember',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_vertex_ai_feature_online_store_iam_member`.',
    constructorParams: <String>[
      'localName',
      'featureOnlineStore',
      'member',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_feature_online_store_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_feature_online_store_iam_policy',
    className: 'GoogleVertexAiFeatureOnlineStoreIamPolicy',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_vertex_ai_feature_online_store_iam_policy`.',
    constructorParams: <String>[
      'localName',
      'featureOnlineStore',
      'policyData',
      'project',
      'region',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_feature_online_store_iam_policy`.\n\nAuthoritative IAM policy for a Vertex Ai Feature Online Store.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleVertexAiFeatureOnlineStoreIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_featurestore_entitytype_iam_binding',
    className: 'GoogleVertexAiFeaturestoreEntitytypeIamBinding',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_vertex_ai_featurestore_entitytype_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'entitytype',
      'featurestore',
      'members',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_featurestore_entitytype_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Vertex Ai Featurestore Entitytype.\n\nReplaces the entire member list for that role. Prefer\n[GoogleVertexAiFeaturestoreEntitytypeIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_featurestore_entitytype_iam_member',
    className: 'GoogleVertexAiFeaturestoreEntitytypeIamMember',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_vertex_ai_featurestore_entitytype_iam_member`.',
    constructorParams: <String>[
      'localName',
      'entitytype',
      'featurestore',
      'member',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_featurestore_entitytype_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_featurestore_entitytype_iam_policy',
    className: 'GoogleVertexAiFeaturestoreEntitytypeIamPolicy',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_vertex_ai_featurestore_entitytype_iam_policy`.',
    constructorParams: <String>[
      'localName',
      'entitytype',
      'featurestore',
      'policyData',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_featurestore_entitytype_iam_policy`.\n\nAuthoritative IAM policy for a Vertex Ai Featurestore Entitytype.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleVertexAiFeaturestoreEntitytypeIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_featurestore_iam_binding',
    className: 'GoogleVertexAiFeaturestoreIamBinding',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_vertex_ai_featurestore_iam_binding`.',
    constructorParams: <String>[
      'localName',
      'featurestore',
      'members',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_featurestore_iam_binding`.\n\nAuthoritative IAM binding for a single `role` on a Vertex Ai Featurestore.\n\nReplaces the entire member list for that role. Prefer\n[GoogleVertexAiFeaturestoreIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_featurestore_iam_member',
    className: 'GoogleVertexAiFeaturestoreIamMember',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_vertex_ai_featurestore_iam_member`.',
    constructorParams: <String>[
      'localName',
      'featurestore',
      'member',
      'project',
      'region',
      'role',
      'condition',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_featurestore_iam_member`.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_featurestore_iam_policy',
    className: 'GoogleVertexAiFeaturestoreIamPolicy',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_vertex_ai_featurestore_iam_policy`.',
    constructorParams: <String>[
      'localName',
      'featurestore',
      'policyData',
      'project',
      'region',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_featurestore_iam_policy`.\n\nAuthoritative IAM policy for a Vertex Ai Featurestore.\n\nOverwrites every role binding on the resource. Prefer\n[GoogleVertexAiFeaturestoreIamMember] for additive grants.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_metadata_store',
    className: 'GoogleVertexAiMetadataStore',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `google_vertex_ai_metadata_store`.',
    constructorParams: <String>[
      'localName',
      'deletionPolicy',
      'description',
      'name',
      'project',
      'region',
      'encryptionSpec',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment: 'Factory wrapper for `google_vertex_ai_metadata_store`.',
  ),
  CatalogEntry(
    tfType: 'google_vertex_ai_model_garden_enable_model',
    className: 'GoogleVertexAiModelGardenEnableModel',
    barrel: 'vertex_ai',
    kind: CatalogKind.resource,
    summary:
        'Factory wrapper for `google_vertex_ai_model_garden_enable_model`.',
    constructorParams: <String>['localName', 'project', 'publisherModelName'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `google_vertex_ai_model_garden_enable_model`.',
  ),
];
