import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;
import 'package:terradart_codegen/src/cli/cli_runner.dart';
import 'package:terradart_codegen/src/cli/exit_codes.dart';
import 'package:test/test.dart';

void main() {
  group('WrapCommand args parse', () {
    test('wrap command is registered', () {
      final runner = buildCliRunner();
      final wrap = runner.commands['wrap'];
      expect(wrap, isNotNull);
      expect(wrap!.name, 'wrap');
    });

    test('--source missing returns dataError', () async {
      final runner = buildCliRunner();
      final code = await runner.run([
        'wrap',
        '--provider',
        'hashicorp/google',
      ]);
      expect(code, CliExitCodes.dataError);
    });

    test('invalid --provider format throws UsageException', () {
      final runner = buildCliRunner();
      expect(
        () => runner.run([
          'wrap',
          '--provider',
          'INVALID',
          '--source',
          '/tmp',
        ]),
        throwsA(isA<UsageException>()),
      );
    });
  });

  group('WrapCommand integration', () {
    test(
        'emits 56 files (27 resource Layer 2 + 27 resource Layer 1 + 1 data source Layer 2 + 1 data source Layer 1)',
        () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_wrap_');
      try {
        final runner = buildCliRunner();
        final code = await runner.run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        expect(code, 0);

        final files = <String>[];
        for (final ent in Directory(tmpOut.path).listSync(recursive: true)) {
          if (ent is File && ent.path.endsWith('.dart')) {
            files.add(p.relative(ent.path, from: tmpOut.path));
          }
        }
        expect(files, hasLength(56));
        expect(files, contains(p.join('pubsub', 'google_pubsub_topic.dart')));
        expect(files, contains(p.join('data', 'google_project.dart')));
        expect(
          files,
          contains(p.join('generated', 'data_google_project.schema.dart')),
        );
        // Phase 4.5.0: resource Layer 1 emit added.
        expect(
          files,
          contains(p.join('generated', 'google_pubsub_topic.schema.dart')),
        );
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('all generated files start with an accepted generated marker',
        () async {
      // Phase 4.5.0: wrap emits two header conventions side by side.
      // - Layer 2 + data source Layer 1 (DataSourceClassEmitter):
      //   `// GENERATED FILE - DO NOT EDIT`
      // - Resource Layer 1 (FileEmitter, pre-Phase 4.1 convention preserved
      //   for byte-identical compatibility with the existing 13 baselines):
      //   `// Generated by terradart codegen. DO NOT EDIT.`
      // The wrap_command's E401 guard accepts both; this test mirrors that.
      const acceptedFirstLines = {
        '// GENERATED FILE - DO NOT EDIT',
        '// Generated by terradart codegen. DO NOT EDIT.',
      };
      final tmpOut = await Directory.systemTemp.createTemp('phase4_wrap_');
      try {
        final runner = buildCliRunner();
        await runner.run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        for (final ent in Directory(tmpOut.path).listSync(recursive: true)) {
          if (ent is File && ent.path.endsWith('.dart')) {
            final firstLine = ent.readAsLinesSync().first;
            expect(acceptedFirstLines, contains(firstLine), reason: ent.path);
          }
        }
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand --check', () {
    test('exit 0 when generated matches existing', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_check_');
      try {
        final runner = buildCliRunner();
        await runner.run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
          '--check',
        ]);
        expect(code, 0);
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('exit non-zero when one file differs', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_check_');
      try {
        await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        final f =
            File(p.join(tmpOut.path, 'pubsub', 'google_pubsub_topic.dart'));
        var src = f.readAsStringSync();
        src = src.replaceFirst(
            'class GooglePubsubTopic', 'class GooglePubsubTopicMUTATED');
        f.writeAsStringSync(src);
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
          '--check',
        ]);
        expect(code, isNot(0));
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('aggregates multiple file diffs (still non-zero)', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_check_');
      try {
        await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        for (final rel in [
          'pubsub/google_pubsub_topic.dart',
          'data/google_project.dart'
        ]) {
          final f = File(p.join(tmpOut.path, rel));
          f.writeAsStringSync('${f.readAsStringSync()}\n// trailing edit\n');
        }
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
          '--check',
        ]);
        expect(code, isNot(0));
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand --force', () {
    test('refuses to overwrite non-generated file by default (E401)', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_force_');
      try {
        // Pre-create a non-generated file at one of wrap's target paths.
        final dir = Directory(p.join(tmpOut.path, 'pubsub'));
        dir.createSync(recursive: true);
        const preExisting = '// hand-written, not generated\nclass Foo {}\n';
        final f = File(p.join(dir.path, 'google_pubsub_topic.dart'));
        f.writeAsStringSync(preExisting);

        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        expect(code, isNot(0));
        expect(f.readAsStringSync(), preExisting);
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('--force overwrites the non-generated file', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_force_');
      try {
        final dir = Directory(p.join(tmpOut.path, 'pubsub'));
        dir.createSync(recursive: true);
        final f = File(p.join(dir.path, 'google_pubsub_topic.dart'));
        f.writeAsStringSync('// hand-written, not generated\nclass Foo {}\n');

        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
          '--force',
        ]);
        expect(code, 0);
        expect(f.readAsStringSync().startsWith('// GENERATED FILE'), isTrue);
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand fixture-driven', () {
    // Fixture files are stored with a `.dart.golden` suffix (matching the
    // project-wide golden naming convention under `test/golden/`) so they
    // are byte-frozen and not rewritten by `dart format`. The wrap-emit
    // pipeline formats with `DartFormatter.latestLanguageVersion`, which
    // can diverge from this package's pubspec SDK constraint formatter
    // version; the `.golden` extension keeps `dart format .` from touching
    // them while still letting the test diff bytes 1:1 against the wrap
    // output (the `.golden` suffix is stripped when computing actualPath).
    test('output matches expected_output exactly (14 files)', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_fix_');
      try {
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        expect(code, 0);

        final fixtureDir = Directory(
          p.join('test', 'fixtures', 'wrap', 'expected_output'),
        );
        var checked = 0;
        for (final fixFile
            in fixtureDir.listSync(recursive: true).whereType<File>()) {
          final rel = p.relative(fixFile.path, from: fixtureDir.path);
          // Strip the trailing `.golden` so the path lines up with the
          // wrap output on disk (`.dart.golden` → `.dart`).
          final actualRel = rel.endsWith('.golden')
              ? rel.substring(0, rel.length - '.golden'.length)
              : rel;
          final actualPath = p.join(tmpOut.path, actualRel);
          final actual =
              File(actualPath).readAsStringSync().replaceAll('\r\n', '\n');
          final expected = fixFile.readAsStringSync().replaceAll('\r\n', '\n');
          expect(actual, expected, reason: actualRel);
          checked++;
        }
        expect(checked, 14, reason: 'fixture must hold exactly 14 files');
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });
}
