import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;
import 'package:terradart_codegen/src/cli/cli_runner.dart';
import 'package:terradart_codegen/src/cli/exit_codes.dart';
import 'package:test/test.dart';

void main() {
  group('WrapInitCommand args parse', () {
    test('wrap-init is registered in the cli runner', () {
      final runner = buildCliRunner();
      final cmd = runner.commands['wrap-init'];
      expect(cmd, isNotNull);
      expect(cmd!.name, 'wrap-init');
    });

    test('missing <resource> positional → usage error', () {
      final runner = buildCliRunner();
      expect(
        () => runner.run(['wrap-init', '--source', '/tmp', '--output', '/tmp']),
        throwsA(isA<UsageException>()),
      );
    });

    test('--source missing returns dataError', () async {
      final runner = buildCliRunner();
      final code = await runner.run([
        'wrap-init',
        'google_pubsub_topic',
        '--output',
        '/tmp',
      ]);
      expect(code, CliExitCodes.dataError);
    });

    test('--output missing returns dataError', () async {
      final runner = buildCliRunner();
      final code = await runner.run([
        'wrap-init',
        'google_pubsub_topic',
        '--source',
        '/tmp',
      ]);
      expect(code, CliExitCodes.dataError);
    });

    test('invalid --provider format throws UsageException', () {
      final runner = buildCliRunner();
      expect(
        () => runner.run([
          'wrap-init',
          'google_pubsub_topic',
          '--provider',
          'INVALID',
          '--source',
          '/tmp',
          '--output',
          '/tmp',
        ]),
        throwsA(isA<UsageException>()),
      );
    });

    test('--provider hashicorp/aws → usage error (only google supported)', () {
      final runner = buildCliRunner();
      expect(
        () => runner.run([
          'wrap-init',
          'google_pubsub_topic',
          '--provider',
          'hashicorp/aws',
          '--source',
          '/tmp',
          '--output',
          '/tmp',
        ]),
        throwsA(isA<UsageException>()),
      );
    });
  });

  group('WrapInitCommand happy + overwrite', () {
    test('emits 1 file at <output>/<resource>.yaml with banner', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_wrap_init_');
      try {
        final runner = buildCliRunner();
        final code = await runner.run([
          'wrap-init',
          'google_pubsub_topic',
          '--source',
          p.join('test', 'fixtures'),
          '--output',
          tmpOut.path,
        ]);
        expect(code, 0);

        final out = File(p.join(tmpOut.path, 'google_pubsub_topic.yaml'));
        expect(out.existsSync(), isTrue);
        final body = out.readAsStringSync();
        expect(body, startsWith('# Auto-generated by `terradart wrap-init`'));
        expect(body, contains('outputDir: pubsub'));
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('resource not in schema returns dataError', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_wrap_init_');
      try {
        final runner = buildCliRunner();
        final code = await runner.run([
          'wrap-init',
          'google_does_not_exist',
          '--source',
          p.join('test', 'fixtures'),
          '--output',
          tmpOut.path,
        ]);
        expect(code, CliExitCodes.dataError);
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('existing yaml without --force returns E402; --force overwrites',
        () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_wrap_init_');
      try {
        final yamlPath = File(p.join(tmpOut.path, 'google_pubsub_topic.yaml'));
        const originalBytes = '# hand-edited, do not clobber\n';
        yamlPath.writeAsStringSync(originalBytes);

        // Without --force: refuse.
        final code1 = await buildCliRunner().run([
          'wrap-init',
          'google_pubsub_topic',
          '--source',
          p.join('test', 'fixtures'),
          '--output',
          tmpOut.path,
        ]);
        expect(code1, CliExitCodes.dataError);
        expect(yamlPath.readAsStringSync(), originalBytes);

        // With --force: overwrite.
        final code2 = await buildCliRunner().run([
          'wrap-init',
          'google_pubsub_topic',
          '--source',
          p.join('test', 'fixtures'),
          '--output',
          tmpOut.path,
          '--force',
        ]);
        expect(code2, 0);
        expect(yamlPath.readAsStringSync(), isNot(originalBytes));
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });
}
