import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;
import 'package:terradart_codegen/src/cli/cli_runner.dart';
import 'package:terradart_codegen/src/cli/exit_codes.dart';
import 'package:test/test.dart';

void main() {
  group('WrapCommand args parse', () {
    test('wrap command is registered', () {
      final runner = buildCliRunner();
      final wrap = runner.commands['wrap'];
      expect(wrap, isNotNull);
      expect(wrap!.name, 'wrap');
    });

    test('--source missing returns dataError', () async {
      final runner = buildCliRunner();
      final code = await runner.run([
        'wrap',
        '--provider',
        'hashicorp/google',
      ]);
      expect(code, CliExitCodes.dataError);
    });

    test('invalid --provider format throws UsageException', () {
      final runner = buildCliRunner();
      expect(
        () => runner.run([
          'wrap',
          '--provider',
          'INVALID',
          '--source',
          '/tmp',
        ]),
        throwsA(isA<UsageException>()),
      );
    });
  });

  group('WrapCommand integration', () {
    test(
        'emits 324 files (322 resource Layer 2 + 1 data source Layer 2 + 1 generated _catalog.g.dart)',
        () async {
      // Plan 5.X (v0.5.0-dev): the schemantic Layer 1 chain
      // (`generated/<type>.schema.dart` + `generated/<type>.schema.g.dart`
      // + `generated/data_<type>.schema.dart`) is retired. Only Layer 2
      // factory wrappers are emitted — one per wrapper-override YAML.
      final tmpOut = await Directory.systemTemp.createTemp('phase4_wrap_');
      try {
        final runner = buildCliRunner();
        final code = await runner.run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        expect(code, 0);

        final files = <String>[];
        for (final ent in Directory(tmpOut.path).listSync(recursive: true)) {
          if (ent is File && ent.path.endsWith('.dart')) {
            files.add(p.relative(ent.path, from: tmpOut.path));
          }
        }
        // 323 wrappers (322 resource Layer 2 + 1 data source Layer 2) plus
        // the generated static catalog `_catalog.g.dart` (one CatalogEntry
        // per wrapper) → 324 emitted .dart files.
        expect(files, hasLength(324));
        expect(files, contains('_catalog.g.dart'));
        expect(files, contains(p.join('pubsub', 'google_pubsub_topic.dart')));
        expect(files, contains(p.join('data', 'google_project.dart')));
        // Plan 5.X: Layer 1 files are no longer emitted.
        expect(
          files,
          isNot(
              contains(p.join('generated', 'data_google_project.schema.dart'))),
        );
        expect(
          files,
          isNot(
              contains(p.join('generated', 'google_pubsub_topic.schema.dart'))),
        );
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('all generated files start with an accepted generated marker',
        () async {
      // Phase 4.5.0: wrap emits two header conventions side by side.
      // - Layer 2 + data source Layer 1 (DataSourceClassEmitter):
      //   `// GENERATED FILE - DO NOT EDIT`
      // - Resource Layer 1 (FileEmitter, pre-Phase 4.1 convention preserved
      //   for byte-identical compatibility with the existing 13 baselines):
      //   `// Generated by terradart codegen. DO NOT EDIT.`
      // The wrap_command's E401 guard accepts both; this test mirrors that.
      const acceptedFirstLines = {
        '// GENERATED FILE - DO NOT EDIT',
        '// Generated by terradart codegen. DO NOT EDIT.',
      };
      final tmpOut = await Directory.systemTemp.createTemp('phase4_wrap_');
      try {
        final runner = buildCliRunner();
        await runner.run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        for (final ent in Directory(tmpOut.path).listSync(recursive: true)) {
          if (ent is File && ent.path.endsWith('.dart')) {
            final firstLine = ent.readAsLinesSync().first;
            expect(acceptedFirstLines, contains(firstLine), reason: ent.path);
          }
        }
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand --check', () {
    test('exit 0 when generated matches existing', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_check_');
      try {
        final runner = buildCliRunner();
        await runner.run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
          '--check',
        ]);
        expect(code, 0);
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('exit non-zero when one file differs', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_check_');
      try {
        await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        final f =
            File(p.join(tmpOut.path, 'pubsub', 'google_pubsub_topic.dart'));
        var src = f.readAsStringSync();
        src = src.replaceFirst(
            'class GooglePubsubTopic', 'class GooglePubsubTopicMUTATED');
        f.writeAsStringSync(src);
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
          '--check',
        ]);
        expect(code, isNot(0));
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('aggregates multiple file diffs (still non-zero)', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_check_');
      try {
        await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        for (final rel in [
          'pubsub/google_pubsub_topic.dart',
          'data/google_project.dart'
        ]) {
          final f = File(p.join(tmpOut.path, rel));
          f.writeAsStringSync('${f.readAsStringSync()}\n// trailing edit\n');
        }
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
          '--check',
        ]);
        expect(code, isNot(0));
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand --force', () {
    test('refuses to overwrite non-generated file by default (E401)', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_force_');
      try {
        // Pre-create a non-generated file at one of wrap's target paths.
        final dir = Directory(p.join(tmpOut.path, 'pubsub'));
        dir.createSync(recursive: true);
        const preExisting = '// hand-written, not generated\nclass Foo {}\n';
        final f = File(p.join(dir.path, 'google_pubsub_topic.dart'));
        f.writeAsStringSync(preExisting);

        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        expect(code, isNot(0));
        expect(f.readAsStringSync(), preExisting);
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('--force overwrites the non-generated file', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_force_');
      try {
        final dir = Directory(p.join(tmpOut.path, 'pubsub'));
        dir.createSync(recursive: true);
        final f = File(p.join(dir.path, 'google_pubsub_topic.dart'));
        f.writeAsStringSync('// hand-written, not generated\nclass Foo {}\n');

        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
          '--force',
        ]);
        expect(code, 0);
        expect(f.readAsStringSync().startsWith('// GENERATED FILE'), isTrue);
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand --only', () {
    test('emits exactly 1 file (Layer 2 wrapper only) for one resource',
        () async {
      // Plan 5.X (v0.5.0-dev): Layer 1 emit retired. `--only <type>` now
      // produces a single wrapper file rather than the historical Layer 1
      // + Layer 2 pair.
      final tmpOut = await Directory.systemTemp.createTemp('phase4_only_');
      try {
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
          '--only',
          'google_pubsub_topic',
        ]);
        expect(code, 0);

        final files = <String>[];
        for (final ent in Directory(tmpOut.path).listSync(recursive: true)) {
          if (ent is File && ent.path.endsWith('.dart')) {
            files.add(p.relative(ent.path, from: tmpOut.path));
          }
        }
        expect(files, hasLength(1));
        expect(files, contains(p.join('pubsub', 'google_pubsub_topic.dart')));
        // `--only` is a partial regen, so the whole-registry catalog is NOT
        // emitted (it must not be clobbered with a single-entry partial).
        expect(files, isNot(contains('_catalog.g.dart')));
        expect(
          files,
          isNot(
              contains(p.join('generated', 'google_pubsub_topic.schema.dart'))),
        );
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('unknown --only target exits with dataError', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_only_');
      try {
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
          '--only',
          'google_no_such_resource',
        ]);
        expect(code, CliExitCodes.dataError);
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand MM YAML', () {
    test('malformed MM YAML exits with dataError (E405)', () async {
      // Build a synthetic --source: a valid schema.json (copied from the
      // real fixture so the schema parse succeeds) plus an mm/ directory
      // holding one intentionally malformed YAML file. The wrap pipeline
      // must surface the parse failure rather than silently dropping the
      // file (which would make `deriveEnums` emit nothing).
      final tmpSrc = await Directory.systemTemp.createTemp('phase4_mm_bad_');
      final tmpOut = await Directory.systemTemp.createTemp('phase4_mm_out_');
      try {
        final fixtureSchema = File(
          p.join('test', 'fixtures', 'wrap', 'source', 'schema.json'),
        );
        File(p.join(tmpSrc.path, 'schema.json'))
            .writeAsStringSync(fixtureSchema.readAsStringSync());
        final mmDir = Directory(p.join(tmpSrc.path, 'mm'));
        mmDir.createSync(recursive: true);
        // Unclosed YAML flow mapping → YamlException from loadYaml.
        File(p.join(mmDir.path, 'google_pubsub_schema.yaml'))
            .writeAsStringSync('{ : : :');

        final errBuf = StringBuffer();
        final code = await IOOverrides.runZoned(
          () => buildCliRunner().run([
            'wrap',
            '--provider',
            'hashicorp/google',
            '--source',
            tmpSrc.path,
            '--output',
            tmpOut.path,
          ]),
          stderr: () => _BufferSink(errBuf),
        );
        expect(code, CliExitCodes.dataError);
        expect(errBuf.toString(), contains('[E405]'));
        expect(errBuf.toString(), contains('malformed MM YAML'));
      } finally {
        await tmpSrc.delete(recursive: true);
        await tmpOut.delete(recursive: true);
      }
    });

    test(
        'valid MM enum_values flow through wrap into a derived Dart enum '
        '(happy path)', () async {
      // Positive complement to the malformed-MM test above.
      // Proves: valid enum_values in MM YAML → IrMerger → deriveEnums gate
      // → derived Dart enum in wrap output.
      //
      // The override registry (google_pubsub_schema.yaml with deriveEnums:true)
      // is loaded from the package, not from --source, so the gate is active.
      // We use --only to limit output to a single file and keep the test fast.
      final tmpSrc = await Directory.systemTemp.createTemp('phase4_mm_ok_src_');
      final tmpOut = await Directory.systemTemp.createTemp('phase4_mm_ok_out_');
      try {
        // Copy the real schema.json fixture so schema parse succeeds.
        final fixtureSchema = File(
          p.join('test', 'fixtures', 'wrap', 'source', 'schema.json'),
        );
        File(p.join(tmpSrc.path, 'schema.json'))
            .writeAsStringSync(fixtureSchema.readAsStringSync());

        // Copy the real MM YAML fixture (has enum_values for PubsubSchemaType).
        final fixtureMm = File(
          p.join(
            'test',
            'fixtures',
            'wrap',
            'source',
            'mm',
            'google_pubsub_schema.yaml',
          ),
        );
        final mmDir = Directory(p.join(tmpSrc.path, 'mm'));
        mmDir.createSync(recursive: true);
        File(p.join(mmDir.path, 'google_pubsub_schema.yaml'))
            .writeAsStringSync(fixtureMm.readAsStringSync());

        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          tmpSrc.path,
          '--output',
          tmpOut.path,
          '--only',
          'google_pubsub_schema',
        ]);
        expect(code, CliExitCodes.success);

        final outFile = File(
          p.join(tmpOut.path, 'pubsub', 'google_pubsub_schema.dart'),
        );
        expect(outFile.existsSync(), isTrue);
        final contents = outFile.readAsStringSync();
        expect(
          contents,
          contains('enum PubsubSchemaType implements TerraformEnum {'),
        );
        expect(contents, contains("typeUnspecified('TYPE_UNSPECIFIED'),"));
      } finally {
        await tmpSrc.delete(recursive: true);
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand fixture-driven', () {
    // Fixture files are stored with a `.dart.golden` suffix (matching the
    // project-wide golden naming convention under `test/golden/`) so they
    // are byte-frozen and not rewritten by `dart format`. The wrap-emit
    // pipeline formats with `DartFormatter.latestLanguageVersion`, which
    // can diverge from this package's pubspec SDK constraint formatter
    // version; the `.golden` extension keeps `dart format .` from touching
    // them while still letting the test diff bytes 1:1 against the wrap
    // output (the `.golden` suffix is stripped when computing actualPath).
    test('output matches expected_output exactly (13 files; Plan 5.X)',
        () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_fix_');
      try {
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          tmpOut.path,
        ]);
        expect(code, 0);

        final fixtureDir = Directory(
          p.join('test', 'fixtures', 'wrap', 'expected_output'),
        );
        var checked = 0;
        for (final fixFile
            in fixtureDir.listSync(recursive: true).whereType<File>()) {
          final rel = p.relative(fixFile.path, from: fixtureDir.path);
          // Strip the trailing `.golden` so the path lines up with the
          // wrap output on disk (`.dart.golden` → `.dart`).
          final actualRel = rel.endsWith('.golden')
              ? rel.substring(0, rel.length - '.golden'.length)
              : rel;
          final actualPath = p.join(tmpOut.path, actualRel);
          final actual =
              File(actualPath).readAsStringSync().replaceAll('\r\n', '\n');
          final expected = fixFile.readAsStringSync().replaceAll('\r\n', '\n');
          expect(actual, expected, reason: actualRel);
          checked++;
        }
        expect(checked, 13,
            reason: 'fixture must hold exactly 13 files (Plan 5.X: dropped '
                'generated/data_google_project.schema.dart.golden along with '
                'the rest of Layer 1)');
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });
}

/// Minimal [Stdout] stand-in that appends every `write*` call to a
/// [StringBuffer], so in-process tests can capture what `stderr.writeln` would
/// have printed. `IOOverrides.runZoned`'s `stderr` factory must return a
/// [Stdout]; only the text-writing surface is exercised by the CLI, so the
/// remainder is routed through `noSuchMethod`.
class _BufferSink implements Stdout {
  _BufferSink(this._buf);

  final StringBuffer _buf;

  @override
  void write(Object? object) => _buf.write(object);

  @override
  void writeln([Object? object = '']) => _buf.writeln(object);

  @override
  void writeAll(Iterable<dynamic> objects, [String separator = '']) =>
      _buf.writeAll(objects, separator);

  @override
  void writeCharCode(int charCode) => _buf.writeCharCode(charCode);

  @override
  Future<void> close() async {}

  @override
  Future<void> flush() async {}

  @override
  dynamic noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
