import 'dart:convert';
import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:dart_style/dart_style.dart';
import 'package:path/path.dart' as p;
import 'package:terradart_codegen/src/cli/cli_runner.dart';
import 'package:terradart_codegen/src/cli/exit_codes.dart';
import 'package:terradart_codegen/src/codegen/barrels/barrel_emitter.dart';
import 'package:terradart_codegen/src/codegen/barrels/barrel_manifest.dart';
import 'package:terradart_codegen/src/codegen/catalog_entry_builder.dart';
import 'package:terradart_codegen/src/codegen/wrapper_emitter.dart';
import 'package:terradart_codegen/src/codegen/wrapper_overrides/yaml_loader.dart';
import 'package:terradart_codegen/src/parser/schema_parser.dart';
import 'package:test/test.dart';

/// Barrels are written one level above `--output` (`lib/` beside `lib/src`),
/// so every integration test roots its output at `<tmp>/lib/src` and
/// inspects `<tmp>` recursively.
String _libSrcOut(Directory tmp) => p.join(tmp.path, 'lib', 'src');

void main() {
  group('WrapCommand args parse', () {
    test('wrap command is registered', () {
      final runner = buildCliRunner();
      final wrap = runner.commands['wrap'];
      expect(wrap, isNotNull);
      expect(wrap!.name, 'wrap');
    });

    test('--source missing returns dataError', () async {
      final runner = buildCliRunner();
      final code = await runner.run([
        'wrap',
        '--provider',
        'hashicorp/google',
      ]);
      expect(code, CliExitCodes.dataError);
    });

    test('invalid --provider format throws UsageException', () {
      final runner = buildCliRunner();
      expect(
        () => runner.run([
          'wrap',
          '--provider',
          'INVALID',
          '--source',
          '/tmp',
        ]),
        throwsA(isA<UsageException>()),
      );
    });
  });

  group('WrapCommand integration', () {
    test(
        'emits 576 files (489 wrappers + _catalog.g.dart + 85 barrels + umbrella)',
        () async {
      // Plan 5.X (v0.5.0-dev): the schemantic Layer 1 chain
      // (`generated/<type>.schema.dart` + `generated/<type>.schema.g.dart`
      // + `generated/data_<type>.schema.dart`) is retired. Only Layer 2
      // factory wrappers are emitted — one per wrapper-override YAML.
      final tmpOut = await Directory.systemTemp.createTemp('phase4_wrap_');
      try {
        final runner = buildCliRunner();
        final code = await runner.run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          _libSrcOut(tmpOut),
        ]);
        expect(code, 0);

        final files = <String>[];
        for (final ent in Directory(tmpOut.path).listSync(recursive: true)) {
          if (ent is File && ent.path.endsWith('.dart')) {
            files.add(p.relative(ent.path, from: tmpOut.path));
          }
        }
        // 489 wrappers (488 resource Layer 2 + 1 data source Layer 2) plus
        // the generated static catalog `_catalog.g.dart`, plus the derived
        // barrels: 85 per-catalog barrels (84 service + `data`) and the
        // `terradart_google.dart` umbrella → 576 emitted .dart files.
        expect(files, hasLength(576));
        expect(files, contains(p.join('lib', 'src', '_catalog.g.dart')));
        expect(
          files,
          contains(p.join('lib', 'src', 'pubsub', 'google_pubsub_topic.dart')),
        );
        expect(
          files,
          contains(p.join('lib', 'src', 'data', 'google_project.dart')),
        );
        // Derived barrels land one level up, under lib/.
        expect(files, contains(p.join('lib', 'pubsub.dart')));
        expect(files, contains(p.join('lib', 'data.dart')));
        // The `sql` barrel keeps its authored file-name override.
        expect(files, contains(p.join('lib', 'cloud_sql.dart')));
        expect(files, isNot(contains(p.join('lib', 'sql.dart'))));
        expect(files, contains(p.join('lib', 'terradart_google.dart')));
        // Plan 5.X: Layer 1 files are no longer emitted.
        expect(
          files,
          isNot(contains(p.join(
              'lib', 'src', 'generated', 'data_google_project.schema.dart'))),
        );
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('all generated files start with an accepted generated marker',
        () async {
      // Phase 4.5.0: wrap emits two header conventions side by side.
      // - Layer 2 + data source Layer 1 (DataSourceClassEmitter):
      //   `// GENERATED FILE - DO NOT EDIT`
      // - Resource Layer 1 (FileEmitter, pre-Phase 4.1 convention preserved
      //   for byte-identical compatibility with the existing 13 baselines):
      //   `// Generated by terradart codegen. DO NOT EDIT.`
      // The wrap_command's E401 guard accepts both; this test mirrors that.
      const acceptedFirstLines = {
        '// GENERATED FILE - DO NOT EDIT',
        '// Generated by terradart codegen. DO NOT EDIT.',
      };
      final tmpOut = await Directory.systemTemp.createTemp('phase4_wrap_');
      try {
        final runner = buildCliRunner();
        await runner.run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          _libSrcOut(tmpOut),
        ]);
        for (final ent in Directory(tmpOut.path).listSync(recursive: true)) {
          if (ent is File && ent.path.endsWith('.dart')) {
            final firstLine = ent.readAsLinesSync().first;
            expect(acceptedFirstLines, contains(firstLine), reason: ent.path);
          }
        }
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand --check', () {
    test('exit 0 when generated matches existing', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_check_');
      try {
        final runner = buildCliRunner();
        await runner.run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          _libSrcOut(tmpOut),
        ]);
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          _libSrcOut(tmpOut),
          '--check',
        ]);
        expect(code, 0);
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('exit non-zero when one file differs', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_check_');
      try {
        await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          _libSrcOut(tmpOut),
        ]);
        final f = File(
            p.join(_libSrcOut(tmpOut), 'pubsub', 'google_pubsub_topic.dart'));
        var src = f.readAsStringSync();
        src = src.replaceFirst(
            'class GooglePubsubTopic', 'class GooglePubsubTopicMUTATED');
        f.writeAsStringSync(src);
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          _libSrcOut(tmpOut),
          '--check',
        ]);
        expect(code, isNot(0));
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('aggregates multiple file diffs (still non-zero)', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_check_');
      try {
        await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          _libSrcOut(tmpOut),
        ]);
        for (final rel in [
          p.join('src', 'pubsub', 'google_pubsub_topic.dart'),
          p.join('src', 'data', 'google_project.dart'),
          // A derived barrel is part of the --check surface too.
          'pubsub.dart',
        ]) {
          final f = File(p.join(tmpOut.path, 'lib', rel));
          f.writeAsStringSync('${f.readAsStringSync()}\n// trailing edit\n');
        }
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          _libSrcOut(tmpOut),
          '--check',
        ]);
        expect(code, isNot(0));
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand --force', () {
    test('refuses to overwrite non-generated file by default (E401)', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_force_');
      try {
        // Pre-create a non-generated file at one of wrap's target paths.
        final dir = Directory(p.join(_libSrcOut(tmpOut), 'pubsub'));
        dir.createSync(recursive: true);
        const preExisting = '// hand-written, not generated\nclass Foo {}\n';
        final f = File(p.join(dir.path, 'google_pubsub_topic.dart'));
        f.writeAsStringSync(preExisting);

        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          _libSrcOut(tmpOut),
        ]);
        expect(code, isNot(0));
        expect(f.readAsStringSync(), preExisting);
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('--force overwrites the non-generated file', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_force_');
      try {
        final dir = Directory(p.join(_libSrcOut(tmpOut), 'pubsub'));
        dir.createSync(recursive: true);
        final f = File(p.join(dir.path, 'google_pubsub_topic.dart'));
        f.writeAsStringSync('// hand-written, not generated\nclass Foo {}\n');

        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          _libSrcOut(tmpOut),
          '--force',
        ]);
        expect(code, 0);
        expect(f.readAsStringSync().startsWith('// GENERATED FILE'), isTrue);
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand --only', () {
    test('emits exactly 1 file (Layer 2 wrapper only) for one resource',
        () async {
      // Plan 5.X (v0.5.0-dev): Layer 1 emit retired. `--only <type>` now
      // produces a single wrapper file rather than the historical Layer 1
      // + Layer 2 pair.
      final tmpOut = await Directory.systemTemp.createTemp('phase4_only_');
      try {
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          _libSrcOut(tmpOut),
          '--only',
          'google_pubsub_topic',
        ]);
        expect(code, 0);

        final files = <String>[];
        for (final ent in Directory(tmpOut.path).listSync(recursive: true)) {
          if (ent is File && ent.path.endsWith('.dart')) {
            files.add(p.relative(ent.path, from: tmpOut.path));
          }
        }
        expect(files, hasLength(1));
        expect(
          files,
          contains(p.join('lib', 'src', 'pubsub', 'google_pubsub_topic.dart')),
        );
        // `--only` is a partial regen, so the whole-registry catalog and the
        // derived barrels are NOT emitted (they must not be clobbered with a
        // single-entry partial).
        expect(files, isNot(contains(p.join('lib', 'src', '_catalog.g.dart'))));
        expect(files, isNot(contains(p.join('lib', 'pubsub.dart'))));
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });

    test('unknown --only target exits with dataError', () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_only_');
      try {
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          _libSrcOut(tmpOut),
          '--only',
          'google_no_such_resource',
        ]);
        expect(code, CliExitCodes.dataError);
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand MM YAML', () {
    test('malformed MM YAML exits with dataError (E405)', () async {
      // Build a synthetic --source: a valid schema.json (copied from the
      // real fixture so the schema parse succeeds) plus an mm/ directory
      // holding one intentionally malformed YAML file. The wrap pipeline
      // must surface the parse failure rather than silently dropping the
      // file (which would make `deriveEnums` emit nothing).
      final tmpSrc = await Directory.systemTemp.createTemp('phase4_mm_bad_');
      final tmpOut = await Directory.systemTemp.createTemp('phase4_mm_out_');
      try {
        final fixtureSchema = File(
          p.join('test', 'fixtures', 'wrap', 'source', 'schema.json'),
        );
        File(p.join(tmpSrc.path, 'schema.json'))
            .writeAsStringSync(fixtureSchema.readAsStringSync());
        final mmDir = Directory(p.join(tmpSrc.path, 'mm'));
        mmDir.createSync(recursive: true);
        // Unclosed YAML flow mapping → YamlException from loadYaml.
        File(p.join(mmDir.path, 'google_pubsub_schema.yaml'))
            .writeAsStringSync('{ : : :');

        final errBuf = StringBuffer();
        final code = await IOOverrides.runZoned(
          () => buildCliRunner().run([
            'wrap',
            '--provider',
            'hashicorp/google',
            '--source',
            tmpSrc.path,
            '--output',
            _libSrcOut(tmpOut),
          ]),
          stderr: () => _BufferSink(errBuf),
        );
        expect(code, CliExitCodes.dataError);
        expect(errBuf.toString(), contains('[E405]'));
        expect(errBuf.toString(), contains('malformed MM YAML'));
      } finally {
        await tmpSrc.delete(recursive: true);
        await tmpOut.delete(recursive: true);
      }
    });

    test(
        'valid MM enum_values flow through wrap into a derived Dart enum '
        '(happy path)', () async {
      // Positive complement to the malformed-MM test above.
      // Proves: valid enum_values in MM YAML → IrMerger → deriveEnums gate
      // → derived Dart enum in wrap output.
      //
      // The override registry (google_pubsub_schema.yaml with deriveEnums:true)
      // is loaded from the package, not from --source, so the gate is active.
      // We use --only to limit output to a single file and keep the test fast.
      final tmpSrc = await Directory.systemTemp.createTemp('phase4_mm_ok_src_');
      final tmpOut = await Directory.systemTemp.createTemp('phase4_mm_ok_out_');
      try {
        // Copy the real schema.json fixture so schema parse succeeds.
        final fixtureSchema = File(
          p.join('test', 'fixtures', 'wrap', 'source', 'schema.json'),
        );
        File(p.join(tmpSrc.path, 'schema.json'))
            .writeAsStringSync(fixtureSchema.readAsStringSync());

        // Copy the real MM YAML fixture (has enum_values for PubsubSchemaType).
        final fixtureMm = File(
          p.join(
            'test',
            'fixtures',
            'wrap',
            'source',
            'mm',
            'google_pubsub_schema.yaml',
          ),
        );
        final mmDir = Directory(p.join(tmpSrc.path, 'mm'));
        mmDir.createSync(recursive: true);
        File(p.join(mmDir.path, 'google_pubsub_schema.yaml'))
            .writeAsStringSync(fixtureMm.readAsStringSync());

        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          tmpSrc.path,
          '--output',
          _libSrcOut(tmpOut),
          '--only',
          'google_pubsub_schema',
        ]);
        expect(code, CliExitCodes.success);

        final outFile = File(
          p.join(_libSrcOut(tmpOut), 'pubsub', 'google_pubsub_schema.dart'),
        );
        expect(outFile.existsSync(), isTrue);
        final contents = outFile.readAsStringSync();
        expect(
          contents,
          contains('enum PubsubSchemaType implements TerraformEnum {'),
        );
        expect(contents, contains("typeUnspecified('TYPE_UNSPECIFIED'),"));
      } finally {
        await tmpSrc.delete(recursive: true);
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand fixture-driven', () {
    // Fixture files are stored with a `.dart.golden` suffix (matching the
    // project-wide golden naming convention under `test/golden/`) so they
    // are byte-frozen and not rewritten by `dart format`. The wrap-emit
    // pipeline formats with `DartFormatter.latestLanguageVersion`, which
    // can diverge from this package's pubspec SDK constraint formatter
    // version; the `.golden` extension keeps `dart format .` from touching
    // them while still letting the test diff bytes 1:1 against the wrap
    // output (the `.golden` suffix is stripped when computing actualPath).
    test('output matches expected_output exactly (13 files; Plan 5.X)',
        () async {
      final tmpOut = await Directory.systemTemp.createTemp('phase4_fix_');
      try {
        final code = await buildCliRunner().run([
          'wrap',
          '--provider',
          'hashicorp/google',
          '--source',
          p.join('test', 'fixtures', 'wrap', 'source'),
          '--output',
          _libSrcOut(tmpOut),
        ]);
        expect(code, 0);

        final fixtureDir = Directory(
          p.join('test', 'fixtures', 'wrap', 'expected_output'),
        );
        var checked = 0;
        for (final fixFile
            in fixtureDir.listSync(recursive: true).whereType<File>()) {
          final rel = p.relative(fixFile.path, from: fixtureDir.path);
          // Strip the trailing `.golden` so the path lines up with the
          // wrap output on disk (`.dart.golden` → `.dart`).
          final actualRel = rel.endsWith('.golden')
              ? rel.substring(0, rel.length - '.golden'.length)
              : rel;
          final actualPath = p.join(_libSrcOut(tmpOut), actualRel);
          final actual =
              File(actualPath).readAsStringSync().replaceAll('\r\n', '\n');
          final expected = fixFile.readAsStringSync().replaceAll('\r\n', '\n');
          expect(actual, expected, reason: actualRel);
          checked++;
        }
        expect(checked, 13,
            reason: 'fixture must hold exactly 13 files (Plan 5.X: dropped '
                'generated/data_google_project.schema.dart.golden along with '
                'the rest of Layer 1)');
      } finally {
        await tmpOut.delete(recursive: true);
      }
    });
  });

  group('WrapCommand deriveNestedTypes (dark launch)', () {
    // Unlike every other test in this file, this one does NOT go through
    // `buildCliRunner().run(['wrap', ...])`: `WrapCommand` resolves its
    // override registry from the PACKAGE's own committed
    // `lib/src/codegen/wrapper_overrides/yaml/` directory
    // (`Isolate.resolvePackageUri` in `wrap_command.dart`), not from
    // `--source` — there is no CLI flag to point it at a temp override
    // directory instead. Flipping a real committed yaml (even temporarily,
    // even restored in a `finally`) would violate the dark-launch
    // requirement this whole PR exists to satisfy, and risks bleeding into
    // any other test file that loads the same production directory
    // concurrently. So this test drives the same building blocks
    // `WrapCommand.run()` composes — `YamlOverrideLoader` ->
    // `SchemaJsonParser` -> `WrapperEmitter` -> `DartFormatter` ->
    // `buildCatalogEntry` -> `buildBarrelFiles` — directly, against a
    // throwaway temp override, the same way `barrel_derivation_test.dart`
    // exercises `buildBarrelFiles` without going through the CLI at all.
    //
    // The dark-launch invariant for the COMMITTED tree (byte-identical
    // `wrap --check`) is proved by the untouched `WrapCommand --check`
    // group above, which stays green throughout this change.
    test(
        'a temp deriveNestedTypes:true override derives a typed nested '
        'class, narrows the ctor param, and flows into the catalog + a '
        'barrel', () async {
      const terraformType = 'google_app_engine_domain_mapping';
      final tmpOverrideDir =
          await Directory.systemTemp.createTemp('phase4_nested_types_');
      try {
        // Minimal override: only the two slots this test cares about.
        // `paramOrder` may be a subset — slots it omits are simply not
        // emitted (see `WrapperOverride.paramOrder`'s doc) — so dropping
        // `override_strategy` / `deletion_policy` / `project` here (present
        // in the real committed yaml) is deliberate, not an oversight: it
        // keeps this reproduction minimal and free of the unrelated
        // hand-written `override_strategy` enum idiom.
        await File(p.join(tmpOverrideDir.path, '$terraformType.yaml'))
            .writeAsString('''
outputDir: app
deriveNestedTypes: true
paramOrder:
  - domain_name
  - ssl_settings
''');
        final loaded =
            YamlOverrideLoader(rootDir: tmpOverrideDir.path).load().resources;
        expect(loaded.keys, [terraformType]);

        final schemaSrc = File(
          p.join('test', 'fixtures', 'wrap', 'source', 'schema.json'),
        ).readAsStringSync();
        final ir = const SchemaJsonParser().parseString(schemaSrc);
        final def = ir.resources[terraformType]!;

        final emitter = WrapperEmitter(
          overrides: loaded,
          rawResourceSchemas: {
            terraformType: _rawBlockOf(schemaSrc, terraformType),
          },
        );
        final raw = emitter.emit(def, providerSource: 'hashicorp/google');
        final formatter = DartFormatter(
          languageVersion: DartFormatter.latestLanguageVersion,
        );
        final formatted = formatter.format(raw);

        // The derived helper class + its attribute enum are emitted as
        // top-level declarations. Their internal shape is byte-pinned by
        // Task 3's emitter tests; here we only need to confirm the wiring
        // actually reaches them.
        expect(
          formatted,
          contains('final class AppEngineDomainMappingSslSettings {'),
        );
        // The class name is long enough that dart_style wraps `implements
        // TerraformEnum {` onto its own line (83 columns unwrapped), so the
        // two fragments are checked independently rather than as one
        // contiguous string — same wrap-tolerance convention Task 3's tests
        // use elsewhere in this campaign.
        expect(
          formatted,
          contains('enum AppEngineDomainMappingSslSettingsSslManagementType'),
        );
        expect(formatted, contains('implements TerraformEnum {'));

        // The constructor param narrows from the generic
        // `TfArg<Map<String, dynamic>>? sslSettings` passthrough to the
        // typed, bare (non-`TfArg`) class reference. `ssl_settings` is
        // schema-optional (nesting_mode: list, max_items: 1, no min_items),
        // so it stays nullable / un-`required`.
        expect(
          formatted,
          contains('AppEngineDomainMappingSslSettings? sslSettings'),
        );
        expect(
          formatted,
          isNot(contains('TfArg<Map<String, dynamic>>? sslSettings')),
        );

        // The argMap entry wraps the typed helper's own `.encode()` in
        // `TfArg.literal(...)` — matching the hand-written customSlot idiom
        // (e.g. `google_pubsub_subscription.yaml`'s `bigquery_config`) —
        // guarded since the slot is optional. No `!` on `sslSettings` inside
        // the guard: it's a constructor PARAMETER, which the `if (sslSettings
        // != null)` guard promotes to non-nullable (unlike a public FIELD —
        // Dart field promotion is private-only — which is why
        // `nested_type_emitter_test.dart`'s per-attribute/child encoding
        // still needs `!`).
        expect(formatted, contains('if (sslSettings != null)'));
        expect(formatted, contains('TfArg.literal(sslSettings.encode())'));

        // Catalog: `nestedTypes` is scanned from this SAME formatted source
        // (`catalog_entry_builder.dart`'s `scanNestedTypes`) — there is no
        // separate registration list to wire up or keep in sync.
        final entry = buildCatalogEntry(
          tfType: terraformType,
          override: loaded[terraformType]!,
          def: def,
          kind: 'resource',
          emittedSource: formatted,
        );
        expect(
          entry.nestedTypes,
          containsAll([
            'AppEngineDomainMappingSslSettings',
            'AppEngineDomainMappingSslSettingsSslManagementType',
          ]),
        );

        // Barrels: `buildBarrelFiles` merges `className` + `nestedTypes`
        // into one sorted `show` set per barrel (`barrel_emitter.dart`).
        // Confirm the derived names reach a barrel's export line, using a
        // minimal synthetic manifest (mirrors `barrel_derivation_test.dart`)
        // rather than the full 66-barrel production manifest, which needs a
        // catalog entry for every declared barrel.
        final barrelFiles = buildBarrelFiles(
          entries: [entry],
          manifest: const BarrelManifest(
            umbrellaDoc: '/// Umbrella.',
            umbrellaExtraExports: [],
            barrels: {'app': BarrelSpec(doc: '/// App Engine.')},
          ),
        );
        expect(
          barrelFiles['app'],
          contains('AppEngineDomainMappingSslSettings'),
        );
        expect(
          barrelFiles['app'],
          contains('AppEngineDomainMappingSslSettingsSslManagementType'),
        );
      } finally {
        await tmpOverrideDir.delete(recursive: true);
      }
    });
  });
}

/// Loads `resource_schemas[terraformType].block` straight from an
/// already-read schema.json string — the raw shape `collectNestedTypes` (via
/// `WrapperEmitter.rawResourceSchemas`) needs. Mirrors
/// `nested_type_collector_test.dart`'s `_blockOf` helper and
/// `wrap_command.dart`'s own private `_rawResourceBlocks`.
Map<String, dynamic> _rawBlockOf(String schemaJson, String terraformType) {
  final decoded = jsonDecode(schemaJson) as Map<String, dynamic>;
  final providerSchemas =
      (decoded['provider_schemas'] as Map).cast<String, dynamic>();
  final providerBody =
      (providerSchemas.values.single as Map).cast<String, dynamic>();
  final resourceSchemas =
      (providerBody['resource_schemas'] as Map).cast<String, dynamic>();
  final resource =
      (resourceSchemas[terraformType] as Map).cast<String, dynamic>();
  return (resource['block'] as Map).cast<String, dynamic>();
}

/// Minimal [Stdout] stand-in that appends every `write*` call to a
/// [StringBuffer], so in-process tests can capture what `stderr.writeln` would
/// have printed. `IOOverrides.runZoned`'s `stderr` factory must return a
/// [Stdout]; only the text-writing surface is exercised by the CLI, so the
/// remainder is routed through `noSuchMethod`.
class _BufferSink implements Stdout {
  _BufferSink(this._buf);

  final StringBuffer _buf;

  @override
  void write(Object? object) => _buf.write(object);

  @override
  void writeln([Object? object = '']) => _buf.writeln(object);

  @override
  void writeAll(Iterable<dynamic> objects, [String separator = '']) =>
      _buf.writeAll(objects, separator);

  @override
  void writeCharCode(int charCode) => _buf.writeCharCode(charCode);

  @override
  Future<void> close() async {}

  @override
  Future<void> flush() async {}

  @override
  dynamic noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
