import 'package:terradart_codegen/src/codegen/wrap_promote/wrap_promote_marker.dart';
import 'package:test/test.dart';

void main() {
  group('WrapPromoteMarker.stripMarkerSection', () {
    test('yaml without marker is returned unchanged', () {
      const yaml = '''
outputDir: pubsub
classDocComment: |-
  /// Doc.
''';
      expect(WrapPromoteMarker.stripMarkerSection(yaml), yaml);
    });

    test('yaml with marker has the entire block removed', () {
      const yaml = '''
outputDir: pubsub

# === wrap-promote additions (do not edit inside this block; regenerated by wrap-promote) ===
# Generated on 2026-01-01.

prelude: |
  sealed class FooChoice {}

# === end wrap-promote additions ===
''';
      final stripped = WrapPromoteMarker.stripMarkerSection(yaml);
      expect(stripped, isNot(contains('=== wrap-promote additions')));
      expect(stripped, isNot(contains('=== end wrap-promote additions')));
      expect(stripped, contains('outputDir: pubsub'));
    });

    test('wrapWithMarkers then stripMarkerSection is identity (round-trip)',
        () {
      const original = 'outputDir: pubsub\n';
      final wrapped = original +
          WrapPromoteMarker.wrapWithMarkers(
            'prelude: |\n  sealed class FooChoice {}\n',
            DateTime.utc(2026, 1, 1),
          );
      final stripped = WrapPromoteMarker.stripMarkerSection(wrapped);
      // Original content preserved (trailing whitespace may differ; compare trimmed).
      expect(stripped.trim(), original.trim());
    });
  });
}
