// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
// ignore_for_file: prefer_relative_imports
import 'package:terradart_core/terradart_core.dart';

/// Sensitive field paths for `aws_connect_phone_number`.
const Set<String> _awsConnectPhoneNumberSensitive = <String>{};

/// Connect Phone Number Country enum for `country_code`.
enum ConnectPhoneNumberCountryCode implements TerraformEnum {
  af('AF'),
  al('AL'),
  dz('DZ'),
  as('AS'),
  ad('AD'),
  ao('AO'),
  ai('AI'),
  aq('AQ'),
  ag('AG'),
  ar('AR'),
  am('AM'),
  aw('AW'),
  au('AU'),
  at('AT'),
  az('AZ'),
  bs('BS'),
  bh('BH'),
  bd('BD'),
  bb('BB'),
  by('BY'),
  be('BE'),
  bz('BZ'),
  bj('BJ'),
  bm('BM'),
  bt('BT'),
  bo('BO'),
  ba('BA'),
  bw('BW'),
  br('BR'),
  io('IO'),
  vg('VG'),
  bn('BN'),
  bg('BG'),
  bf('BF'),
  bi('BI'),
  kh('KH'),
  cm('CM'),
  ca('CA'),
  cv('CV'),
  ky('KY'),
  cf('CF'),
  td('TD'),
  cl('CL'),
  cn('CN'),
  cx('CX'),
  cc('CC'),
  co('CO'),
  km('KM'),
  ck('CK'),
  cr('CR'),
  hr('HR'),
  cu('CU'),
  cw('CW'),
  cy('CY'),
  cz('CZ'),
  cd('CD'),
  dk('DK'),
  dj('DJ'),
  dm('DM'),
  doCase('DO'),
  tl('TL'),
  ec('EC'),
  eg('EG'),
  sv('SV'),
  gq('GQ'),
  er('ER'),
  ee('EE'),
  et('ET'),
  fk('FK'),
  fo('FO'),
  fj('FJ'),
  fi('FI'),
  fr('FR'),
  pf('PF'),
  ga('GA'),
  gm('GM'),
  ge('GE'),
  de('DE'),
  gh('GH'),
  gi('GI'),
  gr('GR'),
  gl('GL'),
  gd('GD'),
  gu('GU'),
  gt('GT'),
  gg('GG'),
  gn('GN'),
  gw('GW'),
  gy('GY'),
  ht('HT'),
  hn('HN'),
  hk('HK'),
  hu('HU'),
  isCase('IS'),
  inCase('IN'),
  id('ID'),
  ir('IR'),
  iq('IQ'),
  ie('IE'),
  im('IM'),
  il('IL'),
  it('IT'),
  ci('CI'),
  jm('JM'),
  jp('JP'),
  je('JE'),
  jo('JO'),
  kz('KZ'),
  ke('KE'),
  ki('KI'),
  kw('KW'),
  kg('KG'),
  la('LA'),
  lv('LV'),
  lb('LB'),
  ls('LS'),
  lr('LR'),
  ly('LY'),
  li('LI'),
  lt('LT'),
  lu('LU'),
  mo('MO'),
  mk('MK'),
  mg('MG'),
  mw('MW'),
  my('MY'),
  mv('MV'),
  ml('ML'),
  mt('MT'),
  mh('MH'),
  mr('MR'),
  mu('MU'),
  yt('YT'),
  mx('MX'),
  fm('FM'),
  md('MD'),
  mc('MC'),
  mn('MN'),
  me('ME'),
  ms('MS'),
  ma('MA'),
  mz('MZ'),
  mm('MM'),
  na('NA'),
  nr('NR'),
  np('NP'),
  nl('NL'),
  an('AN'),
  nc('NC'),
  nz('NZ'),
  ni('NI'),
  ne('NE'),
  ng('NG'),
  nu('NU'),
  kp('KP'),
  mp('MP'),
  no('NO'),
  om('OM'),
  pk('PK'),
  pw('PW'),
  pa('PA'),
  pg('PG'),
  py('PY'),
  pe('PE'),
  ph('PH'),
  pn('PN'),
  pl('PL'),
  pt('PT'),
  pr('PR'),
  qa('QA'),
  cg('CG'),
  re('RE'),
  ro('RO'),
  ru('RU'),
  rw('RW'),
  bl('BL'),
  sh('SH'),
  kn('KN'),
  lc('LC'),
  mf('MF'),
  pm('PM'),
  vc('VC'),
  ws('WS'),
  sm('SM'),
  st('ST'),
  sa('SA'),
  sn('SN'),
  rs('RS'),
  sc('SC'),
  sl('SL'),
  sg('SG'),
  sx('SX'),
  sk('SK'),
  si('SI'),
  sb('SB'),
  so('SO'),
  za('ZA'),
  kr('KR'),
  es('ES'),
  lk('LK'),
  sd('SD'),
  sr('SR'),
  sj('SJ'),
  sz('SZ'),
  se('SE'),
  ch('CH'),
  sy('SY'),
  tw('TW'),
  tj('TJ'),
  tz('TZ'),
  th('TH'),
  tg('TG'),
  tk('TK'),
  to('TO'),
  tt('TT'),
  tn('TN'),
  tr('TR'),
  tm('TM'),
  tc('TC'),
  tv('TV'),
  vi('VI'),
  ug('UG'),
  ua('UA'),
  ae('AE'),
  gb('GB'),
  us('US'),
  uy('UY'),
  uz('UZ'),
  vu('VU'),
  va('VA'),
  ve('VE'),
  vn('VN'),
  wf('WF'),
  eh('EH'),
  ye('YE'),
  zm('ZM'),
  zw('ZW');

  const ConnectPhoneNumberCountryCode(this.terraformValue);
  @override
  final String terraformValue;
}

/// Connect Phone Number enum for `type`.
enum ConnectPhoneNumberType implements TerraformEnum {
  tollFree('TOLL_FREE'),
  did('DID'),
  uifn('UIFN'),
  shared('SHARED'),
  thirdPartyTf('THIRD_PARTY_TF'),
  thirdPartyDid('THIRD_PARTY_DID'),
  shortCode('SHORT_CODE');

  const ConnectPhoneNumberType(this.terraformValue);
  @override
  final String terraformValue;
}

/// Factory wrapper for `aws_connect_phone_number`.
final class AwsConnectPhoneNumber extends Resource {
  static const String tfType = 'aws_connect_phone_number';

  AwsConnectPhoneNumber({
    required super.localName,
    required TfArg<ConnectPhoneNumberCountryCode> countryCode,
    TfArg<String>? description,
    TfArg<String>? prefix,
    TfArg<String>? region,
    TfArg<Map<String, String>>? tags,
    required TfArg<String> targetArn,
    required TfArg<ConnectPhoneNumberType> type,
    super.lifecycle,
    super.dependsOn,
    super.provider,
    super.timeouts,
  }) : super(
         terraformType: tfType,
         argMap: {
           'country_code': countryCode,
           'description': ?description,
           'prefix': ?prefix,
           'region': ?region,
           'tags': ?tags,
           'target_arn': targetArn,
           'type': type,
         },
       );

  @override
  Set<String> get sensitiveFields => _awsConnectPhoneNumberSensitive;

  /// A reference to this resource, for arguments typed
  /// `RefTo<AwsConnectPhoneNumber>`.
  RefTo<AwsConnectPhoneNumber> get ref => RefTo.of(this);

  /// Reference to `id` attribute.
  TfRef<String> get id => TfRef.attribute<String>(this, 'id');

  /// Reference to `arn` attribute.
  TfRef<String> get arn => TfRef.attribute<String>(this, 'arn');

  /// Reference to `phone_number` attribute.
  TfRef<String> get phoneNumber =>
      TfRef.attribute<String>(this, 'phone_number');

  /// Reference to `status` attribute.
  TfRef<List<Map<String, Object?>>> get status =>
      TfRef.attribute<List<Map<String, Object?>>>(this, 'status');
}
