// bump_new_factories.dart — turns the types a weekly schema bump found
// upstream into factories, so a new type never has to wait for a human.
//
// Usage (from repo root; --diff is tool/schema_resource_diff.dart output):
//   dart tool/bump_new_factories.dart scaffold --lane=google \
//     --diff=/tmp/schema_diff.json --out=/tmp/scaffold.json
//   # ... terradart wrap (tool/wrap_lanes.dart --gate regen) ...
//   dart tool/bump_new_factories.dart record --lane=google \
//     --diff=/tmp/schema_diff.json --detected-at=2026-10-04 \
//     --provider-version=7.47.0 --out=/tmp/new_factories.json
//
// scaffold writes a default override for every added type, the way the
// lane's `bump.scaffold` says: `wrap-init` runs tool/batch_wrap_init.dart
// for the added resources (with --fill-param-order, so the override passes
// the universal invariants unedited); `lane` runs scaffold_lane_overrides.dart, which
// fills every schema type that has no override yet. Existing overrides are
// never touched. A lane with Magic Modules YAML (`mm: true`) first gives
// each added resource its tool/mm_yaml_sources.yaml row, fetching the MM
// fixture when a guessed mmv1 path resolves ([guessMmUpstreams]). A new
// override whose barrel the lane's barrels manifest lacks gets a placeholder
// entry there ([addMissingBarrels]).
// --out receives `{exit, log_excerpt}`.
//
// record runs after the regenerate. Every added type the lane's catalog now
// lists is a new factory: it gets a tool/curation_backlog.yaml entry with a
// note asking for API polish and — unless the lane's `bump.exampleGenerator`
// covers every factory — a `ClassName: awaiting-example: ...` line in
// tool/example_debt.yaml (tool/example_synth_gates.dart requires the
// backlog entry). `--example-generator-ok=false` (the generator failed and
// the example was reverted) writes the debt lines anyway. --out receives `{factories: [{tf_type, class_name,
// kind}]}` for the drift report.
//
// exit: 0 success; 1 scaffolding failed; 64 usage error.
// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;
import 'package:meta/meta.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

import 'append_curation_backlog.dart';
import 'bump_plan.dart';
import 'wrap_lanes.dart';

const exampleDebtPath = 'tool/example_debt.yaml';
const curationBacklogPath = 'tool/curation_backlog.yaml';

/// The `reason` token of an example_debt line a schema bump wrote.
const awaitingExampleToken = 'awaiting-example:';

/// The backlog note of a type the bump already made a factory.
const generatedFactoryNote =
    'factory generated by the schema bump with a default override; polish '
    'its API (paramOrder, sealed slots, curatedDoc) and cover it in an '
    'example';

const _debtSectionHeader = '''
# Awaiting an example: factories the weekly schema bump generated with a
# default override (tool/bump_new_factories.dart record). Each one also has
# a tool/curation_backlog.yaml entry; the synth gate fails an
# `awaiting-example:` line without one. Cover the factory in an example (and
# delete the line) or replace the line with a reasoned entry.''';

const mmSourcesPath = 'tool/mm_yaml_sources.yaml';

final _mmUpstream = RegExp(r'^mmv1/products/([^/]+)/([^/]+)\.yaml$');

String _snake(String camel) => camel
    .replaceAllMapped(
      RegExp(r'(?<=[a-z0-9])[A-Z]|(?<=[A-Z])[A-Z](?=[a-z])'),
      (m) => '_${m[0]}',
    )
    .toLowerCase();

String _camel(String snake) => [
      for (final w in snake.split('_'))
        if (w.isNotEmpty) w[0].toUpperCase() + w.substring(1),
    ].join();

/// Likely mmv1 paths for [type], best first, learned from the rows of
/// [mmSources] (tool/mm_yaml_sources.yaml): each `google_<x>_<resource>` row
/// maps the type prefix `google_<x>_` to its product, and [type] takes the
/// products of the two longest prefixes it starts with. Right for ~92% of
/// the committed rows; a miss becomes an `upstream: null` row that
/// tool/check_mm_upstream_fingerprint.dart flags when the type is MM-shaped.
@visibleForTesting
List<String> guessMmUpstreams(String type, String mmSources) {
  final files = (loadYaml(mmSources) as YamlMap)['files'] as YamlMap;
  final products = <String, Map<String, int>>{};
  for (final MapEntry(:key, :value) in files.entries) {
    final upstream = (value as YamlMap)['upstream'];
    final m = upstream is String ? _mmUpstream.firstMatch(upstream) : null;
    if (m == null) continue;
    final resource = _snake(m[2]!);
    final row = '$key';
    if (!row.endsWith('_$resource')) continue;
    final prefix = row.substring(0, row.length - resource.length);
    (products[prefix] ??= {}).update(m[1]!, (n) => n + 1, ifAbsent: () => 1);
  }
  final prefixes = [
    for (final prefix in products.keys)
      if (type.startsWith(prefix) && type.length > prefix.length) prefix,
  ]..sort((a, b) => b.length.compareTo(a.length));
  return [
    for (final prefix in prefixes.take(2))
      for (final product in (products[prefix]!.entries.toList()
            ..sort((a, b) => b.value.compareTo(a.value)))
          .take(2))
        'mmv1/products/${product.key}/'
            '${_camel(type.substring(prefix.length))}.yaml',
  ];
}

/// [mmSources] with a row for every entry of [upstreams] it lacks, inserted
/// before the data-source rows.
@visibleForTesting
String addMmSourceRows(String mmSources, Map<String, String?> upstreams) {
  final listed = ((loadYaml(mmSources) as YamlMap)['files'] as YamlMap).keys;
  final rows = StringBuffer();
  for (final MapEntry(key: type, value: upstream) in upstreams.entries) {
    if (listed.contains(type)) continue;
    rows
      ..writeln('  $type:')
      ..writeln(
        upstream == null
            ? '    upstream: null  # schema bump: no mmv1 YAML at the guessed '
                'paths; probe upstream by hand'
            : '    upstream: $upstream',
      );
  }
  if (rows.isEmpty) return mmSources;
  final at = mmSources.indexOf(RegExp(r'^  data_', multiLine: true));
  if (at < 0) return '${mmSources.trimRight()}\n$rows';
  return mmSources.replaceRange(at, at, '$rows');
}

/// Fetches [upstreamPath] from magic-modules main; null unless HTTP 200.
typedef MmFetch = Future<String?> Function(String upstreamPath);

Future<String?> _fetchMm(String upstreamPath) async {
  try {
    final r = await http.get(
      Uri.parse(
        'https://raw.githubusercontent.com/GoogleCloudPlatform/'
        'magic-modules/main/$upstreamPath',
      ),
    );
    return r.statusCode == 200 ? r.body : null;
  } on Exception {
    return null;
  }
}

/// Gives every type of [resources] a tool/mm_yaml_sources.yaml row (every
/// curated override needs one) and, when a guessed path resolves, its MM
/// fixture under [mmDir] — so wrap-init sees the MM hints.
@visibleForTesting
Future<Map<String, String?>> resolveMmUpstreams(
  List<String> resources, {
  required String mmSources,
  required String mmDir,
  MmFetch fetch = _fetchMm,
}) async {
  final out = <String, String?>{};
  for (final type in resources) {
    out[type] = null;
    for (final path in guessMmUpstreams(type, mmSources)) {
      final body = await fetch(path);
      if (body == null) continue;
      File(p.join(mmDir, '$type.yaml'))
        ..createSync(recursive: true)
        ..writeAsStringSync(body);
      out[type] = path;
      break;
    }
  }
  return out;
}

/// Every `outputDir` the override YAMLs under [overridesRoot] name.
Set<String> overrideBarrels(String overridesRoot) => {
      for (final f in Directory(overridesRoot).listSync().whereType<File>())
        if (f.path.endsWith('.yaml'))
          if (loadYaml(f.readAsStringSync()) case {'outputDir': final String d})
            d,
    };

/// [manifest] (a barrels manifest, `barrels:` last) with a placeholder
/// entry for every barrel of [barrels] it lacks, in key order. `wrap` fails
/// closed on a catalog barrel without an entry, so a new type in a new
/// service would otherwise stop the whole regenerate.
@visibleForTesting
String addMissingBarrels(String manifest, Set<String> barrels) {
  final existing =
      ((loadYaml(manifest) as YamlMap)['barrels'] as YamlMap).keys.toSet();
  final missing = barrels.difference(existing).toList()..sort();
  if (missing.isEmpty) return manifest;
  final lines = manifest.trimRight().split('\n');
  final start = lines.indexOf('barrels:');
  final key = RegExp(r'^  ([a-z0-9_]+):$');
  for (final barrel in missing) {
    var at = lines.length;
    for (var i = start + 1; i < lines.length; i++) {
      final m = key.firstMatch(lines[i]);
      if (m != null && m[1]!.compareTo(barrel) > 0) {
        at = i;
        break;
      }
    }
    lines.insertAll(at, [
      '  $barrel:',
      '    doc: |-',
      '      /// `$barrel` factories, added by the weekly schema bump.',
    ]);
  }
  return '${lines.join('\n')}\n';
}

/// One catalog entry: what the drift report and the ledgers name.
typedef CatalogFactory = ({String tfType, String className, String kind});

/// Every `CatalogEntry` in a `_catalog.g.dart` [source].
List<CatalogFactory> readCatalog(String source) => [
      for (final m in RegExp(
        r"tfType:\s*'([^']+)'[\s\S]*?className:\s*'([^']+)'[\s\S]*?"
        r'kind:\s*CatalogKind\.(\w+)',
      ).allMatches(source))
        (tfType: m[1]!, className: m[2]!, kind: m[3]!),
    ];

/// The added types of [diff] that [catalog] now lists, resources first.
@visibleForTesting
List<CatalogFactory> newFactories(
  Map<String, dynamic> diff,
  List<CatalogFactory> catalog,
) {
  final byKey = {for (final f in catalog) '${f.kind}:${f.tfType}': f};
  return [
    for (final (kind, key) in [
      ('resource', 'added_resources'),
      ('dataSource', 'added_data_sources'),
    ])
      for (final type in ((diff[key] as List?) ?? const []).cast<String>())
        if (byKey['$kind:$type'] case final f?) f,
  ];
}

/// [debtYaml] with an `awaiting-example:` line for every factory in
/// [factories] it does not list yet, under one section at the end.
@visibleForTesting
String appendAwaitingExampleDebt(
  String debtYaml, {
  required List<CatalogFactory> factories,
  required String source,
  required String providerVersion,
  required String detectedAt,
}) {
  final listed = {
    for (final line in debtYaml.split('\n'))
      if (!line.trimLeft().startsWith('#') && line.contains(':'))
        line.substring(0, line.indexOf(':')).trim(),
  };
  final lines = [
    for (final f in factories)
      if (!listed.contains(f.className))
        '${f.className}: $awaitingExampleToken ${f.tfType} '
            '${f.kind == 'dataSource' ? '(data source) ' : ''}'
            'added in $source $providerVersion (schema bump $detectedAt)',
  ];
  if (lines.isEmpty) return debtYaml;
  final b = StringBuffer(debtYaml.trimRight());
  if (!debtYaml.contains(_debtSectionHeader)) {
    b
      ..writeln()
      ..writeln()
      ..write(_debtSectionHeader);
  }
  b.writeln();
  lines.forEach(b.writeln);
  return b.toString();
}

Map<String, String> _flags(List<String> args) => {
      for (final a in args.skip(1))
        if (a.startsWith('--') && a.contains('='))
          a.substring(2, a.indexOf('=')): a.substring(a.indexOf('=') + 1),
    };

Never _usage() {
  stderr.writeln(
    'usage: dart tool/bump_new_factories.dart scaffold --lane=<name> '
    '--diff=<json> --out=<json>\n'
    '       dart tool/bump_new_factories.dart record --lane=<name> '
    '--diff=<json> --detected-at=<date> --provider-version=<v> --out=<json> '
    '[--example-generator-ok=false]',
  );
  exit(64);
}

Future<void> main(List<String> args) async {
  final command = args.isEmpty ? null : args.first;
  final flags = _flags(args);
  final laneName = flags['lane'];
  final diffPath = flags['diff'];
  final outPath = flags['out'];
  if (laneName == null || diffPath == null || outPath == null) _usage();
  final lane = parseBumpLanes(File(providersPath).readAsStringSync())
      .where((l) => l.lane.name == laneName)
      .firstOrNull;
  if (lane == null) {
    stderr.writeln('bump_new_factories: no bump lane "$laneName"');
    exit(64);
  }
  final diff =
      jsonDecode(File(diffPath).readAsStringSync()) as Map<String, dynamic>;
  switch (command) {
    case 'scaffold':
      exit(await _scaffold(lane, diff, outPath));
    case 'record':
      final detectedAt = flags['detected-at'];
      final version = flags['provider-version'];
      if (detectedAt == null || version == null) _usage();
      _record(
        lane,
        diff,
        outPath,
        detectedAt,
        version,
        exampleCovered: lane.exampleGenerator != null &&
            flags['example-generator-ok'] != 'false',
      );
    default:
      _usage();
  }
}

Future<int> _scaffold(
  BumpLane lane,
  Map<String, dynamic> diff,
  String outPath,
) async {
  List<String> added(String key) =>
      ((diff[key] as List?) ?? const []).cast<String>();
  final resources = added('added_resources');
  final dataSources =
      lane.dataSources ? added('added_data_sources') : <String>[];
  final ProcessResult? result;
  if (resources.isEmpty && dataSources.isEmpty) {
    result = null;
  } else if (lane.scaffold == 'wrap-init') {
    if (dataSources.isNotEmpty) {
      stderr.writeln('bump_new_factories: wrap-init scaffolds resources only');
      return 64;
    }
    if (lane.mm) {
      final sources = File(mmSourcesPath);
      final upstreams = await resolveMmUpstreams(
        resources,
        mmSources: sources.readAsStringSync(),
        mmDir: p.join(lane.lane.schemaDir, 'mm'),
      );
      print('MM upstreams: $upstreams');
      sources.writeAsStringSync(
        addMmSourceRows(sources.readAsStringSync(), upstreams),
      );
    }
    result = await Process.run(Platform.resolvedExecutable, [
      'tool/batch_wrap_init.dart',
      '--resources=${resources.join(',')}',
      '--source=${lane.lane.schemaDir}',
      '--output=${lane.lane.overridesRoot}',
      '--fill-param-order',
    ]);
  } else {
    result = await Process.run(
      Platform.resolvedExecutable,
      [
        'run',
        'tool/scaffold_lane_overrides.dart',
        '--provider',
        lane.lane.source,
      ],
      workingDirectory: codegenDir,
    );
  }
  final code = result?.exitCode ?? 0;
  var log =
      result == null ? 'no new types' : '${result.stdout}${result.stderr}';
  if (result != null && code == 0) {
    final manifest = File(lane.lane.barrelsManifest);
    final text = manifest.readAsStringSync();
    final next =
        addMissingBarrels(text, overrideBarrels(lane.lane.overridesRoot));
    if (next != text) {
      manifest.writeAsStringSync(next);
      log += '\nadded barrel entries to ${lane.lane.barrelsManifest}';
    }
  }
  print(log);
  File(outPath)
    ..createSync(recursive: true)
    ..writeAsStringSync(
      jsonEncode({
        'exit': code,
        'log_excerpt': code == 0
            ? ''
            : log.length > 2000
                ? log.substring(log.length - 2000)
                : log,
      }),
    );
  return code == 0 ? 0 : 1;
}

void _record(
  BumpLane lane,
  Map<String, dynamic> diff,
  String outPath,
  String detectedAt,
  String version, {
  required bool exampleCovered,
}) {
  final catalog = readCatalog(
    File(p.join(lane.lane.outputPackage, 'lib', 'src', '_catalog.g.dart'))
        .readAsStringSync(),
  );
  final factories = newFactories(diff, catalog);
  if (factories.isNotEmpty) {
    final backlog = File(curationBacklogPath);
    final text = backlog.readAsStringSync();
    backlog.writeAsStringSync(
      formatBacklogYaml(
        header: readBacklogHeader(text),
        entries: appendCurationEntries(
          existing: readBacklogEntries(text),
          resources: [
            for (final f in factories)
              if (f.kind == 'resource') f.tfType,
          ],
          dataSources: [
            for (final f in factories)
              if (f.kind == 'dataSource') f.tfType,
          ],
          detectedAt: detectedAt,
          providerVersion: version,
          note: generatedFactoryNote,
        ),
      ),
    );
    if (!exampleCovered) {
      final debt = File(exampleDebtPath);
      debt.writeAsStringSync(
        appendAwaitingExampleDebt(
          debt.readAsStringSync(),
          factories: factories,
          source: lane.lane.source,
          providerVersion: version,
          detectedAt: detectedAt,
        ),
      );
    }
  }
  print('bump_new_factories: ${factories.length} new factories'
      '${factories.isEmpty ? '' : ': ${factories.map((f) => f.className).join(', ')}'}');
  File(outPath)
    ..createSync(recursive: true)
    ..writeAsStringSync(
      jsonEncode({
        'example_generator': exampleCovered ? lane.exampleGenerator : null,
        'factories': [
          for (final f in factories)
            {'tf_type': f.tfType, 'class_name': f.className, 'kind': f.kind},
        ],
      }),
    );
}
