// doc_snippets.dart — compiles every ```dart fence in the README, the
// website docs, the package and cookbook READMEs, and the `///` doc comments
// of the published packages against the workspace packages, so a guide or a
// dartdoc page cannot show code the current release rejects.
//
// Run from repo root: dart tool/doc_snippets.dart
// tool/doc_snippets_test.dart runs the same check (CI: `dart test tool/`).
//
// Each document gets a sandbox package named `my_app` that depends on every
// provider package by path. Within it:
//
// - A fence whose first line is a path comment (`// lib/orders_stack.dart`)
//   is written to that path, so fences of one document can import each
//   other (`import 'generated/orders_stack.app.dart';`,
//   `import 'package:my_app/orders_stack.dart';`). Any other fence is
//   `lib/snippet_<n>.dart`.
// - A fence without directives imports every provider barrel, `dart:io`
//   and `dart:convert`.
// - A fence that starts with a statement rather than a declaration is the
//   body of a Stack constructor, so `add(...)`, `addOutput(...)` and
//   `outputEnvironment()` resolve.
// - `bin/*.dart` fences with a `main` run first, in document order, so a
//   synth writes the generated file the app fences import.
// - In a README, `<!-- doc-snippets: skip: <reason> -->` on the line before
//   a fence leaves it out — only for code that needs a package outside the
//   workspace (a cookbook recipe's Genkit server), which the recipe's own
//   build compiles (tool/check_cookbook.sh).
//
// Then one `dart analyze` checks every sandbox; an error or warning fails.
//
// Doc-comment fences share one sandbox per package, a file per fence. An
// example there shows one resource and may name a value it does not build
// (`instance: .ref(primary.nameRef)`): a lowerCamel name the fence leaves
// undefined becomes a `dynamic` stand-in, so the rest of the fence — class,
// parameter, enum and helper names — must still resolve. A doc-comment fence
// needs a language: dartdoc renders an unlabeled one as Dart, so a diagram
// is ```text.
// ignore_for_file: avoid_print

import 'dart:io';

import 'package:path/path.dart' as p;

/// The documents whose Dart fences must compile, relative to the repo root:
/// the README, the website docs, and the package and cookbook READMEs.
List<String> snippetDocuments(String root) {
  final docs = <String>['README.md'];
  for (final dir in ['packages', 'cookbook']) {
    final base = Directory(p.join(root, dir));
    if (!base.existsSync()) continue;
    docs.addAll(
      [
        for (final d in base.listSync().whereType<Directory>())
          if (File(p.join(d.path, 'README.md')).existsSync())
            p.relative(p.join(d.path, 'README.md'), from: root),
      ]..sort(),
    );
  }
  final site = Directory(p.join(root, 'website/src/content/docs'));
  if (site.existsSync()) {
    final pages = [
      for (final f in site.listSync(recursive: true).whereType<File>())
        if ((f.path.endsWith('.md') || f.path.endsWith('.mdx')) &&
            // Generated by tool/render_coverage_page.dart; it has no Dart.
            !f.path.endsWith('/coverage.md'))
          p.relative(f.path, from: root),
    ]..sort();
    docs.addAll(pages);
  }
  return docs;
}

/// A ```dart fence of a document.
final class Snippet {
  Snippet({required this.doc, required this.line, required this.code});

  /// The document, relative to the repo root.
  final String doc;

  /// The 1-based document line of the fence's first code line.
  final int line;

  final String code;

  /// The path the fence's first-line comment names, if any.
  String? get path {
    for (final raw in code.split('\n')) {
      final line = raw.trim();
      if (line.isEmpty || line.startsWith('// docs:pitch:')) continue;
      final m = RegExp(r'^//\s*([\w./-]+\.dart)\b').firstMatch(line);
      return m?.group(1);
    }
    return null;
  }

  bool get hasDirectives => RegExp(
    r'^\s*(import|export|library|part)\b',
    multiLine: true,
  ).hasMatch(code);

  /// Whether the first code line declares something (a class, a function, a
  /// top-level variable with a type) rather than running a statement.
  bool get isLibrary {
    if (hasDirectives) return true;
    for (final raw in code.split('\n')) {
      final line = raw.trim();
      if (line.isEmpty || line.startsWith('//')) continue;
      return _declaration.hasMatch(line);
    }
    return true;
  }

  static final _declaration = RegExp(
    r'^(@|(abstract |base |final |interface |sealed |mixin )*'
    r'(class|enum|mixin|extension|typedef)\b|'
    r'(Future|FutureOr|Stream|void|bool|int|double|num|String|List|Map|Set|'
    r'Iterable|Object|dynamic|[A-Z]\w*)(<[^>]*>)?\??\s+\w+\s*[({=;]|'
    r'(const|final|var|late)\s+[A-Z]\w*(<[^>]*>)?\??\s+\w+\s*=)',
  );
}

/// The ```dart fences of [text], the content of [doc].
List<Snippet> extractSnippets(String doc, String text) {
  final lines = text.split('\n');
  final out = <Snippet>[];
  final open = RegExp(r'^(\s*)(`{3,}|~{3,})dart\b');
  for (var i = 0; i < lines.length; i++) {
    final m = open.firstMatch(lines[i]);
    if (m == null) continue;
    final skip = i > 0 && _skip.firstMatch(lines[i - 1]) != null;
    final indent = m.group(1)!.length;
    final fence = m.group(2)!;
    final close = RegExp(
      '^\\s*${RegExp.escape(fence[0])}{${fence.length},}\\s*\$',
    );
    final body = <String>[];
    var j = i + 1;
    for (; j < lines.length && !close.hasMatch(lines[j]); j++) {
      final l = lines[j];
      body.add(
        l.length >= indent && l.substring(0, indent).trim().isEmpty
            ? l.substring(indent)
            : l.trimLeft(),
      );
    }
    if (!skip) out.add(Snippet(doc: doc, line: i + 2, code: body.join('\n')));
    i = j;
  }
  return out;
}

/// `<!-- doc-snippets: skip: <reason> -->` on the line before a fence; a
/// marker without a reason does not match.
final _skip = RegExp(r'^\s*<!--\s*doc-snippets:\s*skip:\s*\S.*-->\s*$');

/// The packages whose `///` doc comments are a user's dartdoc pages.
const docCommentPackages = [
  'terradart_core',
  'terradart_google',
  'terradart_google_beta',
  'terradart_aws',
  'terradart_cloudflare',
  'terradart_appwrite',
  'terradart_time',
  'terradart_hcl',
  'terradart_migrate',
];

/// The ```dart fences in the `///` doc comments of [file] ([text] its
/// content), and one message per fence that names no language.
({List<Snippet> snippets, List<String> unlabeled}) extractDocCommentSnippets(
  String file,
  String text,
) {
  final lines = text.split('\n');
  final snippets = <Snippet>[];
  final unlabeled = <String>[];
  final doc = RegExp(r'^\s*/// ?(.*)$');
  final open = RegExp(r'^(`{3,}|~{3,})\s*(\S*)');
  for (var i = 0; i < lines.length; i++) {
    final m = doc.firstMatch(lines[i]);
    if (m == null) continue;
    final o = open.firstMatch(m.group(1)!);
    if (o == null) continue;
    final fence = o.group(1)!;
    final language = o.group(2)!;
    final close = RegExp('^${RegExp.escape(fence[0])}{${fence.length},}\\s*\$');
    final body = <String>[];
    var j = i + 1;
    for (; j < lines.length; j++) {
      final d = doc.firstMatch(lines[j]);
      if (d == null || close.hasMatch(d.group(1)!)) break;
      body.add(d.group(1)!);
    }
    if (language.isEmpty) {
      unlabeled.add(
        '$file:${i + 1}: a doc-comment fence needs a language; dartdoc '
        'renders an unlabeled one as Dart (use ```text for a diagram)',
      );
    } else if (language == 'dart') {
      snippets.add(Snippet(doc: file, line: i + 2, code: body.join('\n')));
    }
    i = j;
  }
  return (snippets: snippets, unlabeled: unlabeled);
}

/// A sandbox file built from a [snippet], with [prefix] lines before the
/// snippet's first line.
final class SnippetFile {
  SnippetFile(this.path, this.contents, this.snippet, this.prefix);

  final String path;
  final String contents;
  final Snippet snippet;
  final int prefix;

  /// This file with a `dynamic` stand-in declared for each of [names],
  /// on one line before the snippet.
  SnippetFile withStandIns(Iterable<String> names) {
    final lines = contents.split('\n');
    lines.insert(prefix, 'dynamic ${names.join(', ')};');
    return SnippetFile(path, lines.join('\n'), snippet, prefix + 1);
  }

  /// The document line of sandbox line [line] (1-based).
  int docLine(int line) {
    final offset = line - 1 - prefix;
    final max = snippet.code.split('\n').length - 1;
    return snippet.line + offset.clamp(0, max);
  }
}

const _ignores =
    '// ignore_for_file: unused_import, unused_local_variable, '
    'unused_element, unused_field, dead_code';

const _barrels = [
  "import 'dart:convert';",
  "import 'dart:io';",
  "import 'package:terradart_core/terradart_core.dart';",
  "import 'package:terradart_google/terradart_google.dart';",
  "import 'package:terradart_google_beta/terradart_google_beta.dart';",
  "import 'package:terradart_aws/terradart_aws.dart';",
  "import 'package:terradart_cloudflare/terradart_cloudflare.dart';",
  "import 'package:terradart_appwrite/terradart_appwrite.dart';",
  "import 'package:terradart_time/terradart_time.dart';",
];

/// The sandbox file for the [index]-th fence of a document.
SnippetFile renderSnippet(Snippet s, int index) {
  final path = s.path ?? 'lib/snippet_$index.dart';
  final head = <String>[_ignores, if (!s.hasDirectives) ..._barrels];
  if (s.isLibrary) {
    return SnippetFile(path, '${head.join('\n')}\n${s.code}\n', s, head.length);
  }
  final open = [
    ...head,
    'final class _Snippet$index extends Stack {',
    '  _Snippet$index()',
    '    : super(',
    '        providers: const [],',
    "        appExports: AppExports('lib/generated/snippet_$index.app.dart'),",
    '      ) {',
  ];
  return SnippetFile(
    path,
    '${open.join('\n')}\n${s.code}\n  }\n}\n',
    s,
    open.length,
  );
}

const _packages = [
  'terradart_core',
  'terradart_google',
  'terradart_google_beta',
  'terradart_aws',
  'terradart_cloudflare',
  'terradart_appwrite',
  'terradart_time',
  'terradart_hcl',
  'terradart_migrate',
];

String _pubspec(String root) {
  final b = StringBuffer()
    ..writeln('name: my_app')
    ..writeln('publish_to: none')
    ..writeln('environment:')
    ..writeln('  sdk: ^3.10.0')
    ..writeln('dependencies:');
  for (final pkg in _packages) {
    b.writeln('  $pkg: any');
  }
  b.writeln('dependency_overrides:');
  for (final pkg in _packages) {
    b
      ..writeln('  $pkg:')
      ..writeln('    path: ${p.join(root, 'packages', pkg)}');
  }
  return b.toString();
}

/// One sandbox package: the fences of one document, or of one package's
/// doc comments ([standIns]).
typedef _Unit = ({String name, List<Snippet> snippets, bool standIns});

/// Compiles the Dart fences of [docs] (default: [snippetDocuments]) and of
/// the `///` doc comments under [libs] (default: the `lib/` of each of
/// [docCommentPackages]); returns one message per failure.
Future<List<String>> checkDocSnippets(
  String root, {
  List<String>? docs,
  List<String>? libs,
}) async {
  docs ??= snippetDocuments(root);
  libs ??= [for (final pkg in docCommentPackages) 'packages/$pkg/lib'];
  final failures = <String>[];
  final units = <_Unit>[
    for (final doc in docs)
      (
        name: doc,
        snippets: extractSnippets(
          doc,
          File(p.join(root, doc)).readAsStringSync(),
        ),
        standIns: false,
      ),
  ];
  for (final dir in libs) {
    final lib = Directory(p.join(root, dir));
    if (!lib.existsSync()) continue;
    final snippets = <Snippet>[];
    final files = [
      for (final f in lib.listSync(recursive: true).whereType<File>())
        if (f.path.endsWith('.dart')) f,
    ]..sort((a, b) => a.path.compareTo(b.path));
    for (final f in files) {
      final found = extractDocCommentSnippets(
        p.relative(f.path, from: root),
        f.readAsStringSync(),
      );
      snippets.addAll(found.snippets);
      failures.addAll(found.unlabeled);
    }
    units.add((name: dir, snippets: snippets, standIns: true));
  }

  final sandbox = await Directory.systemTemp.createTemp('doc_snippets_');
  try {
    final files = <String, SnippetFile>{};
    final standInFiles = <String>{};
    final runs = <(String, String, Snippet)>[];
    final dirs = <String>[];
    for (final unit in units) {
      if (unit.snippets.isEmpty) continue;
      final dir = p.join(
        sandbox.path,
        unit.name.replaceAll(RegExp(r'[^\w]+'), '_').toLowerCase(),
      );
      dirs.add(dir);
      Directory(dir).createSync(recursive: true);
      File(p.join(dir, 'pubspec.yaml')).writeAsStringSync(_pubspec(root));
      for (final (i, s) in unit.snippets.indexed) {
        var f = renderSnippet(s, i + 1);
        if (unit.standIns && !s.isLibrary) {
          final shadowed = stackMembers.where((m) => _readsUndeclared(s, m));
          if (shadowed.isNotEmpty) f = f.withStandIns(shadowed);
        }
        final out = File(p.join(dir, f.path));
        if (out.existsSync()) {
          failures.add(
            '${s.doc}:${s.line}: a second fence names ${f.path}; give each '
            'fence its own path',
          );
          continue;
        }
        out
          ..createSync(recursive: true)
          ..writeAsStringSync(f.contents);
        final key = p.canonicalize(out.path);
        files[key] = f;
        if (unit.standIns) standInFiles.add(key);
        if (f.path.startsWith('bin/') &&
            RegExp(r'\bmain\s*\(').hasMatch(s.code)) {
          runs.add((dir, f.path, s));
        }
      }
    }
    for (final dir in dirs) {
      var get = await Process.run('dart', [
        'pub',
        'get',
        '--offline',
      ], workingDirectory: dir);
      if (get.exitCode != 0) {
        get = await Process.run('dart', ['pub', 'get'], workingDirectory: dir);
      }
      if (get.exitCode != 0) {
        failures.add('dart pub get failed in $dir:\n${get.stderr}');
        return failures;
      }
    }
    for (final (dir, path, s) in runs) {
      final run = await Process.run('dart', [
        'run',
        path,
      ], workingDirectory: dir);
      if (run.exitCode != 0) {
        failures.add(
          '${s.doc}:${s.line}: `dart run $path` failed:\n'
          '${run.stdout}${run.stderr}',
        );
      }
    }

    var diagnostics = await _analyze(sandbox.path);
    // A lowerCamel name a doc-comment fence leaves undefined stands for a
    // value the example does not build; declare it and analyze again.
    final undefined = <String, Set<String>>{};
    for (final d in diagnostics) {
      if (!standInFiles.contains(d.file)) continue;
      if (d.code != 'UNDEFINED_IDENTIFIER' && d.code != 'UNDEFINED_FUNCTION') {
        continue;
      }
      final name = RegExp(r"'([a-z_]\w*)'").firstMatch(d.message)?.group(1);
      if (name != null) undefined.putIfAbsent(d.file, () => {}).add(name);
    }
    if (undefined.isNotEmpty) {
      for (final MapEntry(key: path, value: names) in undefined.entries) {
        final f = files[path]!.withStandIns(names.toList()..sort());
        files[path] = f;
        File(path).writeAsStringSync(f.contents);
      }
      diagnostics = await _analyze(sandbox.path);
    }

    for (final d in diagnostics) {
      if (d.severity != 'ERROR' && d.severity != 'WARNING') continue;
      final message = '${d.message} (${d.code})';
      final file = files[d.file];
      if (file == null) {
        failures.add('${d.file}:${d.line}: $message');
        continue;
      }
      failures.add('${file.snippet.doc}:${file.docLine(d.line)}: $message');
    }
  } finally {
    sandbox.deleteSync(recursive: true);
  }
  return failures;
}

/// The getters of `Stack`. A doc-comment fence that reads one of these names
/// without declaring it means a value of its own (`backend.backendIdRef`),
/// not the member the Stack-body wrapper would resolve it to.
const stackMembers = [
  'appExports',
  'backend',
  'constants',
  'dataSources',
  'devMode',
  'externalBlocks',
  'externalVariables',
  'modules',
  'moved',
  'outputs',
  'providers',
  'requiredVersion',
  'resources',
  'variables',
];

bool _readsUndeclared(Snippet s, String name) {
  final read = RegExp('(?<![\\w.\$\'"])$name(?![\\w\$]|\\s*:)');
  final declared = RegExp(
    '\\b(final|var|const|late)\\s+([\\w<>?, ]+\\s+)?$name\\s*[=;]',
  );
  return read.hasMatch(s.code) && !declared.hasMatch(s.code);
}

typedef _Diagnostic = ({
  String severity,
  String code,
  String file,
  int line,
  String message,
});

/// The machine-format diagnostics of `dart analyze` over [dir].
Future<List<_Diagnostic>> _analyze(String dir) async {
  final analyze = await Process.run('dart', [
    'analyze',
    '--format=machine',
    dir,
  ], workingDirectory: dir);
  final out = <_Diagnostic>[];
  for (final line in '${analyze.stdout}\n${analyze.stderr}'.split('\n')) {
    final parts = line.split('|');
    if (parts.length < 8) continue;
    out.add((
      severity: parts[0],
      code: parts[2],
      file: p.canonicalize(parts[3]),
      line: int.parse(parts[4]),
      message: parts.sublist(7).join('|'),
    ));
  }
  if (analyze.exitCode != 0 && out.isEmpty) {
    throw StateError(
      'dart analyze failed:\n${analyze.stdout}${analyze.stderr}',
    );
  }
  return out;
}

Future<void> main() async {
  final root = Directory.current.path;
  final docs = snippetDocuments(root);
  final failures = await checkDocSnippets(root, docs: docs);
  if (failures.isEmpty) {
    print(
      'doc_snippets: OK (${docs.length} documents, doc comments of '
      '${docCommentPackages.length} packages)',
    );
    return;
  }
  stderr.writeln('doc_snippets: FAILED');
  for (final f in failures) {
    stderr.writeln('  - $f');
  }
  exit(1);
}
