// doc_snippets.dart — compiles every ```dart fence in the README and the
// website docs against the workspace packages, so a guide cannot show code
// the current release rejects.
//
// Run from repo root: dart tool/doc_snippets.dart
// tool/doc_snippets_test.dart runs the same check (CI: `dart test tool/`).
//
// Each document gets a sandbox package named `my_app` that depends on every
// provider package by path. Within it:
//
// - A fence whose first line is a path comment (`// lib/orders_stack.dart`)
//   is written to that path, so fences of one document can import each
//   other (`import 'generated/orders_stack.app.dart';`,
//   `import 'package:my_app/orders_stack.dart';`). Any other fence is
//   `lib/snippet_<n>.dart`.
// - A fence without directives imports every provider barrel, `dart:io`
//   and `dart:convert`.
// - A fence that starts with a statement rather than a declaration is the
//   body of a Stack constructor, so `add(...)`, `addOutput(...)` and
//   `outputEnvironment()` resolve.
// - `bin/*.dart` fences with a `main` run first, in document order, so a
//   synth writes the generated file the app fences import.
//
// Then one `dart analyze` checks every sandbox; an error or warning fails.
// ignore_for_file: avoid_print

import 'dart:io';

import 'package:path/path.dart' as p;

/// The documents whose Dart fences must compile, relative to the repo root.
List<String> snippetDocuments(String root) {
  final docs = <String>['README.md'];
  final site = Directory(p.join(root, 'website/src/content/docs'));
  if (site.existsSync()) {
    final pages = [
      for (final f in site.listSync(recursive: true).whereType<File>())
        if ((f.path.endsWith('.md') || f.path.endsWith('.mdx')) &&
            // Generated by tool/render_coverage_page.dart; it has no Dart.
            !f.path.endsWith('/coverage.md'))
          p.relative(f.path, from: root),
    ]..sort();
    docs.addAll(pages);
  }
  return docs;
}

/// A ```dart fence of a document.
final class Snippet {
  Snippet({required this.doc, required this.line, required this.code});

  /// The document, relative to the repo root.
  final String doc;

  /// The 1-based document line of the fence's first code line.
  final int line;

  final String code;

  /// The path the fence's first-line comment names, if any.
  String? get path {
    for (final raw in code.split('\n')) {
      final line = raw.trim();
      if (line.isEmpty || line.startsWith('// docs:pitch:')) continue;
      final m = RegExp(r'^//\s*([\w./-]+\.dart)\b').firstMatch(line);
      return m?.group(1);
    }
    return null;
  }

  bool get hasDirectives => RegExp(
    r'^\s*(import|export|library|part)\b',
    multiLine: true,
  ).hasMatch(code);

  /// Whether the first code line declares something (a class, a function, a
  /// top-level variable with a type) rather than running a statement.
  bool get isLibrary {
    if (hasDirectives) return true;
    for (final raw in code.split('\n')) {
      final line = raw.trim();
      if (line.isEmpty || line.startsWith('//')) continue;
      return _declaration.hasMatch(line);
    }
    return true;
  }

  static final _declaration = RegExp(
    r'^(@|(abstract |base |final |interface |sealed |mixin )*'
    r'(class|enum|mixin|extension|typedef)\b|'
    r'(Future|FutureOr|Stream|void|bool|int|double|num|String|List|Map|Set|'
    r'Iterable|Object|dynamic|[A-Z]\w*)(<[^>]*>)?\??\s+\w+\s*[({=;]|'
    r'(const|final|var|late)\s+[A-Z]\w*(<[^>]*>)?\??\s+\w+\s*=)',
  );
}

/// The ```dart fences of [text], the content of [doc].
List<Snippet> extractSnippets(String doc, String text) {
  final lines = text.split('\n');
  final out = <Snippet>[];
  final open = RegExp(r'^(\s*)(`{3,}|~{3,})dart\b');
  for (var i = 0; i < lines.length; i++) {
    final m = open.firstMatch(lines[i]);
    if (m == null) continue;
    final indent = m.group(1)!.length;
    final fence = m.group(2)!;
    final close = RegExp(
      '^\\s*${RegExp.escape(fence[0])}{${fence.length},}\\s*\$',
    );
    final body = <String>[];
    var j = i + 1;
    for (; j < lines.length && !close.hasMatch(lines[j]); j++) {
      final l = lines[j];
      body.add(
        l.length >= indent && l.substring(0, indent).trim().isEmpty
            ? l.substring(indent)
            : l.trimLeft(),
      );
    }
    out.add(Snippet(doc: doc, line: i + 2, code: body.join('\n')));
    i = j;
  }
  return out;
}

/// A sandbox file built from a [snippet], with [prefix] lines before the
/// snippet's first line.
final class SnippetFile {
  SnippetFile(this.path, this.contents, this.snippet, this.prefix);

  final String path;
  final String contents;
  final Snippet snippet;
  final int prefix;

  /// The document line of sandbox line [line] (1-based).
  int docLine(int line) {
    final offset = line - 1 - prefix;
    final max = snippet.code.split('\n').length - 1;
    return snippet.line + offset.clamp(0, max);
  }
}

const _ignores =
    '// ignore_for_file: unused_import, unused_local_variable, '
    'unused_element, unused_field, dead_code';

const _barrels = [
  "import 'dart:convert';",
  "import 'dart:io';",
  "import 'package:terradart_core/terradart_core.dart';",
  "import 'package:terradart_google/terradart_google.dart';",
  "import 'package:terradart_google_beta/terradart_google_beta.dart';",
  "import 'package:terradart_aws/terradart_aws.dart';",
  "import 'package:terradart_cloudflare/terradart_cloudflare.dart';",
  "import 'package:terradart_appwrite/terradart_appwrite.dart';",
  "import 'package:terradart_time/terradart_time.dart';",
];

/// The sandbox file for the [index]-th fence of a document.
SnippetFile renderSnippet(Snippet s, int index) {
  final path = s.path ?? 'lib/snippet_$index.dart';
  final head = <String>[_ignores, if (!s.hasDirectives) ..._barrels];
  if (s.isLibrary) {
    return SnippetFile(path, '${head.join('\n')}\n${s.code}\n', s, head.length);
  }
  final open = [
    ...head,
    'final class _Snippet$index extends Stack {',
    '  _Snippet$index()',
    '    : super(',
    '        providers: const [],',
    "        appExports: AppExports('lib/generated/snippet_$index.app.dart'),",
    '      ) {',
  ];
  return SnippetFile(
    path,
    '${open.join('\n')}\n${s.code}\n  }\n}\n',
    s,
    open.length,
  );
}

const _packages = [
  'terradart_core',
  'terradart_google',
  'terradart_google_beta',
  'terradart_aws',
  'terradart_cloudflare',
  'terradart_appwrite',
  'terradart_time',
  'terradart_hcl',
];

String _pubspec(String root) {
  final b = StringBuffer()
    ..writeln('name: my_app')
    ..writeln('publish_to: none')
    ..writeln('environment:')
    ..writeln('  sdk: ^3.10.0')
    ..writeln('dependencies:');
  for (final pkg in _packages) {
    b.writeln('  $pkg: any');
  }
  b.writeln('dependency_overrides:');
  for (final pkg in _packages) {
    b
      ..writeln('  $pkg:')
      ..writeln('    path: ${p.join(root, 'packages', pkg)}');
  }
  return b.toString();
}

/// Compiles the Dart fences of [docs] (default: [snippetDocuments]) and
/// returns one message per failure.
Future<List<String>> checkDocSnippets(String root, {List<String>? docs}) async {
  docs ??= snippetDocuments(root);
  final failures = <String>[];
  final sandbox = await Directory.systemTemp.createTemp('doc_snippets_');
  try {
    final files = <String, SnippetFile>{};
    final runs = <(String, String, Snippet)>[];
    final dirs = <String>[];
    for (final doc in docs) {
      final snippets = extractSnippets(
        doc,
        File(p.join(root, doc)).readAsStringSync(),
      );
      if (snippets.isEmpty) continue;
      final dir = p.join(
        sandbox.path,
        doc.replaceAll(RegExp(r'[^\w]+'), '_').toLowerCase(),
      );
      dirs.add(dir);
      Directory(dir).createSync(recursive: true);
      File(p.join(dir, 'pubspec.yaml')).writeAsStringSync(_pubspec(root));
      for (final (i, s) in snippets.indexed) {
        final f = renderSnippet(s, i + 1);
        final out = File(p.join(dir, f.path));
        if (out.existsSync()) {
          failures.add(
            '${s.doc}:${s.line}: a second fence names ${f.path}; give each '
            'fence its own path',
          );
          continue;
        }
        out
          ..createSync(recursive: true)
          ..writeAsStringSync(f.contents);
        files[p.canonicalize(out.path)] = f;
        if (f.path.startsWith('bin/') &&
            RegExp(r'\bmain\s*\(').hasMatch(s.code)) {
          runs.add((dir, f.path, s));
        }
      }
    }
    for (final dir in dirs) {
      var get = await Process.run('dart', [
        'pub',
        'get',
        '--offline',
      ], workingDirectory: dir);
      if (get.exitCode != 0) {
        get = await Process.run('dart', ['pub', 'get'], workingDirectory: dir);
      }
      if (get.exitCode != 0) {
        failures.add('dart pub get failed in $dir:\n${get.stderr}');
        return failures;
      }
    }
    for (final (dir, path, s) in runs) {
      final run = await Process.run('dart', [
        'run',
        path,
      ], workingDirectory: dir);
      if (run.exitCode != 0) {
        failures.add(
          '${s.doc}:${s.line}: `dart run $path` failed:\n'
          '${run.stdout}${run.stderr}',
        );
      }
    }
    final analyze = await Process.run('dart', [
      'analyze',
      '--format=machine',
      sandbox.path,
    ], workingDirectory: sandbox.path);
    for (final line in '${analyze.stdout}\n${analyze.stderr}'.split('\n')) {
      final parts = line.split('|');
      if (parts.length < 8) continue;
      final severity = parts[0];
      if (severity != 'ERROR' && severity != 'WARNING') continue;
      final file = files[p.canonicalize(parts[3])];
      final message = '${parts.sublist(7).join('|')} (${parts[2]})';
      if (file == null) {
        failures.add('${parts[3]}:${parts[4]}: $message');
        continue;
      }
      final at = file.docLine(int.parse(parts[4]));
      failures.add('${file.snippet.doc}:$at: $message');
    }
    if (analyze.exitCode != 0 &&
        failures.isEmpty &&
        !'${analyze.stdout}'.contains('|')) {
      failures.add('dart analyze failed:\n${analyze.stdout}${analyze.stderr}');
    }
  } finally {
    sandbox.deleteSync(recursive: true);
  }
  return failures;
}

Future<void> main() async {
  final root = Directory.current.path;
  final docs = snippetDocuments(root);
  final failures = await checkDocSnippets(root, docs: docs);
  if (failures.isEmpty) {
    print('doc_snippets: OK (${docs.length} documents)');
    return;
  }
  stderr.writeln('doc_snippets: FAILED');
  for (final f in failures) {
    stderr.writeln('  - $f');
  }
  exit(1);
}
