// tool/generate_drift_report.dart
//
// Aggregates structured inputs (provided as files in --inputs-dir) into a
// Markdown drift report. The report is the body of the weekly schema-bump PR.
//
// Usage:
//   dart tool/generate_drift_report.dart \
//     --inputs-dir=/tmp/schema-bump \
//     --out=.schema-bump/drift_report.md
//
// Input layout (see plan Task 4.1):
//   state.json, wrap_check.txt, wrap_check_exit, gates.txt, gates_exit,
//   mm_yaml_sync.json, schema_diff.json
//
// Exit codes:
//   0 report generated (regardless of whether drift was present)
//   64 usage error
//   65 missing or unreadable input file

import 'dart:convert';
import 'dart:io';

import 'package:meta/meta.dart';

const _exitUsage = 64;
const _exitMissingInput = 65;

Future<void> main(List<String> args) async {
  final parsed = _parseArgs(args);
  if (parsed == null) {
    stderr.writeln(
      'Usage: dart tool/generate_drift_report.dart '
      '--inputs-dir=<path> --out=<path>',
    );
    exit(_exitUsage);
  }
  final ReportInputs inputs;
  try {
    inputs = readInputs(parsed.inputsDir);
  } catch (e) {
    stderr.writeln('Cannot read inputs: $e');
    exit(_exitMissingInput);
  }
  final md = buildReport(inputs);
  final outFile = File(parsed.outPath)
    ..createSync(recursive: true)
    ..writeAsStringSync(md);
  stdout.writeln('drift report written: ${outFile.path}');
}

class _Args {
  _Args(this.inputsDir, this.outPath);
  final String inputsDir;
  final String outPath;
}

_Args? _parseArgs(List<String> args) {
  String? inputs;
  String? out;
  for (final a in args) {
    if (a.startsWith('--inputs-dir=')) {
      inputs = a.substring('--inputs-dir='.length);
    } else if (a.startsWith('--out=')) {
      out = a.substring('--out='.length);
    }
  }
  if (inputs == null || out == null) return null;
  return _Args(inputs, out);
}

@visibleForTesting
class ReportInputs {
  ReportInputs({
    required this.state,
    required this.wrapCheckStdout,
    required this.wrapCheckExitCode,
    required this.gatesStdout,
    required this.gatesExitCode,
    required this.mmYamlSync,
    required this.schemaDiff,
  });
  final Map<String, dynamic> state;
  final String wrapCheckStdout;
  final int wrapCheckExitCode;
  final String gatesStdout;
  final int gatesExitCode;
  final Map<String, dynamic> mmYamlSync;
  final Map<String, dynamic> schemaDiff;
}

@visibleForTesting
ReportInputs readInputs(String dir) {
  final state = jsonDecode(File('$dir/state.json').readAsStringSync())
      as Map<String, dynamic>;
  final wrapCheck = File('$dir/wrap_check.txt').readAsStringSync();
  final wrapCheckExit = int.parse(
    File('$dir/wrap_check_exit').readAsStringSync().trim(),
  );
  final gates = File('$dir/gates.txt').readAsStringSync();
  final gatesExit = int.parse(
    File('$dir/gates_exit').readAsStringSync().trim(),
  );
  final mm = jsonDecode(File('$dir/mm_yaml_sync.json').readAsStringSync())
      as Map<String, dynamic>;
  final schema = jsonDecode(File('$dir/schema_diff.json').readAsStringSync())
      as Map<String, dynamic>;
  return ReportInputs(
    state: state,
    wrapCheckStdout: wrapCheck,
    wrapCheckExitCode: wrapCheckExit,
    gatesStdout: gates,
    gatesExitCode: gatesExit,
    mmYamlSync: mm,
    schemaDiff: schema,
  );
}

@visibleForTesting
String buildReport(ReportInputs i) {
  final b = StringBuffer();
  final banner = buildV8Banner(i);
  if (banner != null) {
    b.writeln(banner);
    b.writeln();
    b.writeln('---');
    b.writeln();
  }
  b.writeln('# Schema bump — ${i.state['bump_date']}');
  b.writeln();
  b.writeln(buildSummaryTable(i));
  b.writeln();
  b.writeln(buildSchemaSection(i));
  b.writeln();
  b.writeln(buildMmYamlSection(i));
  b.writeln();
  b.writeln(buildDivergenceSection(i));
  b.writeln();
  b.writeln(buildGateSection(i));
  b.writeln();
  b.writeln(buildNewResourceSection(i));
  b.writeln();
  b.writeln(buildRemovedResourceSection(i));
  b.writeln();
  b.writeln('---');
  b.writeln();
  b.writeln(
    'Generated by `.github/workflows/schema-bump.yml`. '
    'Source: `tool/generate_drift_report.dart`.',
  );
  return b.toString();
}

@visibleForTesting
String? buildV8Banner(ReportInputs i) {
  if (i.state['v8_available'] != true) return null;
  final maxMajor = i.state['max_major_version'] ?? 'unknown';
  return '> ⚠️ **NEW MAJOR AVAILABLE**: `hashicorp/google` v$maxMajor exists.\n'
      '>\n'
      '> Plan 5.E does NOT auto-bump across majors — per `_provider_meta.dart`:\n'
      '> "bump `~> 8.0` only after a curated-surface regression sweep."\n'
      '>\n'
      '> Action: open a separate planning issue when ready to absorb v$maxMajor.';
}

@visibleForTesting
String buildSummaryTable(ReportInputs i) {
  final v7Current = i.state['v7_current'] ?? 'unknown';
  final v7Latest = i.state['v7_latest'] ?? v7Current;
  final mmChanged = (i.mmYamlSync['changed'] as List?)?.length ?? 0;
  final wrapStatus = i.wrapCheckExitCode == 0 ? '✅ clean' : '⚠️ divergence';
  final gatesStatus = i.gatesExitCode == 0 ? '✅ all pass' : '❌ failures';
  final newResources = (i.schemaDiff['added_resources'] as List?)?.length ?? 0;
  final removedResources =
      (i.schemaDiff['removed_resources'] as List?)?.length ?? 0;
  return '## Summary\n\n'
      '| Source | Status |\n'
      '|---|---|\n'
      '| `hashicorp/google` v7 | $v7Current → **$v7Latest** |\n'
      '| magic-modules | **$mmChanged files updated** |\n'
      '| `terradart wrap --check` | $wrapStatus |\n'
      '| 6 universal QA gates | $gatesStatus |\n'
      '| New `google_*` resources | **$newResources detected** |\n'
      '| Removed curated resources | ${removedResources == 0 ? "✅ none" : "⚠️ $removedResources"} |';
}

@visibleForTesting
String buildSchemaSection(ReportInputs i) {
  final v7Current = i.state['v7_current'] ?? 'unknown';
  final v7Latest = i.state['v7_latest'] ?? v7Current;
  return '## Provider schema diff ($v7Current → $v7Latest)\n\n'
      '- See full schema diff in the PR file diff for '
      '`packages/terradart_codegen/test/fixtures/wrap/source/schema.json`.';
}

@visibleForTesting
String buildMmYamlSection(ReportInputs i) {
  final changed = (i.mmYamlSync['changed'] as List?) ?? [];
  final failed = (i.mmYamlSync['failed'] as List?) ?? [];
  if (changed.isEmpty && failed.isEmpty) {
    return '## MM YAML updates\n\n- ✅ no upstream changes since last sync.';
  }
  final b = StringBuffer('## MM YAML updates (${changed.length} files)\n\n');
  if (changed.isNotEmpty) {
    b.writeln('| File | Upstream URL |');
    b.writeln('|---|---|');
    for (final c in changed) {
      final m = c as Map<String, dynamic>;
      b.writeln('| `${m['file']}` | <${m['upstream_url']}> |');
    }
  }
  if (failed.isNotEmpty) {
    b.writeln();
    b.writeln('### ⚠️ Sync failures');
    for (final f in failed) {
      final m = f as Map<String, dynamic>;
      b.writeln('- `${m['file']}` — ${m['reason']}');
    }
  }
  return b.toString().trimRight();
}

@visibleForTesting
String buildDivergenceSection(ReportInputs i) {
  if (i.wrapCheckExitCode == 0) {
    return '## ✅ `terradart wrap --check`\n\n'
        'All wrappers byte-identical with emitter output.';
  }
  return '## ⚠️ `terradart wrap --check` divergence\n\n'
      'The wrap CLI output no longer matches committed wrappers. Likely\n'
      'caused by upstream schema or MM YAML changes. Review and either\n'
      're-run `terradart wrap` locally, or adjust `wrapper_overrides/yaml/`\n'
      'overrides.\n\n'
      '```\n'
      '${_truncate(i.wrapCheckStdout, 8000)}\n'
      '```';
}

@visibleForTesting
String buildGateSection(ReportInputs i) {
  if (i.gatesExitCode == 0) {
    return '## ✅ Universal QA gates (6/6 pass)';
  }
  return '## ❌ Universal QA gates failures\n\n'
      '```\n'
      '${_truncate(i.gatesStdout, 8000)}\n'
      '```';
}

@visibleForTesting
String buildNewResourceSection(ReportInputs i) {
  final added = (i.schemaDiff['added_resources'] as List?) ?? [];
  if (added.isEmpty) {
    return '## 🆕 New `google_*` resources\n\n- ✅ none in this bump.';
  }
  final b = StringBuffer(
    '## 🆕 New `google_*` resources (${added.length} detected)\n\n',
  );
  for (final r in added) {
    b.writeln('- `$r`');
  }
  b.writeln();
  b.writeln(
    'These entries have been appended to `tool/curation_backlog.yaml` '
    'for tracking.',
  );
  return b.toString().trimRight();
}

@visibleForTesting
String buildRemovedResourceSection(ReportInputs i) {
  final removed = (i.schemaDiff['removed_resources'] as List?) ?? [];
  if (removed.isEmpty) {
    return '## ✅ Removed curated resources\n\n- none detected.';
  }
  final b = StringBuffer(
    '## ⚠️ Removed curated resources (${removed.length})\n\n',
  );
  b.writeln(
    'These resources existed in the previous schema but are gone in the new '
    'one. If any are curated, the wrapper will break:',
  );
  b.writeln();
  for (final r in removed) {
    b.writeln('- `$r`');
  }
  return b.toString().trimRight();
}

String _truncate(String s, int max) {
  if (s.length <= max) return s;
  return '${s.substring(0, max)}\n... (truncated)';
}
