import 'package:test/test.dart';

import 'render_coverage_page.dart';

void main() {
  const catalog = [
    (
      tfType: 'google_pubsub_topic',
      className: 'GooglePubsubTopic',
      barrel: 'pubsub',
      kind: 'resource',
    ),
    (
      tfType: 'google_dns_policy',
      className: 'GoogleDnsPolicy',
      barrel: 'dns',
      kind: 'resource',
    ),
    (
      tfType: 'google_dns_record_set',
      className: 'GoogleDnsRecordSet',
      barrel: 'dns',
      kind: 'resource',
    ),
  ];

  test(
    'buildRows joins example back-references and sorts by barrel then tfType',
    () {
      final rows = buildRows(
        catalog: catalog,
        tfTypeToExamples: {
          'resource:google_pubsub_topic': [
            'pubsub_quickstart',
            'eventarc_quickstart',
          ],
          'resource:google_dns_policy': ['dns_quickstart'],
        },
      );
      expect(rows.first.barrel, 'dns');
      expect(rows.first.tfType, 'google_dns_policy');
      expect(rows.first.examples, ['dns_quickstart']);
      expect(
        rows[1].examples,
        isEmpty,
        reason: 'record_set appears in no tf-out',
      );
      expect(rows.last.examples, [
        'eventarc_quickstart',
        'pubsub_quickstart',
      ], reason: 'example lists are sorted');
    },
  );

  const provider = (
    slug: 'google',
    title: 'Google Cloud',
    package: 'terradart_google',
    source: 'hashicorp/google',
    catalog: catalog,
  );

  test('renderProviderPage emits marker, frontmatter, counts phrase, '
      'import line, barrel anchors, and rows', () {
    final md = renderProviderPage(
      provider: provider,
      rows: buildRows(
        catalog: catalog,
        tfTypeToExamples: {
          'resource:google_dns_policy': ['dns_quickstart'],
        },
      ),
    );
    expect(md, contains('<!-- GENERATED by tool/render_coverage_page.dart'));
    expect(md, contains('title: Google Cloud coverage'));
    expect(
      md,
      contains(
        '**3 curated resource factories + 0 data sources (3 catalog '
        'entries)**, 1 of them in a runnable example',
      ),
    );
    expect(md, contains("`import 'package:terradart_google/<barrel>.dart';`"));
    expect(md, contains('## dns'));
    expect(md, contains('- [`dns`](#dns)'));
    expect(md, contains('| `google_dns_policy` | `GoogleDnsPolicy` |'));
    expect(md, contains('Release history'));
  });

  test('countsPhrase uses the singular for one data source', () {
    final rows = buildRows(
      catalog: [
        ...catalog,
        (
          tfType: 'google_project',
          className: 'DataGoogleProject',
          barrel: 'data',
          kind: 'dataSource',
        ),
      ],
      tfTypeToExamples: const {},
    );
    expect(
      countsPhrase(rows),
      '3 curated resource factories + 1 data source (4 catalog entries)',
    );
  });

  test('renderPages renders an overview row and a page per provider', () {
    final pages = renderPages(const {});
    expect(pages.keys, ['index.md', for (final p in providers) '${p.slug}.md']);
    for (final p in providers) {
      expect(pages['index.md'], contains('(/docs/coverage/${p.slug}/)'));
      expect(pages['${p.slug}.md'], contains('`${p.package}` wraps'));
    }
    expect(
      providers.map((p) => p.package),
      containsAll([
        'terradart_google',
        'terradart_google_beta',
        'terradart_aws',
        'terradart_cloudflare',
        'terradart_appwrite',
      ]),
    );
  });

  test('resource / data-source twins do not share example back-references', () {
    const twins = [
      (
        tfType: 'google_compute_network',
        className: 'GoogleComputeNetwork',
        barrel: 'compute',
        kind: 'resource',
      ),
      (
        tfType: 'google_compute_network',
        className: 'DataGoogleComputeNetwork',
        barrel: 'data',
        kind: 'dataSource',
      ),
    ];
    final rows = buildRows(
      catalog: twins,
      tfTypeToExamples: {
        'resource:google_compute_network': ['compute_quickstart'],
        'dataSource:google_compute_network': [
          'data_source_leftover_quickstart',
        ],
      },
    );
    expect(rows[0].className, 'GoogleComputeNetwork');
    expect(rows[0].examples, ['compute_quickstart']);
    expect(rows[1].className, 'DataGoogleComputeNetwork');
    expect(rows[1].examples, ['data_source_leftover_quickstart']);
  });

  test('render is deterministic across input permutations', () {
    final a = renderProviderPage(
      provider: provider,
      rows: buildRows(catalog: catalog, tfTypeToExamples: const {}),
    );
    final b = renderProviderPage(
      provider: provider,
      rows: buildRows(
        catalog: catalog.reversed.toList(),
        tfTypeToExamples: const {},
      ),
    );
    expect(a, b);
  });
}
