import 'package:test/test.dart';

import 'render_coverage_page.dart';

void main() {
  const catalog = [
    (
      tfType: 'google_pubsub_topic',
      className: 'GooglePubsubTopic',
      barrel: 'pubsub',
      kind: 'resource',
    ),
    (
      tfType: 'google_dns_policy',
      className: 'GoogleDnsPolicy',
      barrel: 'dns',
      kind: 'resource',
    ),
    (
      tfType: 'google_dns_record_set',
      className: 'GoogleDnsRecordSet',
      barrel: 'dns',
      kind: 'resource',
    ),
  ];

  test(
      'buildRows joins example back-references and sorts by barrel then tfType',
      () {
    final rows = buildRows(
      catalog: catalog,
      tfTypeToExamples: {
        'resource:google_pubsub_topic': [
          'pubsub_quickstart',
          'eventarc_quickstart',
        ],
        'resource:google_dns_policy': ['dns_quickstart'],
      },
    );
    expect(rows.first.barrel, 'dns');
    expect(rows.first.tfType, 'google_dns_policy');
    expect(rows.first.examples, ['dns_quickstart']);
    expect(
      rows[1].examples,
      isEmpty,
      reason: 'record_set appears in no tf-out',
    );
    expect(
      rows.last.examples,
      ['eventarc_quickstart', 'pubsub_quickstart'],
      reason: 'example lists are sorted',
    );
  });

  test(
      'renderCoveragePage emits marker, frontmatter, counts phrase, '
      'barrel anchors, and rows', () {
    final md = renderCoveragePage(
      rows: buildRows(catalog: catalog, tfTypeToExamples: const {}),
      countsPhrase:
          '380 curated resource factories + 1 data source (381 catalog entries)',
    );
    expect(md, contains('<!-- GENERATED by tool/render_coverage_page.dart'));
    expect(md, contains('title: Coverage'));
    expect(md, contains('380 curated resource factories + 1 data source'));
    expect(md, contains('## dns'));
    expect(md, contains('| `google_dns_policy` | `GoogleDnsPolicy` |'));
    expect(md, contains('Release history'));
  });

  test('resource / data-source twins do not share example back-references', () {
    const twins = [
      (
        tfType: 'google_compute_network',
        className: 'GoogleComputeNetwork',
        barrel: 'compute',
        kind: 'resource',
      ),
      (
        tfType: 'google_compute_network',
        className: 'DataGoogleComputeNetwork',
        barrel: 'data',
        kind: 'dataSource',
      ),
    ];
    final rows = buildRows(
      catalog: twins,
      tfTypeToExamples: {
        'resource:google_compute_network': ['compute_quickstart'],
        'dataSource:google_compute_network': [
          'data_source_leftover_quickstart'
        ],
      },
    );
    expect(rows[0].className, 'GoogleComputeNetwork');
    expect(rows[0].examples, ['compute_quickstart']);
    expect(rows[1].className, 'DataGoogleComputeNetwork');
    expect(rows[1].examples, ['data_source_leftover_quickstart']);
  });

  test('render is deterministic across input permutations', () {
    final a = renderCoveragePage(
      rows: buildRows(catalog: catalog, tfTypeToExamples: const {}),
      countsPhrase: 'x',
    );
    final b = renderCoveragePage(
      rows: buildRows(
        catalog: catalog.reversed.toList(),
        tfTypeToExamples: const {},
      ),
      countsPhrase: 'x',
    );
    expect(a, b);
  });
}
