// render_coverage_page.dart — generate the site's /docs/coverage/ page.
//
// Renders website/src/content/docs/docs/coverage.md from the wrap-generated
// catalog (package:terradart_google/catalog.dart) plus a tfType → example
// back-reference map walked out of synthed examples/*_quickstart/tf-out/
// main.tf.json files. The committed page is a GENERATED artifact: humans edit
// this generator, never the markdown.
//
// Usage:
//   dart tool/example_synth_gates.dart --skip-validate   # populate tf-out
//   dart tool/render_coverage_page.dart                  # write the page
//   dart tool/render_coverage_page.dart --check          # verify freshness
//
// --check exits 1 when the committed page differs from a fresh render (CI
// runs it on the synth-equipped job; the weekly bump agent regenerates as a
// Tier-2 repair when the catalog moved).
// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

import 'package:terradart_google/catalog.dart';

import 'doc_expectations.dart' as expectations;

const _outputPath = 'website/src/content/docs/docs/coverage.md';

typedef CatalogItem = ({
  String tfType,
  String className,
  String barrel,
  String kind,
});

typedef CoverageRow = ({
  String tfType,
  String className,
  String barrel,
  String kind,
  List<String> examples,
});

/// Joins catalog items with their example back-references, sorted by barrel
/// then tfType (deterministic regardless of input order).
List<CoverageRow> buildRows({
  required List<CatalogItem> catalog,
  required Map<String, List<String>> tfTypeToExamples,
}) {
  final rows = [
    for (final item in catalog)
      (
        tfType: item.tfType,
        className: item.className,
        barrel: item.barrel,
        kind: item.kind,
        examples: ([...?tfTypeToExamples[_coverageKey(item.kind, item.tfType)]]
          ..sort()),
      ),
  ]..sort(
      (a, b) {
        final byBarrel = a.barrel.compareTo(b.barrel);
        return byBarrel != 0 ? byBarrel : a.tfType.compareTo(b.tfType);
      },
    );
  return rows;
}

/// Distinguishes resource / data-source twins that share a terraform type.
String _coverageKey(String kind, String tfType) => '$kind:$tfType';

String _exampleCell(List<String> examples) {
  if (examples.isEmpty) return '—';
  return examples
      .map(
        (slug) =>
            '[$slug](https://github.com/nozomi-koborinai/terradart/tree/main/examples/$slug)',
      )
      .join(', ');
}

/// Renders the full markdown page (deterministic for a given input).
String renderCoveragePage({
  required List<CoverageRow> rows,
  required String countsPhrase,
}) {
  final barrels = <String, List<CoverageRow>>{};
  for (final row in rows) {
    barrels.putIfAbsent(row.barrel, () => []).add(row);
  }
  final barrelNames = barrels.keys.toList()..sort();

  final buf = StringBuffer()
    ..writeln('---')
    ..writeln('title: Coverage')
    ..writeln(
      'description: Every curated google_* factory, its barrel import, and '
      'the runnable examples that exercise it.',
    )
    ..writeln('---')
    ..writeln()
    ..writeln(
      '<!-- GENERATED by tool/render_coverage_page.dart — do not edit; '
      'edit the generator and re-run it. -->',
    )
    ..writeln()
    ..writeln(
      'TerraDart currently ships **$countsPhrase**. Each factory below is '
      'generated from the pinned provider schema, exported from the barrel '
      'shown, and — where an example is listed — synthesized (and, for '
      'apply-eligible examples, actually applied) in CI.',
    )
    ..writeln()
    ..writeln(
      'Import per service: `import \'package:terradart_google/<barrel>.dart\';`',
    )
    ..writeln()
    ..writeln('## Barrels')
    ..writeln();
  for (final name in barrelNames) {
    buf.writeln('- [`$name`](#${name.replaceAll('_', '')})');
  }
  buf.writeln();
  for (final name in barrelNames) {
    buf
      ..writeln('## $name')
      ..writeln()
      ..writeln('| Terraform type | Dart factory | Example |')
      ..writeln('| --- | --- | --- |');
    for (final row in barrels[name]!) {
      final suffix = row.kind == 'resource' ? '' : ' (data source)';
      buf.writeln(
        '| `${row.tfType}`$suffix | `${row.className}` | '
        '${_exampleCell(row.examples)} |',
      );
    }
    buf.writeln();
  }
  buf.writeln(
    'Release history: '
    '[GitHub Releases](https://github.com/nozomi-koborinai/terradart/releases)'
    ' · per-package CHANGELOGs.',
  );
  return buf.toString();
}

Map<String, List<String>> _walkTfOuts() {
  final map = <String, Set<String>>{};
  final dirs = Directory('examples').listSync().whereType<Directory>().toList()
    ..sort(
      (a, b) => a.path.compareTo(b.path),
    );
  var seen = 0;
  var quickstarts = 0;
  final missing = <String>[];
  for (final dir in dirs) {
    final slug = dir.path.split(Platform.pathSeparator).last;
    if (!slug.endsWith('_quickstart')) continue;
    quickstarts++;
    final tfJson = File('${dir.path}/tf-out/main.tf.json');
    if (!tfJson.existsSync()) {
      missing.add(slug);
      continue;
    }
    seen++;
    final root = jsonDecode(tfJson.readAsStringSync()) as Map<String, dynamic>;
    for (final section in ['resource', 'data']) {
      final block = root[section];
      if (block is! Map<String, dynamic>) continue;
      final kind = section == 'data' ? 'dataSource' : 'resource';
      for (final tfType in block.keys) {
        map.putIfAbsent(_coverageKey(kind, tfType), () => <String>{}).add(slug);
      }
    }
  }
  // Partial tf-out is as wrong as none: rendering from a subset silently
  // blanks the other examples' back-references (first canary, PR #277).
  if (seen < quickstarts) {
    print(
      'render_coverage_page: tf-out present for only $seen of $quickstarts '
      'quickstarts — run `dart tool/example_synth_gates.dart '
      '--skip-validate` first (missing: ${missing.take(5).join(', ')}'
      '${missing.length > 5 ? ', …' : ''}).',
    );
    exit(1);
  }
  return {
    for (final entry in map.entries) entry.key: entry.value.toList()..sort(),
  };
}

void main(List<String> args) {
  final check = args.contains('--check');
  final catalog = [
    for (final entry in terradartCatalog)
      (
        tfType: entry.tfType,
        className: entry.className,
        barrel: entry.barrel,
        kind: entry.kind.name,
      ),
  ];
  final countsPhrase =
      '${expectations.curatedFactoryCount} curated resource factories + '
      '${expectations.dataSourceCatalogPhrase} (${expectations.catalogEntryCount} catalog entries)';
  final rendered = renderCoveragePage(
    rows: buildRows(catalog: catalog, tfTypeToExamples: _walkTfOuts()),
    countsPhrase: countsPhrase,
  );
  final file = File(_outputPath);
  if (check) {
    final committed = file.existsSync() ? file.readAsStringSync() : '';
    if (committed == rendered) {
      print('render_coverage_page: OK ($_outputPath is fresh)');
      exit(0);
    }
    print(
      'render_coverage_page: STALE — $_outputPath does not match a fresh '
      'render. Run `dart tool/render_coverage_page.dart` and commit.',
    );
    exit(1);
  }
  file.writeAsStringSync(rendered);
  print('render_coverage_page: wrote $_outputPath (${rendered.length} bytes)');
}
