import 'package:test/test.dart';

import 'sync_lane_mm_yaml.dart';

void main() {
  group('mmPathFromGoHeader', () {
    test('reads the mmv1 path of a generated resource', () {
      const header = '''
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/apigateway/ApiConfig.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/resource.go.tmpl
''';
      expect(
        mmPathFromGoHeader(header),
        'mmv1/products/apigateway/ApiConfig.yaml',
      );
    });

    test('is null for a hand-written resource', () {
      expect(
          mmPathFromGoHeader('package compute\n\nfunc Resource() {}'), isNull);
    });
  });

  test('resourceGoFiles keys each service resource file by name', () {
    expect(
      resourceGoFiles(
        [
          'google-beta/services/apigateway/resource_api_gateway_api.go',
          'google-beta/services/apigateway/iam_api_gateway_api.go',
          'google-beta/services/apigateway/resource_api_gateway_api_test.go',
          'google-beta/provider/resource_x.go',
          'google-beta/services/compute/nested/resource_y.go',
        ],
        'google-beta/services',
      ),
      {
        'resource_api_gateway_api.go':
            'google-beta/services/apigateway/resource_api_gateway_api.go',
        'resource_api_gateway_api_test.go':
            'google-beta/services/apigateway/resource_api_gateway_api_test.go',
      },
    );
  });

  test('resourceGoFileName drops the provider prefix', () {
    expect(
      resourceGoFileName('google_api_gateway_api_config'),
      'resource_api_gateway_api_config.go',
    );
  });

  test('renderMmSources lists every type in order, with the reason of a miss',
      () {
    final out = renderMmSources(
      lane: 'google-beta',
      providerVersion: '8.4.0',
      ref: 'abc',
      sources: {
        'google_b': (upstream: null, reason: 'hand-written (b.go)'),
        'google_a': (upstream: 'mmv1/products/a/A.yaml', reason: null),
      },
    );
    expect(
      out,
      endsWith(
        'provider_version: 8.4.0\n'
        'upstream_ref: abc\n'
        'files:\n'
        '  google_a: mmv1/products/a/A.yaml\n'
        '  google_b: null  # hand-written (b.go)\n',
      ),
    );
    expect(out, startsWith('# GENERATED'));
  });
}
