// tool/sync_lane_mm_yaml.dart
//
// Fetches the Magic Modules YAML of every resource in a lane's schema
// fixture, for a lane whose curated set is the fixture itself (google-beta,
// `mmSync:` in tool/providers.yaml) — so there is no hand-kept source
// manifest to drift. Each resource is resolved through the provider's own
// generated Go source at the fixture's release tag: MMv1 resources carry a
// `Configuration: .../magic-modules/tree/main/mmv1/products/<p>/<R>.yaml`
// header in `<servicesDir>/<svc>/resource_<name>.go`; a hand-written
// resource (no header) or a type without that file (IAM adjuncts) has no
// MM YAML. The YAML is read at the magic-modules commit the release was
// generated from (the `[upstream:<sha>]` stamp nearest the release tag,
// tool/sync_mm_yaml.dart resolveUpstreamRef).
//
// Writes, under the lane's schemaDir (never hand-edit either):
//   mm/<terraform_type>.yaml  one per resolved resource; stale ones deleted
//   mm_sources.yaml           the release, the magic-modules commit and the
//                             resolved path (or null + why) per resource —
//                             tool/wrap_lanes.dart compares it with the
//                             fixture to decide whether the sync is stale
//
// Usage (repo root; network: api.github.com + raw.githubusercontent.com,
// GITHUB_TOKEN / GH_TOKEN raises the API rate limit):
//   dart tool/sync_lane_mm_yaml.dart --lane=google-beta [--ref=<mm sha>]
//
// exit: 0 synced; 1 a fetch failed; 64 usage error.
// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;
import 'package:path/path.dart' as p;

import 'sync_mm_yaml.dart' show Manifest, ProviderPin, resolveUpstreamRef;
import 'wrap_lanes.dart';

const _mmRepo = 'GoogleCloudPlatform/magic-modules';

final _configurationHeader = RegExp(
  r'Configuration:\s+https://github\.com/GoogleCloudPlatform/magic-modules/'
  r'tree/[^/\s]+/(mmv1/products/\S+\.yaml)',
);

/// One resource's resolution: its mmv1 path, or null and why not.
typedef MmSource = ({String? upstream, String? reason});

/// The mmv1 path a generated Go resource file names in its header, or null
/// for a hand-written one.
String? mmPathFromGoHeader(String goSource) =>
    _configurationHeader.firstMatch(goSource)?.group(1);

/// `resource_<name>.go` file name → its path under [servicesDir], from the
/// repo tree listing [treePaths].
Map<String, String> resourceGoFiles(
  Iterable<String> treePaths,
  String servicesDir,
) {
  final pattern = RegExp(
    '^${RegExp.escape(servicesDir)}/[^/]+/(resource_[a-z0-9_]+\\.go)\$',
  );
  return {
    for (final path in treePaths)
      if (pattern.firstMatch(path) case final m?) m[1]!: path,
  };
}

/// `resource_<name>.go` for a Terraform [type] (`google_<name>`).
String resourceGoFileName(String type) =>
    'resource_${type.substring(type.indexOf('_') + 1)}.go';

/// The generated `mm_sources.yaml` for [sources] (sorted by type).
String renderMmSources({
  required String lane,
  required String providerVersion,
  required String ref,
  required Map<String, MmSource> sources,
}) {
  final buf = StringBuffer()
    ..writeln(
      '# GENERATED by `dart tool/sync_lane_mm_yaml.dart --lane=$lane`'
      ' - never hand-edit.',
    )
    ..writeln(
      '# Every resource of schema.json, resolved to its Magic Modules '
      'YAML (mm/<type>.yaml)',
    )
    ..writeln(
      '# through the provider\'s generated Go source at the release '
      'tag; null when the',
    )
    ..writeln(
      '# resource has none. tool/wrap_lanes.dart re-syncs when this '
      'file no longer',
    )
    ..writeln('# matches provider_version.txt or the schema.json resource set.')
    ..writeln('provider_version: $providerVersion')
    ..writeln('upstream_ref: $ref')
    ..writeln('files:');
  for (final type in sources.keys.toList()..sort()) {
    final s = sources[type]!;
    buf.writeln(
      s.upstream != null
          ? '  $type: ${s.upstream}'
          : '  $type: null  # ${s.reason}',
    );
  }
  return buf.toString();
}

Map<String, String> _githubHeaders() {
  final token =
      Platform.environment['GITHUB_TOKEN'] ?? Platform.environment['GH_TOKEN'];
  return {
    'Accept': 'application/vnd.github+json',
    if (token != null && token.isNotEmpty) 'Authorization': 'Bearer $token',
  };
}

Future<List<String>> _treePaths(String repo, String tag) async {
  final r = await http.get(
    Uri.https('api.github.com', '/repos/$repo/git/trees/$tag', {
      'recursive': '1',
    }),
    headers: _githubHeaders(),
  );
  if (r.statusCode != 200) {
    throw HttpException('GET tree of $repo@$tag: HTTP ${r.statusCode}');
  }
  final body = jsonDecode(r.body) as Map<String, dynamic>;
  if (body['truncated'] == true) {
    throw StateError('the tree of $repo@$tag is truncated');
  }
  return [for (final e in body['tree'] as List) (e as Map)['path'] as String];
}

Future<String> _raw(String repo, String ref, String path) async {
  final r = await http.get(
    Uri.parse('https://raw.githubusercontent.com/$repo/$ref/$path'),
  );
  if (r.statusCode != 200) {
    throw HttpException('GET $repo@$ref/$path: HTTP ${r.statusCode}');
  }
  return r.body;
}

Future<void> main(List<String> args) async {
  String? laneName;
  String? refOverride;
  for (final a in args) {
    if (a.startsWith('--lane=')) {
      laneName = a.substring('--lane='.length);
    } else if (a.startsWith('--ref=')) {
      refOverride = a.substring('--ref='.length);
    } else {
      print('sync_lane_mm_yaml: unknown argument $a');
      exit(64);
    }
  }
  final lanes = parseWrapLanes(File(providersPath).readAsStringSync());
  final lane = [
    for (final l in lanes)
      if (l.name == laneName) l,
  ].firstOrNull;
  final sync = lane?.mmSync;
  if (lane == null || sync == null) {
    print(
      'usage: dart tool/sync_lane_mm_yaml.dart --lane=<a lane with '
      'mmSync: in $providersPath> [--ref=<magic-modules sha>]',
    );
    exit(64);
  }

  final versionFile = p.join(lane.schemaDir, 'provider_version.txt');
  final version = File(versionFile).readAsStringSync().trim();
  final tag = 'v$version';
  final ref = await resolveUpstreamRef(
    Manifest(
      upstreamRepo: _mmRepo,
      providerPin: ProviderPin(
        providerRepo: sync.providerRepo,
        versionFile: versionFile,
      ),
      files: const {},
    ),
    override: refOverride,
  );
  print('>> ${lane.name}: ${sync.providerRepo} $tag, magic-modules $ref');

  final schema =
      jsonDecode(File(p.join(lane.schemaDir, 'schema.json')).readAsStringSync())
          as Map<String, dynamic>;
  final types = <String>[
    for (final provider
        in (schema['provider_schemas'] as Map<String, dynamic>).values)
      ...((provider as Map<String, dynamic>)['resource_schemas']
                  as Map<String, dynamic>? ??
              const {})
          .keys,
  ]..sort();

  final goFiles = resourceGoFiles(
    await _treePaths(sync.providerRepo, tag),
    sync.servicesDir,
  );
  // Every fetch completes before anything is written, so a failed sync
  // leaves the fixture as it was.
  final fetched = <String, String>{};
  final sources = <String, MmSource>{};
  for (final type in types) {
    final goPath = goFiles[resourceGoFileName(type)];
    if (goPath == null) {
      sources[type] = (
        upstream: null,
        reason: 'no ${resourceGoFileName(type)} in ${sync.servicesDir}',
      );
      continue;
    }
    final upstream = mmPathFromGoHeader(
      await _raw(sync.providerRepo, tag, goPath),
    );
    if (upstream == null) {
      sources[type] = (upstream: null, reason: 'hand-written ($goPath)');
      continue;
    }
    fetched[type] = await _raw(_mmRepo, ref, upstream);
    sources[type] = (upstream: upstream, reason: null);
  }

  final mmDir = Directory(p.join(lane.schemaDir, 'mm'))
    ..createSync(recursive: true);
  for (final MapEntry(key: type, value: body) in fetched.entries) {
    File(p.join(mmDir.path, '$type.yaml')).writeAsStringSync(body);
  }
  for (final f in mmDir.listSync().whereType<File>()) {
    final type = p.basenameWithoutExtension(f.path);
    if (f.path.endsWith('.yaml') && sources[type]?.upstream == null) {
      f.deleteSync();
    }
  }
  File(p.join(lane.schemaDir, mmSourcesFile)).writeAsStringSync(
    renderMmSources(
      lane: lane.name,
      providerVersion: version,
      ref: ref,
      sources: sources,
    ),
  );
  final resolved = sources.values.where((s) => s.upstream != null).length;
  print(
    'sync_lane_mm_yaml: $resolved of ${types.length} resources have MM '
    'YAML (${lane.schemaDir}/mm)',
  );
}
