/// HCL → Dart migrator for existing Terraform users (`terradart-migrate`,
/// #80).
///
/// [migrateModule] turns a [TfModule] (read through `terradart_hcl`) into a
/// Dart package — a `Stack` class, `bin/infra.dart` and `pubspec.yaml` — and
/// a [MigrationReport] listing what became Dart and what stays in Terraform,
/// with a reason each. The recipe it follows is the **migration manifest**
/// of each curated catalog: one [MigrateManifest] per provider package,
/// generated by `terradart wrap --migrate-manifest`; [allMigrateManifests]
/// lists them, [manifestForPackage] and [findMigrateEntry] look them up.
library;

import 'package:terradart_hcl/terradart_hcl.dart' show TfModule;

import 'src/manifests.dart';
import 'src/migrate_manifest.dart';
import 'src/report.dart';

export 'src/cli.dart';
export 'src/manifests.dart';
export 'src/migrate.dart';
export 'src/migrate_manifest.dart';
export 'src/project.dart';
export 'src/report.dart';
export 'src/sidecar.dart';
export 'src/topology.dart';
export 'src/version.dart';
