/// HCL → Dart migrator for existing Terraform users (`terradart-migrate`,
/// #80).
///
/// This phase ships the **migration manifests**: one [MigrateManifest] per
/// curated catalog (`terradart_google`, `terradart_google_beta`,
/// `terradart_appwrite`, `terradart_cloudflare`), generated by
/// `terradart wrap --migrate-manifest` from the same inputs as the factories
/// themselves. [allMigrateManifests] lists them; [manifestForPackage] and
/// [MigrateManifest.entryFor] look them up.
library;

export 'src/manifests.dart';
export 'src/migrate_manifest.dart';
