name: terradart_example_network_connectivity_quickstart
description: terradart example — Network Connectivity CCI transport.
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  terradart_core: ^0.27.0
  terradart_google: ^0.27.0

dev_dependencies:
  lints: ^6.0.0
