/// Banner / TODO templates for `terradart wrap-init` output.
///
/// Centralised so future copy revisions diff in one place across ~1000
/// yamls (Phase 4.5), and so CI grep gates can assert "every yaml emitted
/// by wrap-init carries the banner".
library;

/// Two-line banner prepended to every wrap-init output. `{date}` is replaced
/// at emit time with `Clock.now().toIso8601String()` truncated to date only.
const String wrapInitBannerTemplate =
    '# Auto-generated by `terradart wrap-init` on {date}.\n'
    '# Review every TODO before committing.\n';

/// TODO note above `classDocComment` when MM YAML had no description.
const String todoClassDocCommentNoMm =
    'write a class doc comment for this resource (MM YAML had no description).';

/// TODO note above `classDocComment` when MM YAML provided a description seed.
const String todoClassDocCommentWithMm =
    'expand the MM-seeded comment with a usage example, ForceNew callouts, and composition notes.';

/// TODO note above the commented-out `extraGetters` skeleton.
const String todoExtraGetters =
    'verify the `id` / `name` attrs exist on this resource; uncomment the block below '
    'and add cross-resource hint getters (e.g. `topic.id` for downstream resources).';

/// TODO note above the commented-out `deprecatedParams` block.
const String todoDeprecatedParams =
    'review MM-derived deprecation messages and uncomment the entries that apply.';

/// Banner above the commented-out `paramOrder` scaffold.
const String paramOrderCommentedBanner =
    'paramOrder is commented; uncomment + reorder only if natural schema order needs override.';
