// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
/// OS Config guest policies (beta-only).
library;

export 'src/os_config/google_os_config_guest_policies.dart'
    show
        GoogleOsConfigGuestPolicies,
        OsConfigGuestPoliciesAssignment,
        OsConfigGuestPoliciesAssignmentGroupLabels,
        OsConfigGuestPoliciesAssignmentOsTypes,
        OsConfigGuestPoliciesPackageRepositories,
        OsConfigGuestPoliciesPackageRepositoriesApt,
        OsConfigGuestPoliciesPackageRepositoriesAptArchiveType,
        OsConfigGuestPoliciesPackageRepositoriesGoo,
        OsConfigGuestPoliciesPackageRepositoriesYum,
        OsConfigGuestPoliciesPackageRepositoriesZypper,
        OsConfigGuestPoliciesPackages,
        OsConfigGuestPoliciesPackagesDesiredState,
        OsConfigGuestPoliciesPackagesManager,
        OsConfigGuestPoliciesRecipes,
        OsConfigGuestPoliciesRecipesArtifacts,
        OsConfigGuestPoliciesRecipesArtifactsGcs,
        OsConfigGuestPoliciesRecipesArtifactsRemote,
        OsConfigGuestPoliciesRecipesDesiredState,
        OsConfigGuestPoliciesRecipesInstallSteps,
        OsConfigGuestPoliciesRecipesInstallStepsArchiveExtraction,
        OsConfigGuestPoliciesRecipesInstallStepsArchiveExtractionType,
        OsConfigGuestPoliciesRecipesInstallStepsDpkgInstallation,
        OsConfigGuestPoliciesRecipesInstallStepsFileCopy,
        OsConfigGuestPoliciesRecipesInstallStepsFileExec,
        OsConfigGuestPoliciesRecipesInstallStepsMsiInstallation,
        OsConfigGuestPoliciesRecipesInstallStepsRpmInstallation,
        OsConfigGuestPoliciesRecipesInstallStepsScriptRun,
        OsConfigGuestPoliciesRecipesInstallStepsScriptRunInterpreter,
        OsConfigGuestPoliciesRecipesUpdateSteps,
        OsConfigGuestPoliciesRecipesUpdateStepsArchiveExtraction,
        OsConfigGuestPoliciesRecipesUpdateStepsArchiveExtractionType,
        OsConfigGuestPoliciesRecipesUpdateStepsDpkgInstallation,
        OsConfigGuestPoliciesRecipesUpdateStepsFileCopy,
        OsConfigGuestPoliciesRecipesUpdateStepsFileExec,
        OsConfigGuestPoliciesRecipesUpdateStepsMsiInstallation,
        OsConfigGuestPoliciesRecipesUpdateStepsRpmInstallation,
        OsConfigGuestPoliciesRecipesUpdateStepsScriptRun,
        OsConfigGuestPoliciesRecipesUpdateStepsScriptRunInterpreter;
