// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
/// Privileged Access Manager settings (beta-only).
library;

export 'src/privileged_access_manager/google_privileged_access_manager_settings.dart'
    show
        GooglePrivilegedAccessManagerSettings,
        PrivilegedAccessManagerSettingsEmailNotificationSettings,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehavior,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorAdminNotifications,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorAdminNotificationsGrantActivated,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorAdminNotificationsGrantActivationFailed,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorAdminNotificationsGrantEnded,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorAdminNotificationsGrantExternallyModified,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorApproverNotifications,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorApproverNotificationsPendingApproval,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorChoice,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorRequesterNotifications,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorRequesterNotificationsEntitlementAssigned,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorRequesterNotificationsGrantActivated,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorRequesterNotificationsGrantActivationFailed,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorRequesterNotificationsGrantDenied,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorRequesterNotificationsGrantEnded,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorRequesterNotificationsGrantExpired,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorRequesterNotificationsGrantExternallyModified,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsCustomNotificationBehaviorRequesterNotificationsGrantRevoked,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsDisableAllNotifications,
        PrivilegedAccessManagerSettingsEmailNotificationSettingsDisableAllNotificationsChoice,
        PrivilegedAccessManagerSettingsServiceAccountApproverSettings;
