import '../ir/provider_schema_ir.dart';
import '../ir/resource_def.dart';

/// Plan 5.X (v0.5.0-dev) — schemantic Layer 1 emission is retired.
///
/// Pre-Plan-5.X, this emitter wrote the `// Generated by terradart codegen.`
/// banner, the `package:schemantic` / `package:terradart_annotations`
/// imports, and the `part '<type>.schema.g.dart';` directive that fed the
/// schemantic build_runner stage. With the schemantic chain dropped, none
/// of those outputs have a consumer. The call site in `wrap_command.dart`
/// no longer invokes [emit]; the class is retained as a transitional stub
/// so any downstream tool that still imports it does not break, but [emit]
/// returns an empty string.
///
/// Safe to delete entirely once no external consumer is observed; left in
/// place for one release cycle out of an abundance of caution.
class FileEmitter {
  /// Plan 5.X stub. Always returns the empty string.
  ///
  /// Parameters are kept to preserve the v0.4 API shape, but [ir] / [def] /
  /// [extraSensitiveFields] are intentionally unused — Layer 1 no longer
  /// exists.
  String emit({
    required ProviderSchemaIR ir,
    required ResourceDef def,
    List<String>? extraSensitiveFields,
  }) {
    return '';
  }
}
