import 'package:dart_style/dart_style.dart';

import '../ir/provider_schema_ir.dart';
import '../ir/resource_def.dart';
import 'abstract_class_emitter.dart';

/// Emits one fully-formed Dart source file per resource.
///
/// Wraps [AbstractClassEmitter] with the generated banner, the schemantic /
/// terradart_annotations imports, the `part '<type>.schema.g.dart';`
/// directive (consumed by schemantic Stage 2), and runs the resulting
/// buffer through `dart_style.DartFormatter` for deterministic output.
class FileEmitter {
  final DartFormatter _formatter;

  FileEmitter()
      : _formatter = DartFormatter(
          languageVersion: DartFormatter.latestLanguageVersion,
        );

  /// Emits the full Dart source for one resource file (formatted).
  ///
  /// [extraSensitiveFields] (optional) is forwarded to the abstract-class
  /// emitter so the curator's yaml override can extend the emitted
  /// `<terraformTypeCamelCase>Sensitive` set beyond the schema-derived
  /// `@Sensitive` paths.
  String emit({
    required ProviderSchemaIR ir,
    required ResourceDef def,
    List<String>? extraSensitiveFields,
  }) {
    final body = const AbstractClassEmitter().emit(
      def,
      providerSource: ir.providerSource,
      extraSensitiveFields: extraSensitiveFields,
    );
    final partFile = '${def.terraformType}.schema.g.dart';
    final src = '''
// Generated by terradart codegen. DO NOT EDIT.
// Source: ${ir.providerSource} v${ir.providerVersion} -- ${def.terraformType}
import 'package:schemantic/schemantic.dart';
import 'package:terradart_annotations/terradart_annotations.dart';

part '$partFile';

$body
''';
    return _formatter.format(src);
  }
}
