/// Marker delimiters + helpers for the `wrap-promote` additions section.
///
/// Phase 4.3 overlays MM-derived hints onto an existing wrap-init-produced
/// YAML by appending a marker-delimited block at the bottom. The marker is
/// stripped and re-appended on every wrap-promote run, making the operation
/// idempotent for the same inputs.
class WrapPromoteMarker {
  WrapPromoteMarker._();

  static const String beginMarker =
      '# === wrap-promote additions (do not edit inside this block; regenerated by wrap-promote) ===';
  static const String endMarker = '# === end wrap-promote additions ===';

  /// Removes the marker-delimited section from [yaml]. Returns [yaml]
  /// unchanged when no marker is present.
  ///
  /// Throws [FormatException] when a begin marker is found but no matching
  /// end marker — refusing to mutate yaml whose structure we can't reason
  /// about safely.
  static String stripMarkerSection(String yaml) {
    final beginIdx = yaml.indexOf(beginMarker);
    if (beginIdx < 0) return yaml;
    final endIdx = yaml.indexOf(endMarker, beginIdx);
    if (endIdx < 0) {
      throw const FormatException(
        'wrap-promote marker section opened but not closed; refusing to strip.',
      );
    }
    final after = endIdx + endMarker.length;
    // Trim trailing whitespace from the head, leading whitespace from the
    // tail, and reattach with a single newline separator.
    final before = yaml.substring(0, beginIdx).trimRight();
    final tail = yaml.substring(after).trimLeft();
    return tail.isEmpty ? '$before\n' : '$before\n$tail';
  }

  /// Wraps [content] (multi-line yaml additions) with begin/end markers and
  /// a generation banner. Returned string includes a leading newline so it
  /// can be appended directly to existing yaml.
  static String wrapWithMarkers(String content, DateTime bannerDate) {
    final date = bannerDate.toIso8601String().substring(0, 10);
    final buf = StringBuffer()
      ..writeln()
      ..writeln(beginMarker)
      ..writeln('# Generated on $date. Rename placeholders, copy/integrate '
          'into the main yaml above, fill in encode() bodies, then delete this block.')
      ..writeln()
      ..write(content);
    if (!content.endsWith('\n')) buf.writeln();
    buf.writeln(endMarker);
    return buf.toString();
  }
}
