// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
import 'catalog_entry.dart';

const List<CatalogEntry> terradartCatalog = <CatalogEntry>[
  CatalogEntry(
    tfType: 'appwrite_auth_team',
    className: 'AppwriteAuthTeam',
    barrel: 'auth',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_auth_team`.',
    constructorParams: <String>['localName', 'name', 'projectId', 'roles'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_auth_team`.\n\nManages an Appwrite team.',
  ),
  CatalogEntry(
    tfType: 'appwrite_auth_team',
    className: 'DataAppwriteAuthTeam',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_auth_team`.',
    constructorParams: <String>['localName', 'id', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_auth_team`.\n\nFetches an Appwrite team by ID.',
  ),
  CatalogEntry(
    tfType: 'appwrite_auth_user',
    className: 'AppwriteAuthUser',
    barrel: 'auth',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_auth_user`.',
    constructorParams: <String>[
      'localName',
      'email',
      'emailVerification',
      'labels',
      'name',
      'password',
      'phone',
      'phoneVerification',
      'projectId',
      'status',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['password'],
    docComment:
        'Factory wrapper for `appwrite_auth_user`.\n\nManages an Appwrite user.',
  ),
  CatalogEntry(
    tfType: 'appwrite_auth_user',
    className: 'DataAppwriteAuthUser',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_auth_user`.',
    constructorParams: <String>['localName', 'id', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_auth_user`.\n\nFetches an Appwrite user by ID.',
  ),
  CatalogEntry(
    tfType: 'appwrite_backup_policy',
    className: 'AppwriteBackupPolicy',
    barrel: 'backups',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_backup_policy`.',
    constructorParams: <String>[
      'localName',
      'enabled',
      'name',
      'projectId',
      'resourceId',
      'retention',
      'schedule',
      'services',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_backup_policy`.\n\nManages an Appwrite backup policy.',
  ),
  CatalogEntry(
    tfType: 'appwrite_function',
    className: 'AppwriteFunction',
    barrel: 'functions',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_function`.',
    constructorParams: <String>[
      'localName',
      'buildSpecification',
      'commands',
      'deploymentRetention',
      'enabled',
      'entrypoint',
      'events',
      'execute',
      'installationId',
      'logging',
      'name',
      'projectId',
      'providerBranch',
      'providerRepositoryId',
      'providerRootDirectory',
      'providerSilentMode',
      'runtime',
      'runtimeSpecification',
      'schedule',
      'scopes',
      'timeout',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_function`.\n\nManages an Appwrite function.',
  ),
  CatalogEntry(
    tfType: 'appwrite_function',
    className: 'DataAppwriteFunction',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_function`.',
    constructorParams: <String>['localName', 'id', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_function`.\n\nFetches an Appwrite function by ID.',
  ),
  CatalogEntry(
    tfType: 'appwrite_function_deployment',
    className: 'AppwriteFunctionDeployment',
    barrel: 'functions',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_function_deployment`.',
    constructorParams: <String>[
      'localName',
      'activate',
      'codeHash',
      'codePath',
      'commands',
      'entrypoint',
      'functionId',
      'owner',
      'projectId',
      'reference',
      'repository',
      'rootDirectory',
      'sourceType',
      'type',
      'waitForReady',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_function_deployment`.\n\nManages an Appwrite function deployment.',
  ),
  CatalogEntry(
    tfType: 'appwrite_function_variable',
    className: 'AppwriteFunctionVariable',
    barrel: 'functions',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_function_variable`.',
    constructorParams: <String>[
      'localName',
      'functionId',
      'key',
      'projectId',
      'secret',
      'value',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['value'],
    docComment:
        'Factory wrapper for `appwrite_function_variable`.\n\nManages an Appwrite function environment variable.\n\nFunction environment variable. [value] is sensitive — pass\n`TfArg.variable` so the secret never enters synth output.',
  ),
  CatalogEntry(
    tfType: 'appwrite_messaging_provider',
    className: 'AppwriteMessagingProvider',
    barrel: 'messaging',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_messaging_provider`.',
    constructorParams: <String>[
      'localName',
      'accountSid',
      'apiKey',
      'apiSecret',
      'authKey',
      'authKeyId',
      'authToken',
      'autoTls',
      'bundleId',
      'customerId',
      'domain',
      'enabled',
      'encryption',
      'from',
      'fromEmail',
      'fromName',
      'host',
      'isEuRegion',
      'name',
      'password',
      'port',
      'projectId',
      'replyToEmail',
      'replyToName',
      'sandbox',
      'senderId',
      'serviceAccountJson',
      'teamId',
      'templateId',
      'type',
      'username',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[
      'api_key',
      'api_secret',
      'auth_key',
      'auth_token',
      'password',
      'service_account_json',
    ],
    docComment:
        'Factory wrapper for `appwrite_messaging_provider`.\n\nManages an Appwrite messaging provider.',
  ),
  CatalogEntry(
    tfType: 'appwrite_messaging_subscriber',
    className: 'AppwriteMessagingSubscriber',
    barrel: 'messaging',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_messaging_subscriber`.',
    constructorParams: <String>[
      'localName',
      'projectId',
      'targetId',
      'topicId',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_messaging_subscriber`.\n\nManages a subscriber to an Appwrite messaging topic.',
  ),
  CatalogEntry(
    tfType: 'appwrite_messaging_topic',
    className: 'AppwriteMessagingTopic',
    barrel: 'messaging',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_messaging_topic`.',
    constructorParams: <String>['localName', 'name', 'projectId', 'subscribe'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_messaging_topic`.\n\nManages an Appwrite messaging topic.',
  ),
  CatalogEntry(
    tfType: 'appwrite_messaging_topic',
    className: 'DataAppwriteMessagingTopic',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_messaging_topic`.',
    constructorParams: <String>['localName', 'id', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_messaging_topic`.\n\nFetches an Appwrite messaging topic by ID.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mongo_backup_policy',
    className: 'AppwriteMongoBackupPolicy',
    barrel: 'mongo',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_mongo_backup_policy`.',
    constructorParams: <String>[
      'localName',
      'databaseId',
      'enabled',
      'name',
      'projectId',
      'retention',
      'schedule',
      'type',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_mongo_backup_policy`.\n\nManages a scheduled backup policy for a dedicated Appwrite MongoDB database.\nUse `appwrite_backup_policy` instead for databases running on Appwrite\'s\nshared infrastructure.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mongo_backup_storage',
    className: 'AppwriteMongoBackupStorage',
    barrel: 'mongo',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_mongo_backup_storage`.',
    constructorParams: <String>[
      'localName',
      'accessKey',
      'bucket',
      'databaseId',
      'endpoint',
      'prefix',
      'projectId',
      'region',
      'secretKey',
      'storageProvider',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['access_key', 'secret_key'],
    docComment:
        'Factory wrapper for `appwrite_mongo_backup_storage`.\n\nSends the backups of a dedicated Appwrite MongoDB database to a bucket you\nown rather than Appwrite\'s default storage.\n\nThe API offers no route to read this configuration back, so Terraform cannot\ndetect drift, cannot verify what the server currently has, and cannot import\nan existing configuration. Destroying this resource only removes it from\nstate; backups continue going to the last destination applied. Change the\ndestination by applying a new one.\n\nCustom MongoDB backup destination. The API has no read route, so\nTerraform cannot detect drift or import an existing configuration.\n[accessKey] / [secretKey] are sensitive — use `TfArg.variable`.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mongo_backups',
    className: 'DataAppwriteMongoBackups',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_mongo_backups`.',
    constructorParams: <String>[
      'localName',
      'databaseId',
      'projectId',
      'queries',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_mongo_backups`.\n\nLists the backups taken of a dedicated Appwrite MongoDB database. Restoring\nis not a Terraform operation, so this is how a backup ID is found for a\nrestore run through the Console or API.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mongo_branch',
    className: 'AppwriteMongoBranch',
    barrel: 'mongo',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_mongo_branch`.',
    constructorParams: <String>[
      'localName',
      'branchId',
      'databaseId',
      'projectId',
      'ttl',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['connection_string', 'password'],
    docComment:
        'Factory wrapper for `appwrite_mongo_branch`.\n\nCreates a branch of a dedicated Appwrite MongoDB database: a copy that\nshares the parent\'s credentials but has its own host and database name.\n\nBranches have no update route, so changing any argument replaces the branch\nand discards its data. A branch given a `ttl` is deleted by the server when\nit expires; the next refresh then drops it from state and the following plan\nrecreates it.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mongo_database',
    className: 'AppwriteMongoDatabase',
    barrel: 'mongo',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_mongo_database`.',
    constructorParams: <String>[
      'localName',
      'idleTimeoutMinutes',
      'maintenanceWindowDay',
      'maintenanceWindowHourUtc',
      'name',
      'networkIdleTimeoutSeconds',
      'networkIpAllowlist',
      'pitr',
      'pitrRetentionDays',
      'projectId',
      'replicas',
      'specification',
      'sqlApiAllowedStatements',
      'sqlApiEnabled',
      'sqlApiMaxBytes',
      'sqlApiMaxRows',
      'sqlApiTimeoutSeconds',
      'status',
      'storageAutoscaling',
      'storageAutoscalingMaxGb',
      'storageAutoscalingThresholdPercent',
      'syncMode',
      'version',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['connection_password', 'connection_string'],
    docComment:
        'Factory wrapper for `appwrite_mongo_database`.\n\nManages a dedicated Appwrite MongoDB database. A dedicated database runs on\ninfrastructure reserved for one project, so creating, resizing or upgrading\none takes several minutes; Terraform waits for the database to settle before\ncontinuing.\n\nDedicated MongoDB database (reserved compute, billed while it exists).\nProvisioning takes several minutes; apply waits for settle.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mongo_database',
    className: 'DataAppwriteMongoDatabase',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_mongo_database`.',
    constructorParams: <String>['localName', 'id', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>['connection_password', 'connection_string'],
    docComment:
        'Factory wrapper for `appwrite_mongo_database`.\n\nFetches a dedicated Appwrite MongoDB database by ID.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mongo_database_status',
    className: 'DataAppwriteMongoDatabaseStatus',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_mongo_database_status`.',
    constructorParams: <String>['localName', 'databaseId', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_mongo_database_status`.\n\nReads the live operational state of a dedicated Appwrite MongoDB database:\nhealth, replication, connection counts and storage volumes.\n\nThese are measurements taken when Terraform refreshes, not configuration, so\nthey change between runs on their own. Use them for outputs and checks, not\nto drive resource arguments.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mongo_databases',
    className: 'DataAppwriteMongoDatabases',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_mongo_databases`.',
    constructorParams: <String>['localName', 'projectId', 'queries'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_mongo_databases`.\n\nLists the dedicated Appwrite MongoDB databases in a project. Connection\ncredentials are deliberately not included; read them from the singular\n`appwrite_mongo_database` data source for the one database that needs them,\nso a listing does not put every password into state.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mongo_specifications',
    className: 'DataAppwriteMongoSpecifications',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_mongo_specifications`.',
    constructorParams: <String>['localName', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_mongo_specifications`.\n\nLists the compute specifications available for dedicated MongoDB databases,\nso a `specification` slug can be selected without hardcoding it.\nAvailability depends on the organization\'s billing plan; check `enabled`\nbefore using a slug.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mysql_backup_policy',
    className: 'AppwriteMysqlBackupPolicy',
    barrel: 'mysql',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_mysql_backup_policy`.',
    constructorParams: <String>[
      'localName',
      'databaseId',
      'enabled',
      'name',
      'projectId',
      'retention',
      'schedule',
      'type',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_mysql_backup_policy`.\n\nManages a scheduled backup policy for a dedicated Appwrite MySQL database.\nUse `appwrite_backup_policy` instead for databases running on Appwrite\'s\nshared infrastructure.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mysql_backup_storage',
    className: 'AppwriteMysqlBackupStorage',
    barrel: 'mysql',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_mysql_backup_storage`.',
    constructorParams: <String>[
      'localName',
      'accessKey',
      'bucket',
      'databaseId',
      'endpoint',
      'prefix',
      'projectId',
      'region',
      'secretKey',
      'storageProvider',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['access_key', 'secret_key'],
    docComment:
        'Factory wrapper for `appwrite_mysql_backup_storage`.\n\nSends the backups of a dedicated Appwrite MySQL database to a bucket you own\nrather than Appwrite\'s default storage.\n\nThe API offers no route to read this configuration back, so Terraform cannot\ndetect drift, cannot verify what the server currently has, and cannot import\nan existing configuration. Destroying this resource only removes it from\nstate; backups continue going to the last destination applied. Change the\ndestination by applying a new one.\n\nCustom MySQL backup destination. The API has no read route, so\nTerraform cannot detect drift or import an existing configuration.\n[accessKey] / [secretKey] are sensitive — use `TfArg.variable`.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mysql_backups',
    className: 'DataAppwriteMysqlBackups',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_mysql_backups`.',
    constructorParams: <String>[
      'localName',
      'databaseId',
      'projectId',
      'queries',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_mysql_backups`.\n\nLists the backups taken of a dedicated Appwrite MySQL database. Restoring is\nnot a Terraform operation, so this is how a backup ID is found for a restore\nrun through the Console or API.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mysql_branch',
    className: 'AppwriteMysqlBranch',
    barrel: 'mysql',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_mysql_branch`.',
    constructorParams: <String>[
      'localName',
      'branchId',
      'databaseId',
      'projectId',
      'ttl',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['connection_string', 'password'],
    docComment:
        'Factory wrapper for `appwrite_mysql_branch`.\n\nCreates a branch of a dedicated Appwrite MySQL database: a copy that shares\nthe parent\'s credentials but has its own host and database name.\n\nBranches have no update route, so changing any argument replaces the branch\nand discards its data. A branch given a `ttl` is deleted by the server when\nit expires; the next refresh then drops it from state and the following plan\nrecreates it.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mysql_database',
    className: 'AppwriteMysqlDatabase',
    barrel: 'mysql',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_mysql_database`.',
    constructorParams: <String>[
      'localName',
      'idleTimeoutMinutes',
      'maintenanceWindowDay',
      'maintenanceWindowHourUtc',
      'name',
      'networkIdleTimeoutSeconds',
      'networkIpAllowlist',
      'pitr',
      'pitrRetentionDays',
      'projectId',
      'replicas',
      'specification',
      'sqlApiAllowedStatements',
      'sqlApiEnabled',
      'sqlApiMaxBytes',
      'sqlApiMaxRows',
      'sqlApiTimeoutSeconds',
      'status',
      'storageAutoscaling',
      'storageAutoscalingMaxGb',
      'storageAutoscalingThresholdPercent',
      'syncMode',
      'version',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['connection_password', 'connection_string'],
    docComment:
        'Factory wrapper for `appwrite_mysql_database`.\n\nManages a dedicated Appwrite MySQL database. A dedicated database runs on\ninfrastructure reserved for one project, so creating, resizing or upgrading\none takes several minutes; Terraform waits for the database to settle before\ncontinuing.\n\nDedicated MySQL database (reserved compute, billed while it exists).\nProvisioning takes several minutes; apply waits for settle.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mysql_database',
    className: 'DataAppwriteMysqlDatabase',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_mysql_database`.',
    constructorParams: <String>['localName', 'id', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>['connection_password', 'connection_string'],
    docComment:
        'Factory wrapper for `appwrite_mysql_database`.\n\nFetches a dedicated Appwrite MySQL database by ID.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mysql_database_status',
    className: 'DataAppwriteMysqlDatabaseStatus',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_mysql_database_status`.',
    constructorParams: <String>['localName', 'databaseId', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_mysql_database_status`.\n\nReads the live operational state of a dedicated Appwrite MySQL database:\nhealth, replication, connection counts and storage volumes.\n\nThese are measurements taken when Terraform refreshes, not configuration, so\nthey change between runs on their own. Use them for outputs and checks, not\nto drive resource arguments.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mysql_databases',
    className: 'DataAppwriteMysqlDatabases',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_mysql_databases`.',
    constructorParams: <String>['localName', 'projectId', 'queries'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_mysql_databases`.\n\nLists the dedicated Appwrite MySQL databases in a project. Connection\ncredentials are deliberately not included; read them from the singular\n`appwrite_mysql_database` data source for the one database that needs them,\nso a listing does not put every password into state.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mysql_pooler',
    className: 'AppwriteMysqlPooler',
    barrel: 'mysql',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_mysql_pooler`.',
    constructorParams: <String>[
      'localName',
      'databaseId',
      'defaultPoolSize',
      'maxConnections',
      'mode',
      'poolerCpuLimit',
      'poolerCpuRequest',
      'poolerMemoryLimit',
      'poolerMemoryRequest',
      'projectId',
      'readWriteSplitting',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_mysql_pooler`.\n\nConfigures the connection pooler of a dedicated Appwrite MySQL database. The\npooler exists for the lifetime of the database, so this resource only ever\nupdates its settings: destroying it leaves the pooler running with its last\napplied configuration.',
  ),
  CatalogEntry(
    tfType: 'appwrite_mysql_specifications',
    className: 'DataAppwriteMysqlSpecifications',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_mysql_specifications`.',
    constructorParams: <String>['localName', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_mysql_specifications`.\n\nLists the compute specifications available for dedicated MySQL databases, so\na `specification` slug can be selected without hardcoding it. Availability\ndepends on the organization\'s billing plan; check `enabled` before using a\nslug.',
  ),
  CatalogEntry(
    tfType: 'appwrite_postgresql_backup_policy',
    className: 'AppwritePostgresqlBackupPolicy',
    barrel: 'postgresql',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_postgresql_backup_policy`.',
    constructorParams: <String>[
      'localName',
      'databaseId',
      'enabled',
      'name',
      'projectId',
      'retention',
      'schedule',
      'type',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_postgresql_backup_policy`.\n\nManages a scheduled backup policy for a dedicated Appwrite PostgreSQL\ndatabase. Use `appwrite_backup_policy` instead for databases running on\nAppwrite\'s shared infrastructure.',
  ),
  CatalogEntry(
    tfType: 'appwrite_postgresql_backup_storage',
    className: 'AppwritePostgresqlBackupStorage',
    barrel: 'postgresql',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_postgresql_backup_storage`.',
    constructorParams: <String>[
      'localName',
      'accessKey',
      'bucket',
      'databaseId',
      'endpoint',
      'prefix',
      'projectId',
      'region',
      'secretKey',
      'storageProvider',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['access_key', 'secret_key'],
    docComment:
        'Factory wrapper for `appwrite_postgresql_backup_storage`.\n\nSends the backups of a dedicated Appwrite PostgreSQL database to a bucket\nyou own rather than Appwrite\'s default storage.\n\nThe API offers no route to read this configuration back, so Terraform cannot\ndetect drift, cannot verify what the server currently has, and cannot import\nan existing configuration. Destroying this resource only removes it from\nstate; backups continue going to the last destination applied. Change the\ndestination by applying a new one.\n\nCustom PostgreSQL backup destination. The API has no read route, so\nTerraform cannot detect drift or import an existing configuration.\n[accessKey] / [secretKey] are sensitive — use `TfArg.variable`.',
  ),
  CatalogEntry(
    tfType: 'appwrite_postgresql_backups',
    className: 'DataAppwritePostgresqlBackups',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_postgresql_backups`.',
    constructorParams: <String>[
      'localName',
      'databaseId',
      'projectId',
      'queries',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_postgresql_backups`.\n\nLists the backups taken of a dedicated Appwrite PostgreSQL database.\nRestoring is not a Terraform operation, so this is how a backup ID is found\nfor a restore run through the Console or API.',
  ),
  CatalogEntry(
    tfType: 'appwrite_postgresql_branch',
    className: 'AppwritePostgresqlBranch',
    barrel: 'postgresql',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_postgresql_branch`.',
    constructorParams: <String>[
      'localName',
      'branchId',
      'databaseId',
      'projectId',
      'ttl',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['connection_string', 'password'],
    docComment:
        'Factory wrapper for `appwrite_postgresql_branch`.\n\nCreates a branch of a dedicated Appwrite PostgreSQL database: a copy that\nshares the parent\'s credentials but has its own host and database name.\n\nBranches have no update route, so changing any argument replaces the branch\nand discards its data. A branch given a `ttl` is deleted by the server when\nit expires; the next refresh then drops it from state and the following plan\nrecreates it.',
  ),
  CatalogEntry(
    tfType: 'appwrite_postgresql_database',
    className: 'AppwritePostgresqlDatabase',
    barrel: 'postgresql',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_postgresql_database`.',
    constructorParams: <String>[
      'localName',
      'idleTimeoutMinutes',
      'maintenanceWindowDay',
      'maintenanceWindowHourUtc',
      'name',
      'networkIdleTimeoutSeconds',
      'networkIpAllowlist',
      'pitr',
      'pitrRetentionDays',
      'projectId',
      'replicas',
      'specification',
      'sqlApiAllowedStatements',
      'sqlApiEnabled',
      'sqlApiMaxBytes',
      'sqlApiMaxRows',
      'sqlApiTimeoutSeconds',
      'status',
      'storageAutoscaling',
      'storageAutoscalingMaxGb',
      'storageAutoscalingThresholdPercent',
      'syncMode',
      'version',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['connection_password', 'connection_string'],
    docComment:
        'Factory wrapper for `appwrite_postgresql_database`.\n\nManages a dedicated Appwrite PostgreSQL database. A dedicated database runs\non infrastructure reserved for one project, so creating, resizing or\nupgrading one takes several minutes; Terraform waits for the database to\nsettle before continuing.\n\nDedicated PostgreSQL database (reserved compute, billed while it\nexists). Provisioning takes several minutes; apply waits for settle.',
  ),
  CatalogEntry(
    tfType: 'appwrite_postgresql_database',
    className: 'DataAppwritePostgresqlDatabase',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_postgresql_database`.',
    constructorParams: <String>['localName', 'id', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>['connection_password', 'connection_string'],
    docComment:
        'Factory wrapper for `appwrite_postgresql_database`.\n\nFetches a dedicated Appwrite PostgreSQL database by ID.',
  ),
  CatalogEntry(
    tfType: 'appwrite_postgresql_database_status',
    className: 'DataAppwritePostgresqlDatabaseStatus',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_postgresql_database_status`.',
    constructorParams: <String>['localName', 'databaseId', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_postgresql_database_status`.\n\nReads the live operational state of a dedicated Appwrite PostgreSQL\ndatabase: health, replication, connection counts and storage volumes.\n\nThese are measurements taken when Terraform refreshes, not configuration, so\nthey change between runs on their own. Use them for outputs and checks, not\nto drive resource arguments.',
  ),
  CatalogEntry(
    tfType: 'appwrite_postgresql_databases',
    className: 'DataAppwritePostgresqlDatabases',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_postgresql_databases`.',
    constructorParams: <String>['localName', 'projectId', 'queries'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_postgresql_databases`.\n\nLists the dedicated Appwrite PostgreSQL databases in a project. Connection\ncredentials are deliberately not included; read them from the singular\n`appwrite_postgresql_database` data source for the one database that needs\nthem, so a listing does not put every password into state.',
  ),
  CatalogEntry(
    tfType: 'appwrite_postgresql_extension',
    className: 'AppwritePostgresqlExtension',
    barrel: 'postgresql',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_postgresql_extension`.',
    constructorParams: <String>['localName', 'databaseId', 'name', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_postgresql_extension`.\n\nInstalls an extension into a dedicated Appwrite PostgreSQL database. Read\nthe installable names from the `available` list of the corresponding\nextensions data source.',
  ),
  CatalogEntry(
    tfType: 'appwrite_postgresql_extensions',
    className: 'DataAppwritePostgresqlExtensions',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_postgresql_extensions`.',
    constructorParams: <String>['localName', 'databaseId', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_postgresql_extensions`.\n\nLists the extensions installed on, and available to, a dedicated Appwrite\nPostgreSQL database.',
  ),
  CatalogEntry(
    tfType: 'appwrite_postgresql_pooler',
    className: 'AppwritePostgresqlPooler',
    barrel: 'postgresql',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_postgresql_pooler`.',
    constructorParams: <String>[
      'localName',
      'databaseId',
      'defaultPoolSize',
      'mode',
      'poolerCpuLimit',
      'poolerCpuRequest',
      'poolerMemoryLimit',
      'poolerMemoryRequest',
      'projectId',
      'readWriteSplitting',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_postgresql_pooler`.\n\nConfigures the connection pooler of a dedicated Appwrite PostgreSQL\ndatabase. The pooler exists for the lifetime of the database, so this\nresource only ever updates its settings: destroying it leaves the pooler\nrunning with its last applied configuration.',
  ),
  CatalogEntry(
    tfType: 'appwrite_postgresql_specifications',
    className: 'DataAppwritePostgresqlSpecifications',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_postgresql_specifications`.',
    constructorParams: <String>['localName', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_postgresql_specifications`.\n\nLists the compute specifications available for dedicated PostgreSQL\ndatabases, so a `specification` slug can be selected without hardcoding it.\nAvailability depends on the organization\'s billing plan; check `enabled`\nbefore using a slug.',
  ),
  CatalogEntry(
    tfType: 'appwrite_project',
    className: 'AppwriteProject',
    barrel: 'project',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_project`.',
    constructorParams: <String>[
      'localName',
      'name',
      'organizationId',
      'region',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_project`.\n\nManages an Appwrite project within an organization.\n\nAppwrite **project** — the top-level container for auth, databases,\nstorage, functions, and messaging.\n\nCreating a project is an organization-scoped operation: apply needs an\norganization API key (`APPWRITE_ORGANIZATION_API_KEY` env var, or the\nprovider\'s `organization_api_key`) and an organization id. Synth output\nnever contains credentials — see [AppwriteProvider].',
  ),
  CatalogEntry(
    tfType: 'appwrite_project_key',
    className: 'AppwriteProjectKey',
    barrel: 'project',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_project_key`.',
    constructorParams: <String>[
      'localName',
      'expire',
      'name',
      'organizationId',
      'projectId',
      'scopes',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['secret'],
    docComment:
        'Factory wrapper for `appwrite_project_key`.\n\nManages an Appwrite project API key.\n\nAppwrite **project API key**.\n\nThe create endpoint is gone upstream: mint the key in the Console and\n`terraform import` it. Read / update / delete still work. Synth output\nnever contains the secret — see [AppwriteProvider].',
  ),
  CatalogEntry(
    tfType: 'appwrite_proxy_rule',
    className: 'AppwriteProxyRule',
    barrel: 'proxy',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_proxy_rule`.',
    constructorParams: <String>[
      'localName',
      'branch',
      'domain',
      'projectId',
      'resourceId',
      'type',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_proxy_rule`.\n\nManages a custom domain proxy rule for an Appwrite site or function.',
  ),
  CatalogEntry(
    tfType: 'appwrite_site',
    className: 'AppwriteSite',
    barrel: 'sites',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_site`.',
    constructorParams: <String>[
      'localName',
      'adapter',
      'buildCommand',
      'buildRuntime',
      'buildSpecification',
      'deploymentRetention',
      'enabled',
      'fallbackFile',
      'framework',
      'installCommand',
      'installationId',
      'logging',
      'name',
      'outputDirectory',
      'projectId',
      'providerBranch',
      'providerRepositoryId',
      'providerRootDirectory',
      'providerSilentMode',
      'runtimeSpecification',
      'startCommand',
      'timeout',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_site`.\n\nManages an Appwrite site.',
  ),
  CatalogEntry(
    tfType: 'appwrite_site',
    className: 'DataAppwriteSite',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_site`.',
    constructorParams: <String>['localName', 'id', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_site`.\n\nFetches an Appwrite site by ID.',
  ),
  CatalogEntry(
    tfType: 'appwrite_site_deployment',
    className: 'AppwriteSiteDeployment',
    barrel: 'sites',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_site_deployment`.',
    constructorParams: <String>[
      'localName',
      'activate',
      'buildCommand',
      'codeHash',
      'codePath',
      'installCommand',
      'outputDirectory',
      'owner',
      'projectId',
      'reference',
      'repository',
      'rootDirectory',
      'siteId',
      'sourceType',
      'type',
      'waitForReady',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_site_deployment`.\n\nManages an Appwrite site deployment.',
  ),
  CatalogEntry(
    tfType: 'appwrite_site_variable',
    className: 'AppwriteSiteVariable',
    barrel: 'sites',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_site_variable`.',
    constructorParams: <String>[
      'localName',
      'key',
      'projectId',
      'secret',
      'siteId',
      'value',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['value'],
    docComment:
        'Factory wrapper for `appwrite_site_variable`.\n\nManages an Appwrite site environment variable.\n\nSite environment variable. [value] is sensitive — pass\n`TfArg.variable` so the secret never enters synth output.',
  ),
  CatalogEntry(
    tfType: 'appwrite_storage_bucket',
    className: 'AppwriteStorageBucket',
    barrel: 'storage',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_storage_bucket`.',
    constructorParams: <String>[
      'localName',
      'name',
      'enabled',
      'fileSecurity',
      'maximumFileSize',
      'allowedFileExtensions',
      'compression',
      'encryption',
      'antivirus',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_storage_bucket`.\n\nManages an Appwrite storage bucket.\n\nAppwrite **storage bucket** — file storage with per-bucket security,\nsize limits, allowed extensions, compression, encryption, and\nantivirus toggles.\n\nProject-scoped: apply resolves the target project from the provider\'s\n`project_id` (or `APPWRITE_PROJECT_ID`).',
  ),
  CatalogEntry(
    tfType: 'appwrite_storage_bucket',
    className: 'DataAppwriteStorageBucket',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_storage_bucket`.',
    constructorParams: <String>['localName', 'id', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_storage_bucket`.\n\nFetches an Appwrite storage bucket by ID.',
  ),
  CatalogEntry(
    tfType: 'appwrite_storage_file',
    className: 'AppwriteStorageFile',
    barrel: 'storage',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_storage_file`.',
    constructorParams: <String>[
      'localName',
      'bucketId',
      'filePath',
      'name',
      'permissions',
      'projectId',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_storage_file`.\n\nManages a file in an Appwrite storage bucket.\n\nAppwrite **storage file** — uploads a local file into a bucket.\n\n[filePath] is resolved at apply time on the machine running Terraform.',
  ),
  CatalogEntry(
    tfType: 'appwrite_tablesdb',
    className: 'AppwriteTablesdb',
    barrel: 'tablesdb',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_tablesdb`.',
    constructorParams: <String>['localName', 'enabled', 'name', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_tablesdb`.\n\nManages an Appwrite database.',
  ),
  CatalogEntry(
    tfType: 'appwrite_tablesdb',
    className: 'DataAppwriteTablesdb',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_tablesdb`.',
    constructorParams: <String>['localName', 'id', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_tablesdb`.\n\nFetches an Appwrite database by ID.',
  ),
  CatalogEntry(
    tfType: 'appwrite_tablesdb_column',
    className: 'AppwriteTablesdbColumn',
    barrel: 'tablesdb',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_tablesdb_column`.',
    constructorParams: <String>[
      'localName',
      'databaseId',
      'tableId',
      'type',
      'key',
      'columnRequired',
      'defaultValue',
      'size',
      'array',
      'elements',
      'encrypt',
      'floatMax',
      'floatMin',
      'max',
      'min',
      'onDelete',
      'relatedTableId',
      'relationshipType',
      'twoWay',
      'twoWayKey',
      'projectId',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_tablesdb_column`.\n\nManages a column in an Appwrite table.',
  ),
  CatalogEntry(
    tfType: 'appwrite_tablesdb_index',
    className: 'AppwriteTablesdbIndex',
    barrel: 'tablesdb',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_tablesdb_index`.',
    constructorParams: <String>[
      'localName',
      'columns',
      'databaseId',
      'key',
      'orders',
      'projectId',
      'tableId',
      'type',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_tablesdb_index`.\n\nManages an index on an Appwrite table.',
  ),
  CatalogEntry(
    tfType: 'appwrite_tablesdb_row',
    className: 'AppwriteTablesdbRow',
    barrel: 'tablesdb',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_tablesdb_row`.',
    constructorParams: <String>[
      'localName',
      'data',
      'databaseId',
      'permissions',
      'projectId',
      'tableId',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_tablesdb_row`.\n\nManages a row in an Appwrite tablesdb table.',
  ),
  CatalogEntry(
    tfType: 'appwrite_tablesdb_table',
    className: 'AppwriteTablesdbTable',
    barrel: 'tablesdb',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_tablesdb_table`.',
    constructorParams: <String>[
      'localName',
      'databaseId',
      'enabled',
      'name',
      'permissions',
      'projectId',
      'rowSecurity',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_tablesdb_table`.\n\nManages an Appwrite table within a database.',
  ),
  CatalogEntry(
    tfType: 'appwrite_webhook',
    className: 'AppwriteWebhook',
    barrel: 'webhooks',
    kind: CatalogKind.resource,
    summary: 'Factory wrapper for `appwrite_webhook`.',
    constructorParams: <String>[
      'localName',
      'authPassword',
      'authUsername',
      'enabled',
      'events',
      'name',
      'projectId',
      'tls',
      'url',
    ],
    nestedTypes: <String>[],
    sensitiveFields: <String>['auth_password', 'secret'],
    docComment:
        'Factory wrapper for `appwrite_webhook`.\n\nManages an Appwrite webhook.',
  ),
  CatalogEntry(
    tfType: 'appwrite_webhook',
    className: 'DataAppwriteWebhook',
    barrel: 'data',
    kind: CatalogKind.dataSource,
    summary: 'Factory wrapper for `appwrite_webhook`.',
    constructorParams: <String>['localName', 'id', 'projectId'],
    nestedTypes: <String>[],
    sensitiveFields: <String>[],
    docComment:
        'Factory wrapper for `appwrite_webhook`.\n\nFetches an Appwrite webhook by ID.',
  ),
];
