name: terradart_example_firebaserules_quickstart
description: Firebase Security Rules ruleset quickstart (no release).
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  terradart_core: ^0.25.2
  terradart_google: ^0.25.2

dev_dependencies:
  lints: ^6.0.0
