// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
/// AWS Application Auto Scaling.
library;

export 'src/appautoscaling/aws_appautoscaling_policy.dart'
    show
        AppautoscalingPolicyPolicyType,
        AppautoscalingPolicyPredictiveScalingPolicyConfiguration,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMaxCapacityBreachBehavior,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecification,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedCapacityMetricSpecification,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQuery,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueryMetricStat,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueryMetricStatMetric,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueryMetricStatMetricDimension,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedLoadMetricSpecification,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQuery,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueryMetricStat,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueryMetricStatMetric,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueryMetricStatMetricDimension,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedScalingMetricSpecification,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQuery,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueryMetricStat,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueryMetricStatMetric,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueryMetricStatMetricDimension,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationPredefinedLoadMetricSpecification,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationPredefinedMetricPairSpecification,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMetricSpecificationPredefinedScalingMetricSpecification,
        AppautoscalingPolicyPredictiveScalingPolicyConfigurationMode,
        AppautoscalingPolicyStepScalingPolicyConfiguration,
        AppautoscalingPolicyStepScalingPolicyConfigurationAdjustmentType,
        AppautoscalingPolicyStepScalingPolicyConfigurationMetricAggregationType,
        AppautoscalingPolicyStepScalingPolicyConfigurationStepAdjustment,
        AppautoscalingPolicyTargetTrackingScalingPolicyConfiguration,
        AppautoscalingPolicyTargetTrackingScalingPolicyConfigurationCustomizedMetricSpecification,
        AppautoscalingPolicyTargetTrackingScalingPolicyConfigurationCustomizedMetricSpecificationDimensions,
        AppautoscalingPolicyTargetTrackingScalingPolicyConfigurationCustomizedMetricSpecificationMetrics,
        AppautoscalingPolicyTargetTrackingScalingPolicyConfigurationCustomizedMetricSpecificationMetricsMetricStat,
        AppautoscalingPolicyTargetTrackingScalingPolicyConfigurationCustomizedMetricSpecificationMetricsMetricStatMetric,
        AppautoscalingPolicyTargetTrackingScalingPolicyConfigurationCustomizedMetricSpecificationMetricsMetricStatMetricDimensions,
        AppautoscalingPolicyTargetTrackingScalingPolicyConfigurationCustomizedMetricSpecificationOrPredefinedMetricSpecification,
        AppautoscalingPolicyTargetTrackingScalingPolicyConfigurationCustomizedMetricSpecificationOrPredefinedMetricSpecificationCustomizedMetricSpecification,
        AppautoscalingPolicyTargetTrackingScalingPolicyConfigurationCustomizedMetricSpecificationOrPredefinedMetricSpecificationPredefinedMetricSpecification,
        AppautoscalingPolicyTargetTrackingScalingPolicyConfigurationCustomizedMetricSpecificationStatistic,
        AppautoscalingPolicyTargetTrackingScalingPolicyConfigurationPredefinedMetricSpecification,
        AwsAppautoscalingPolicy;
export 'src/appautoscaling/aws_appautoscaling_scheduled_action.dart'
    show
        AppautoscalingScheduledActionScalableTargetAction,
        AwsAppautoscalingScheduledAction;
export 'src/appautoscaling/aws_appautoscaling_target.dart'
    show AppautoscalingTargetSuspendedState, AwsAppautoscalingTarget;
