// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
/// AWS ARC Region switch plans.
library;

export 'package:terradart_core/terradart_core.dart';
export 'src/arcregionswitch/aws_arcregionswitch_plan.dart'
    show
        ArcregionswitchPlanAction,
        ArcregionswitchPlanAlarmType,
        ArcregionswitchPlanArcRoutingControlConfig,
        ArcregionswitchPlanAsg,
        ArcregionswitchPlanAssociatedAlarms,
        ArcregionswitchPlanAuroraProvisionedScalingConfig,
        ArcregionswitchPlanAuroraServerlessScalingConfig,
        ArcregionswitchPlanBehavior,
        ArcregionswitchPlanCondition,
        ArcregionswitchPlanConditions,
        ArcregionswitchPlanCustomActionLambdaConfig,
        ArcregionswitchPlanCustomActionLambdaConfigUngraceful,
        ArcregionswitchPlanDocumentDbConfig,
        ArcregionswitchPlanDocumentDbConfigUngraceful,
        ArcregionswitchPlanEc2AsgCapacityIncreaseConfig,
        ArcregionswitchPlanEc2AsgCapacityIncreaseConfigCapacityMonitoringApproach,
        ArcregionswitchPlanEc2AsgCapacityIncreaseConfigUngraceful,
        ArcregionswitchPlanEcsCapacityIncreaseConfig,
        ArcregionswitchPlanEcsCapacityIncreaseConfigCapacityMonitoringApproach,
        ArcregionswitchPlanEksClusters,
        ArcregionswitchPlanEksResourceScalingConfig,
        ArcregionswitchPlanEksResourceScalingConfigCapacityMonitoringApproach,
        ArcregionswitchPlanExecutionApprovalConfig,
        ArcregionswitchPlanExecutionBlockType,
        ArcregionswitchPlanGlobalAuroraConfig,
        ArcregionswitchPlanKubernetesResourceType,
        ArcregionswitchPlanLambda,
        ArcregionswitchPlanLambdaEventSourceMappingConfig,
        ArcregionswitchPlanLambdaEventSourceMappingConfigAction,
        ArcregionswitchPlanNeptuneGlobalDatabaseConfig,
        ArcregionswitchPlanParallelConfig,
        ArcregionswitchPlanParallelConfigStep,
        ArcregionswitchPlanRdsCreateCrossRegionReadReplicaConfig,
        ArcregionswitchPlanRdsPromoteReadReplicaConfig,
        ArcregionswitchPlanRecordSet,
        ArcregionswitchPlanRecoveryApproach,
        ArcregionswitchPlanRegionAndRoutingControls,
        ArcregionswitchPlanRegionEventSourceMapping,
        ArcregionswitchPlanRegionSwitchPlanConfig,
        ArcregionswitchPlanRegionToRun,
        ArcregionswitchPlanReportConfiguration,
        ArcregionswitchPlanReportOutput,
        ArcregionswitchPlanResources,
        ArcregionswitchPlanRoute53HealthCheckConfig,
        ArcregionswitchPlanRoutingControl,
        ArcregionswitchPlanS3Configuration,
        ArcregionswitchPlanScalingResources,
        ArcregionswitchPlanService,
        ArcregionswitchPlanState,
        ArcregionswitchPlanStep,
        ArcregionswitchPlanTriggers,
        ArcregionswitchPlanUngracefulBehavior,
        ArcregionswitchPlanUngracefulUngraceful,
        ArcregionswitchPlanWorkflow,
        ArcregionswitchPlanWorkflowTargetAction,
        AwsArcregionswitchPlan;
export 'src/data/aws_arcregionswitch_plan.dart' show DataAwsArcregionswitchPlan;
export 'src/data/aws_arcregionswitch_route53_health_checks.dart'
    show DataAwsArcregionswitchRoute53HealthChecks;
