// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
/// AWS EC2 Auto Scaling and launch configurations.
library;

export 'src/autoscaling/aws_autoscaling_attachment.dart'
    show
        AutoscalingAttachmentElbOption,
        AutoscalingAttachmentElbOrLbTargetGroupArn,
        AutoscalingAttachmentLbTargetGroupArnOption,
        AwsAutoscalingAttachment;
export 'src/autoscaling/aws_autoscaling_group.dart'
    show
        AutoscalingGroupAvailabilityZoneDistribution,
        AutoscalingGroupAvailabilityZoneDistributionCapacityDistributionStrategy,
        AutoscalingGroupAvailabilityZonesOption,
        AutoscalingGroupAvailabilityZonesOrVpcZoneIdentifier,
        AutoscalingGroupCapacityReservationSpecification,
        AutoscalingGroupCapacityReservationSpecificationCapacityReservationPreference,
        AutoscalingGroupCapacityReservationSpecificationCapacityReservationTarget,
        AutoscalingGroupCapacityReservationSpecificationCapacityReservationTargetCapacityReservationIdsOption,
        AutoscalingGroupCapacityReservationSpecificationCapacityReservationTargetCapacityReservationIdsOrCapacityReservationResourceGroupArns,
        AutoscalingGroupCapacityReservationSpecificationCapacityReservationTargetCapacityReservationResourceGroupArnsOption,
        AutoscalingGroupDesiredCapacityType,
        AutoscalingGroupInitialLifecycleHook,
        AutoscalingGroupInitialLifecycleHookDefaultResult,
        AutoscalingGroupInitialLifecycleHookLifecycleTransition,
        AutoscalingGroupInstanceLifecyclePolicy,
        AutoscalingGroupInstanceLifecyclePolicyRetentionTriggers,
        AutoscalingGroupInstanceLifecyclePolicyRetentionTriggersTerminateHookAbandon,
        AutoscalingGroupInstanceMaintenancePolicy,
        AutoscalingGroupInstanceRefresh,
        AutoscalingGroupInstanceRefreshPreferences,
        AutoscalingGroupInstanceRefreshPreferencesAlarmSpecification,
        AutoscalingGroupInstanceRefreshPreferencesScaleInProtectedInstances,
        AutoscalingGroupInstanceRefreshPreferencesStandbyInstances,
        AutoscalingGroupInstanceRefreshStrategy,
        AutoscalingGroupLaunchConfigurationOption,
        AutoscalingGroupLaunchConfigurationOrLaunchTemplateOrMixedInstancesPolicy,
        AutoscalingGroupLaunchTemplate,
        AutoscalingGroupLaunchTemplateIdOption,
        AutoscalingGroupLaunchTemplateIdOrName,
        AutoscalingGroupLaunchTemplateNameOption,
        AutoscalingGroupLaunchTemplateOption,
        AutoscalingGroupMixedInstancesPolicy,
        AutoscalingGroupMixedInstancesPolicyInstancesDistribution,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplate,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateLaunchTemplateSpecification,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverride,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirements,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsAcceleratorCount,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsAcceleratorManufacturers,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsAcceleratorNames,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsAcceleratorTotalMemoryMib,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsAcceleratorTypes,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsBareMetal,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsBaselineEbsBandwidthMbps,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsBurstablePerformance,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsCpuManufacturers,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsInstanceGenerations,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsLocalStorage,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsLocalStorageTypes,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsMemoryGibPerVcpu,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsMemoryMib,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsNetworkBandwidthGbps,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsNetworkInterfaceCount,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsTotalLocalStorageGb,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideInstanceRequirementsVcpuCount,
        AutoscalingGroupMixedInstancesPolicyLaunchTemplateOverrideLaunchTemplateSpecification,
        AutoscalingGroupMixedInstancesPolicyOption,
        AutoscalingGroupNameOption,
        AutoscalingGroupNameOrNamePrefix,
        AutoscalingGroupNamePrefixOption,
        AutoscalingGroupTag,
        AutoscalingGroupTrafficSource,
        AutoscalingGroupVpcZoneIdentifierOption,
        AutoscalingGroupWarmPool,
        AutoscalingGroupWarmPoolInstanceReusePolicy,
        AutoscalingGroupWarmPoolPoolState,
        AwsAutoscalingGroup;
export 'src/autoscaling/aws_autoscaling_group_tag.dart'
    show AutoscalingGroupTagTag, AwsAutoscalingGroupTag;
export 'src/autoscaling/aws_autoscaling_lifecycle_hook.dart'
    show
        AutoscalingLifecycleHookDefaultResult,
        AutoscalingLifecycleHookLifecycleTransition,
        AwsAutoscalingLifecycleHook;
export 'src/autoscaling/aws_autoscaling_notification.dart'
    show AwsAutoscalingNotification;
export 'src/autoscaling/aws_autoscaling_policy.dart'
    show
        AutoscalingPolicyPolicyType,
        AutoscalingPolicyPredictiveScalingConfiguration,
        AutoscalingPolicyPredictiveScalingConfigurationMaxCapacityBreachBehavior,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecification,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecification,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueries,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesMetricStat,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesMetricStatMetric,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedCapacityMetricSpecificationMetricDataQueriesMetricStatMetricDimensions,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecification,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueries,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesMetricStat,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesMetricStatMetric,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedLoadMetricSpecificationMetricDataQueriesMetricStatMetricDimensions,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecification,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueries,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesMetricStat,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesMetricStatMetric,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationMetricDataQueriesMetricStatMetricDimensions,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationOption,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationCustomizedScalingMetricSpecificationOrPredefinedScalingMetricSpecification,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecification,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationPredefinedLoadMetricSpecificationPredefinedMetricType,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecification,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationPredefinedMetricPairSpecificationPredefinedMetricType,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecification,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationOption,
        AutoscalingPolicyPredictiveScalingConfigurationMetricSpecificationPredefinedScalingMetricSpecificationPredefinedMetricType,
        AutoscalingPolicyPredictiveScalingConfigurationMode,
        AutoscalingPolicyScalingAdjustmentOption,
        AutoscalingPolicyScalingAdjustmentOrStepAdjustment,
        AutoscalingPolicyStepAdjustment,
        AutoscalingPolicyStepAdjustmentOption,
        AutoscalingPolicyTargetTrackingConfiguration,
        AutoscalingPolicyTargetTrackingConfigurationCustomizedMetricSpecification,
        AutoscalingPolicyTargetTrackingConfigurationCustomizedMetricSpecificationMetricDimension,
        AutoscalingPolicyTargetTrackingConfigurationCustomizedMetricSpecificationMetrics,
        AutoscalingPolicyTargetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStat,
        AutoscalingPolicyTargetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatMetric,
        AutoscalingPolicyTargetTrackingConfigurationCustomizedMetricSpecificationMetricsMetricStatMetricDimensions,
        AutoscalingPolicyTargetTrackingConfigurationCustomizedMetricSpecificationOption,
        AutoscalingPolicyTargetTrackingConfigurationCustomizedMetricSpecificationOrPredefinedMetricSpecification,
        AutoscalingPolicyTargetTrackingConfigurationPredefinedMetricSpecification,
        AutoscalingPolicyTargetTrackingConfigurationPredefinedMetricSpecificationOption,
        AwsAutoscalingPolicy;
export 'src/autoscaling/aws_autoscaling_schedule.dart'
    show AwsAutoscalingSchedule;
export 'src/autoscaling/aws_autoscaling_traffic_source_attachment.dart'
    show
        AutoscalingTrafficSourceAttachmentTrafficSource,
        AwsAutoscalingTrafficSourceAttachment;
export 'src/autoscaling/aws_launch_configuration.dart'
    show
        AwsLaunchConfiguration,
        LaunchConfigurationEbsBlockDevice,
        LaunchConfigurationEphemeralBlockDevice,
        LaunchConfigurationMetadataOptions,
        LaunchConfigurationMetadataOptionsHttpEndpoint,
        LaunchConfigurationMetadataOptionsHttpTokens,
        LaunchConfigurationNameOption,
        LaunchConfigurationNameOrNamePrefix,
        LaunchConfigurationNamePrefixOption,
        LaunchConfigurationRootBlockDevice,
        LaunchConfigurationUserDataBase64Option,
        LaunchConfigurationUserDataOption,
        LaunchConfigurationUserDataOrUserDataBase64;
