// GENERATED FILE - DO NOT EDIT
// Run `terradart wrap` to regenerate.
/// AWS SageMaker.
library;

export 'src/sagemaker/aws_sagemaker_algorithm.dart'
    show
        AwsSagemakerAlgorithm,
        SagemakerAlgorithmInferenceSpecification,
        SagemakerAlgorithmInferenceSpecificationContainers,
        SagemakerAlgorithmInferenceSpecificationContainersAdditionalS3DataSource,
        SagemakerAlgorithmInferenceSpecificationContainersBaseModel,
        SagemakerAlgorithmInferenceSpecificationContainersModelDataSource,
        SagemakerAlgorithmInferenceSpecificationContainersModelDataSourceS3DataSource,
        SagemakerAlgorithmInferenceSpecificationContainersModelDataSourceS3DataSourceHubAccessConfig,
        SagemakerAlgorithmInferenceSpecificationContainersModelDataSourceS3DataSourceModelAccessConfig,
        SagemakerAlgorithmInferenceSpecificationContainersModelInput,
        SagemakerAlgorithmTrainingSpecification,
        SagemakerAlgorithmTrainingSpecificationAdditionalS3DataSource,
        SagemakerAlgorithmTrainingSpecificationMetricDefinitions,
        SagemakerAlgorithmTrainingSpecificationSupportedHyperParameters,
        SagemakerAlgorithmTrainingSpecificationSupportedHyperParametersRange,
        SagemakerAlgorithmTrainingSpecificationSupportedHyperParametersRangeCategoricalParameterRangeSpecification,
        SagemakerAlgorithmTrainingSpecificationSupportedHyperParametersRangeContinuousParameterRangeSpecification,
        SagemakerAlgorithmTrainingSpecificationSupportedHyperParametersRangeIntegerParameterRangeSpecification,
        SagemakerAlgorithmTrainingSpecificationSupportedTuningJobObjectiveMetrics,
        SagemakerAlgorithmTrainingSpecificationTrainingChannels,
        SagemakerAlgorithmValidationSpecification,
        SagemakerAlgorithmValidationSpecificationValidationProfiles,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinition,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinitionInputDataConfig,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinitionInputDataConfigDataSource,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinitionInputDataConfigDataSourceFileSystemDataSource,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinitionInputDataConfigDataSourceS3DataSource,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinitionInputDataConfigDataSourceS3DataSourceHubAccessConfig,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinitionInputDataConfigDataSourceS3DataSourceModelAccessConfig,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinitionInputDataConfigShuffleConfig,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinitionOutputDataConfig,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinitionResourceConfig,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinitionResourceConfigInstanceGroups,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinitionResourceConfigInstancePlacementConfig,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinitionResourceConfigInstancePlacementConfigPlacementSpecifications,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTrainingJobDefinitionStoppingCondition,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTransformJobDefinition,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTransformJobDefinitionTransformInput,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTransformJobDefinitionTransformInputDataSource,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTransformJobDefinitionTransformInputDataSourceS3DataSource,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTransformJobDefinitionTransformOutput,
        SagemakerAlgorithmValidationSpecificationValidationProfilesTransformJobDefinitionTransformResources;
export 'src/sagemaker/aws_sagemaker_app.dart'
    show AwsSagemakerApp, SagemakerAppResourceSpec;
export 'src/sagemaker/aws_sagemaker_app_image_config.dart'
    show
        AwsSagemakerAppImageConfig,
        SagemakerAppImageConfigCodeEditorAppImageConfig,
        SagemakerAppImageConfigCodeEditorAppImageConfigContainerConfig,
        SagemakerAppImageConfigCodeEditorAppImageConfigFileSystemConfig,
        SagemakerAppImageConfigJupyterLabImageConfig,
        SagemakerAppImageConfigJupyterLabImageConfigContainerConfig,
        SagemakerAppImageConfigJupyterLabImageConfigFileSystemConfig,
        SagemakerAppImageConfigKernelGatewayImageConfig,
        SagemakerAppImageConfigKernelGatewayImageConfigFileSystemConfig,
        SagemakerAppImageConfigKernelGatewayImageConfigKernelSpec;
export 'src/sagemaker/aws_sagemaker_code_repository.dart'
    show AwsSagemakerCodeRepository, SagemakerCodeRepositoryGitConfig;
export 'src/sagemaker/aws_sagemaker_data_quality_job_definition.dart'
    show
        AwsSagemakerDataQualityJobDefinition,
        SagemakerDataQualityJobDefinitionDataQualityAppSpecification,
        SagemakerDataQualityJobDefinitionDataQualityBaselineConfig,
        SagemakerDataQualityJobDefinitionDataQualityBaselineConfigConstraintsResource,
        SagemakerDataQualityJobDefinitionDataQualityBaselineConfigStatisticsResource,
        SagemakerDataQualityJobDefinitionDataQualityJobInput,
        SagemakerDataQualityJobDefinitionDataQualityJobInputBatchTransformInput,
        SagemakerDataQualityJobDefinitionDataQualityJobInputBatchTransformInputDatasetFormat,
        SagemakerDataQualityJobDefinitionDataQualityJobInputBatchTransformInputDatasetFormatCsv,
        SagemakerDataQualityJobDefinitionDataQualityJobInputBatchTransformInputDatasetFormatJson,
        SagemakerDataQualityJobDefinitionDataQualityJobInputEndpointInput,
        SagemakerDataQualityJobDefinitionDataQualityJobOutputConfig,
        SagemakerDataQualityJobDefinitionDataQualityJobOutputConfigMonitoringOutputs,
        SagemakerDataQualityJobDefinitionDataQualityJobOutputConfigMonitoringOutputsS3Output,
        SagemakerDataQualityJobDefinitionJobResources,
        SagemakerDataQualityJobDefinitionJobResourcesClusterConfig,
        SagemakerDataQualityJobDefinitionNetworkConfig,
        SagemakerDataQualityJobDefinitionNetworkConfigVpcConfig,
        SagemakerDataQualityJobDefinitionStoppingCondition;
export 'src/sagemaker/aws_sagemaker_device.dart'
    show AwsSagemakerDevice, SagemakerDeviceDevice;
export 'src/sagemaker/aws_sagemaker_device_fleet.dart'
    show AwsSagemakerDeviceFleet, SagemakerDeviceFleetOutputConfig;
export 'src/sagemaker/aws_sagemaker_domain.dart'
    show
        AwsSagemakerDomain,
        SagemakerDomainDefaultSpaceSettings,
        SagemakerDomainDefaultSpaceSettingsCustomFileSystemConfig,
        SagemakerDomainDefaultSpaceSettingsCustomFileSystemConfigEfsFileSystemConfig,
        SagemakerDomainDefaultSpaceSettingsCustomPosixUserConfig,
        SagemakerDomainDefaultSpaceSettingsJupyterLabAppSettings,
        SagemakerDomainDefaultSpaceSettingsJupyterLabAppSettingsAppLifecycleManagement,
        SagemakerDomainDefaultSpaceSettingsJupyterLabAppSettingsAppLifecycleManagementIdleSettings,
        SagemakerDomainDefaultSpaceSettingsJupyterLabAppSettingsCodeRepository,
        SagemakerDomainDefaultSpaceSettingsJupyterLabAppSettingsCustomImage,
        SagemakerDomainDefaultSpaceSettingsJupyterLabAppSettingsDefaultResourceSpec,
        SagemakerDomainDefaultSpaceSettingsJupyterLabAppSettingsEmrSettings,
        SagemakerDomainDefaultSpaceSettingsJupyterServerAppSettings,
        SagemakerDomainDefaultSpaceSettingsJupyterServerAppSettingsCodeRepository,
        SagemakerDomainDefaultSpaceSettingsJupyterServerAppSettingsDefaultResourceSpec,
        SagemakerDomainDefaultSpaceSettingsKernelGatewayAppSettings,
        SagemakerDomainDefaultSpaceSettingsKernelGatewayAppSettingsCustomImage,
        SagemakerDomainDefaultSpaceSettingsKernelGatewayAppSettingsDefaultResourceSpec,
        SagemakerDomainDefaultSpaceSettingsSpaceStorageSettings,
        SagemakerDomainDefaultSpaceSettingsSpaceStorageSettingsDefaultEbsStorageSettings,
        SagemakerDomainDefaultUserSettings,
        SagemakerDomainDefaultUserSettingsCanvasAppSettings,
        SagemakerDomainDefaultUserSettingsCanvasAppSettingsDirectDeploySettings,
        SagemakerDomainDefaultUserSettingsCanvasAppSettingsEmrServerlessSettings,
        SagemakerDomainDefaultUserSettingsCanvasAppSettingsGenerativeAiSettings,
        SagemakerDomainDefaultUserSettingsCanvasAppSettingsIdentityProviderOauthSettings,
        SagemakerDomainDefaultUserSettingsCanvasAppSettingsKendraSettings,
        SagemakerDomainDefaultUserSettingsCanvasAppSettingsModelRegisterSettings,
        SagemakerDomainDefaultUserSettingsCanvasAppSettingsTimeSeriesForecastingSettings,
        SagemakerDomainDefaultUserSettingsCanvasAppSettingsWorkspaceSettings,
        SagemakerDomainDefaultUserSettingsCodeEditorAppSettings,
        SagemakerDomainDefaultUserSettingsCodeEditorAppSettingsAppLifecycleManagement,
        SagemakerDomainDefaultUserSettingsCodeEditorAppSettingsAppLifecycleManagementIdleSettings,
        SagemakerDomainDefaultUserSettingsCodeEditorAppSettingsCustomImage,
        SagemakerDomainDefaultUserSettingsCodeEditorAppSettingsDefaultResourceSpec,
        SagemakerDomainDefaultUserSettingsCustomFileSystemConfig,
        SagemakerDomainDefaultUserSettingsCustomFileSystemConfigEfsFileSystemConfig,
        SagemakerDomainDefaultUserSettingsCustomPosixUserConfig,
        SagemakerDomainDefaultUserSettingsJupyterLabAppSettings,
        SagemakerDomainDefaultUserSettingsJupyterLabAppSettingsAppLifecycleManagement,
        SagemakerDomainDefaultUserSettingsJupyterLabAppSettingsAppLifecycleManagementIdleSettings,
        SagemakerDomainDefaultUserSettingsJupyterLabAppSettingsCodeRepository,
        SagemakerDomainDefaultUserSettingsJupyterLabAppSettingsCustomImage,
        SagemakerDomainDefaultUserSettingsJupyterLabAppSettingsDefaultResourceSpec,
        SagemakerDomainDefaultUserSettingsJupyterLabAppSettingsEmrSettings,
        SagemakerDomainDefaultUserSettingsJupyterServerAppSettings,
        SagemakerDomainDefaultUserSettingsJupyterServerAppSettingsCodeRepository,
        SagemakerDomainDefaultUserSettingsJupyterServerAppSettingsDefaultResourceSpec,
        SagemakerDomainDefaultUserSettingsKernelGatewayAppSettings,
        SagemakerDomainDefaultUserSettingsKernelGatewayAppSettingsCustomImage,
        SagemakerDomainDefaultUserSettingsKernelGatewayAppSettingsDefaultResourceSpec,
        SagemakerDomainDefaultUserSettingsRSessionAppSettings,
        SagemakerDomainDefaultUserSettingsRSessionAppSettingsCustomImage,
        SagemakerDomainDefaultUserSettingsRSessionAppSettingsDefaultResourceSpec,
        SagemakerDomainDefaultUserSettingsRStudioServerProAppSettings,
        SagemakerDomainDefaultUserSettingsSharingSettings,
        SagemakerDomainDefaultUserSettingsSpaceStorageSettings,
        SagemakerDomainDefaultUserSettingsSpaceStorageSettingsDefaultEbsStorageSettings,
        SagemakerDomainDefaultUserSettingsStudioWebPortalSettings,
        SagemakerDomainDefaultUserSettingsTensorBoardAppSettings,
        SagemakerDomainDefaultUserSettingsTensorBoardAppSettingsDefaultResourceSpec,
        SagemakerDomainDomainSettings,
        SagemakerDomainDomainSettingsDockerSettings,
        SagemakerDomainDomainSettingsRStudioServerProDomainSettings,
        SagemakerDomainDomainSettingsRStudioServerProDomainSettingsDefaultResourceSpec,
        SagemakerDomainDomainSettingsTrustedIdentityPropagationSettings,
        SagemakerDomainRetentionPolicy;
export 'src/sagemaker/aws_sagemaker_endpoint.dart'
    show
        AwsSagemakerEndpoint,
        SagemakerEndpointDeploymentConfig,
        SagemakerEndpointDeploymentConfigAutoRollbackConfiguration,
        SagemakerEndpointDeploymentConfigAutoRollbackConfigurationAlarms,
        SagemakerEndpointDeploymentConfigBlueGreenUpdatePolicy,
        SagemakerEndpointDeploymentConfigBlueGreenUpdatePolicyTrafficRoutingConfiguration,
        SagemakerEndpointDeploymentConfigBlueGreenUpdatePolicyTrafficRoutingConfigurationCanarySize,
        SagemakerEndpointDeploymentConfigBlueGreenUpdatePolicyTrafficRoutingConfigurationLinearStepSize,
        SagemakerEndpointDeploymentConfigRollingUpdatePolicy,
        SagemakerEndpointDeploymentConfigRollingUpdatePolicyMaximumBatchSize,
        SagemakerEndpointDeploymentConfigRollingUpdatePolicyRollbackMaximumBatchSize;
export 'src/sagemaker/aws_sagemaker_endpoint_configuration.dart'
    show
        AwsSagemakerEndpointConfiguration,
        SagemakerEndpointConfigurationAsyncInferenceConfig,
        SagemakerEndpointConfigurationAsyncInferenceConfigClientConfig,
        SagemakerEndpointConfigurationAsyncInferenceConfigOutputConfig,
        SagemakerEndpointConfigurationAsyncInferenceConfigOutputConfigNotificationConfig,
        SagemakerEndpointConfigurationDataCaptureConfig,
        SagemakerEndpointConfigurationDataCaptureConfigCaptureContentTypeHeader,
        SagemakerEndpointConfigurationDataCaptureConfigCaptureOptions,
        SagemakerEndpointConfigurationProductionVariants,
        SagemakerEndpointConfigurationProductionVariantsCapacityReservationConfig,
        SagemakerEndpointConfigurationProductionVariantsCoreDumpConfig,
        SagemakerEndpointConfigurationProductionVariantsManagedInstanceScaling,
        SagemakerEndpointConfigurationProductionVariantsRoutingConfig,
        SagemakerEndpointConfigurationProductionVariantsServerlessConfig,
        SagemakerEndpointConfigurationShadowProductionVariants,
        SagemakerEndpointConfigurationShadowProductionVariantsCapacityReservationConfig,
        SagemakerEndpointConfigurationShadowProductionVariantsCoreDumpConfig,
        SagemakerEndpointConfigurationShadowProductionVariantsManagedInstanceScaling,
        SagemakerEndpointConfigurationShadowProductionVariantsRoutingConfig,
        SagemakerEndpointConfigurationShadowProductionVariantsServerlessConfig;
export 'src/sagemaker/aws_sagemaker_feature_group.dart'
    show
        AwsSagemakerFeatureGroup,
        SagemakerFeatureGroupFeatureDefinition,
        SagemakerFeatureGroupFeatureDefinitionCollectionConfig,
        SagemakerFeatureGroupFeatureDefinitionCollectionConfigVectorConfig,
        SagemakerFeatureGroupOfflineStoreConfig,
        SagemakerFeatureGroupOfflineStoreConfigDataCatalogConfig,
        SagemakerFeatureGroupOfflineStoreConfigS3StorageConfig,
        SagemakerFeatureGroupOnlineStoreConfig,
        SagemakerFeatureGroupOnlineStoreConfigSecurityConfig,
        SagemakerFeatureGroupOnlineStoreConfigTtlDuration,
        SagemakerFeatureGroupThroughputConfig;
export 'src/sagemaker/aws_sagemaker_flow_definition.dart'
    show
        AwsSagemakerFlowDefinition,
        SagemakerFlowDefinitionHumanLoopActivationConfig,
        SagemakerFlowDefinitionHumanLoopActivationConfigHumanLoopActivationConditionsConfig,
        SagemakerFlowDefinitionHumanLoopConfig,
        SagemakerFlowDefinitionHumanLoopConfigPublicWorkforceTaskPrice,
        SagemakerFlowDefinitionHumanLoopConfigPublicWorkforceTaskPriceAmountInUsd,
        SagemakerFlowDefinitionHumanLoopRequestSource,
        SagemakerFlowDefinitionOutputConfig;
export 'src/sagemaker/aws_sagemaker_hub.dart'
    show AwsSagemakerHub, SagemakerHubS3StorageConfig;
export 'src/sagemaker/aws_sagemaker_hub_content_reference.dart'
    show AwsSagemakerHubContentReference;
export 'src/sagemaker/aws_sagemaker_human_task_ui.dart'
    show AwsSagemakerHumanTaskUi, SagemakerHumanTaskUiUiTemplate;
export 'src/sagemaker/aws_sagemaker_hyper_parameter_tuning_job.dart'
    show
        AwsSagemakerHyperParameterTuningJob,
        SagemakerHyperParameterTuningJobAutotune,
        SagemakerHyperParameterTuningJobConfig,
        SagemakerHyperParameterTuningJobConfigObjective,
        SagemakerHyperParameterTuningJobConfigParameterRanges,
        SagemakerHyperParameterTuningJobConfigParameterRangesAutoParameters,
        SagemakerHyperParameterTuningJobConfigParameterRangesCategoricalParameterRanges,
        SagemakerHyperParameterTuningJobConfigParameterRangesContinuousParameterRanges,
        SagemakerHyperParameterTuningJobConfigParameterRangesIntegerParameterRanges,
        SagemakerHyperParameterTuningJobConfigResourceLimits,
        SagemakerHyperParameterTuningJobConfigStrategyConfig,
        SagemakerHyperParameterTuningJobConfigStrategyConfigHyperbandStrategyConfig,
        SagemakerHyperParameterTuningJobConfigTuningJobCompletionCriteria,
        SagemakerHyperParameterTuningJobConfigTuningJobCompletionCriteriaBestObjectiveNotImproving,
        SagemakerHyperParameterTuningJobConfigTuningJobCompletionCriteriaConvergenceDetected,
        SagemakerHyperParameterTuningJobTrainingJobDefinition,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionAlgorithmSpecification,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionAlgorithmSpecificationMetricDefinitions,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionCheckpointConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionHyperParameterRanges,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionHyperParameterRangesAutoParameters,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionHyperParameterRangesCategoricalParameterRanges,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionHyperParameterRangesContinuousParameterRanges,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionHyperParameterRangesIntegerParameterRanges,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionHyperParameterTuningResourceConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionHyperParameterTuningResourceConfigInstanceConfigs,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionInputDataConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionInputDataConfigDataSource,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionInputDataConfigDataSourceFileSystemDataSource,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionInputDataConfigDataSourceS3DataSource,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionInputDataConfigDataSourceS3DataSourceHubAccessConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionInputDataConfigDataSourceS3DataSourceModelAccessConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionInputDataConfigShuffleConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionOutputDataConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionResourceConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionResourceConfigInstanceGroups,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionResourceConfigInstancePlacementConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionResourceConfigInstancePlacementConfigPlacementSpecifications,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionStoppingCondition,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionTuningObjective,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionVpcConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitions,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsAlgorithmSpecification,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsAlgorithmSpecificationMetricDefinitions,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsCheckpointConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsHyperParameterRanges,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsHyperParameterRangesAutoParameters,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsHyperParameterRangesCategoricalParameterRanges,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsHyperParameterRangesContinuousParameterRanges,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsHyperParameterRangesIntegerParameterRanges,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsHyperParameterTuningResourceConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsHyperParameterTuningResourceConfigInstanceConfigs,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsInputDataConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsInputDataConfigDataSource,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsInputDataConfigDataSourceFileSystemDataSource,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsInputDataConfigDataSourceS3DataSource,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsInputDataConfigDataSourceS3DataSourceHubAccessConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsInputDataConfigDataSourceS3DataSourceModelAccessConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsInputDataConfigShuffleConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsOutputDataConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsResourceConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsResourceConfigInstanceGroups,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsResourceConfigInstancePlacementConfig,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsResourceConfigInstancePlacementConfigPlacementSpecifications,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsStoppingCondition,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsTuningObjective,
        SagemakerHyperParameterTuningJobTrainingJobDefinitionsVpcConfig,
        SagemakerHyperParameterTuningJobWarmStartConfig,
        SagemakerHyperParameterTuningJobWarmStartConfigParentHyperParameterTuningJobs;
export 'src/sagemaker/aws_sagemaker_image.dart' show AwsSagemakerImage;
export 'src/sagemaker/aws_sagemaker_image_version.dart'
    show AwsSagemakerImageVersion;
export 'src/sagemaker/aws_sagemaker_labeling_job.dart'
    show
        AwsSagemakerLabelingJob,
        SagemakerLabelingJobHumanTaskConfig,
        SagemakerLabelingJobHumanTaskConfigAnnotationConsolidationConfig,
        SagemakerLabelingJobHumanTaskConfigPublicWorkforceTaskPrice,
        SagemakerLabelingJobHumanTaskConfigPublicWorkforceTaskPriceAmountInUsd,
        SagemakerLabelingJobHumanTaskConfigUiConfig,
        SagemakerLabelingJobInputConfig,
        SagemakerLabelingJobInputConfigDataAttributes,
        SagemakerLabelingJobInputConfigDataSource,
        SagemakerLabelingJobInputConfigDataSourceS3DataSource,
        SagemakerLabelingJobInputConfigDataSourceSnsDataSource,
        SagemakerLabelingJobLabelingJobAlgorithmsConfig,
        SagemakerLabelingJobLabelingJobAlgorithmsConfigLabelingJobResourceConfig,
        SagemakerLabelingJobLabelingJobAlgorithmsConfigLabelingJobResourceConfigVpcConfig,
        SagemakerLabelingJobOutputConfig;
export 'src/sagemaker/aws_sagemaker_mlflow_app.dart' show AwsSagemakerMlflowApp;
export 'src/sagemaker/aws_sagemaker_mlflow_tracking_server.dart'
    show AwsSagemakerMlflowTrackingServer;
export 'src/sagemaker/aws_sagemaker_model.dart'
    show
        AwsSagemakerModel,
        SagemakerModelContainer,
        SagemakerModelContainerAdditionalModelDataSource,
        SagemakerModelContainerAdditionalModelDataSourceS3DataSource,
        SagemakerModelContainerAdditionalModelDataSourceS3DataSourceModelAccessConfig,
        SagemakerModelContainerImageConfig,
        SagemakerModelContainerImageConfigRepositoryAuthConfig,
        SagemakerModelContainerModelDataSource,
        SagemakerModelContainerModelDataSourceS3DataSource,
        SagemakerModelContainerModelDataSourceS3DataSourceModelAccessConfig,
        SagemakerModelContainerMultiModelConfig,
        SagemakerModelInferenceExecutionConfig,
        SagemakerModelPrimaryContainer,
        SagemakerModelPrimaryContainerAdditionalModelDataSource,
        SagemakerModelPrimaryContainerAdditionalModelDataSourceS3DataSource,
        SagemakerModelPrimaryContainerAdditionalModelDataSourceS3DataSourceModelAccessConfig,
        SagemakerModelPrimaryContainerImageConfig,
        SagemakerModelPrimaryContainerImageConfigRepositoryAuthConfig,
        SagemakerModelPrimaryContainerModelDataSource,
        SagemakerModelPrimaryContainerModelDataSourceS3DataSource,
        SagemakerModelPrimaryContainerModelDataSourceS3DataSourceModelAccessConfig,
        SagemakerModelPrimaryContainerMultiModelConfig,
        SagemakerModelVpcConfig;
export 'src/sagemaker/aws_sagemaker_model_card.dart'
    show AwsSagemakerModelCard, SagemakerModelCardSecurityConfig;
export 'src/sagemaker/aws_sagemaker_model_card_export_job.dart'
    show
        AwsSagemakerModelCardExportJob,
        SagemakerModelCardExportJobOutputConfig;
export 'src/sagemaker/aws_sagemaker_model_package_group.dart'
    show AwsSagemakerModelPackageGroup;
export 'src/sagemaker/aws_sagemaker_model_package_group_policy.dart'
    show AwsSagemakerModelPackageGroupPolicy;
export 'src/sagemaker/aws_sagemaker_monitoring_schedule.dart'
    show
        AwsSagemakerMonitoringSchedule,
        SagemakerMonitoringScheduleMonitoringScheduleConfig,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinition,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionBaseline,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionBaselineConstraintsResource,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionBaselineStatisticsResource,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionMonitoringAppSpecification,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionMonitoringInputs,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionMonitoringInputsBatchTransformInput,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionMonitoringInputsBatchTransformInputDatasetFormat,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionMonitoringInputsBatchTransformInputDatasetFormatCsv,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionMonitoringInputsBatchTransformInputDatasetFormatJson,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionMonitoringInputsEndpointInput,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionMonitoringOutputConfig,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionMonitoringOutputConfigMonitoringOutputs,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionMonitoringOutputConfigMonitoringOutputsS3Output,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionMonitoringResources,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionMonitoringResourcesClusterConfig,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionNetworkConfig,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionNetworkConfigVpcConfig,
        SagemakerMonitoringScheduleMonitoringScheduleConfigMonitoringJobDefinitionStoppingCondition,
        SagemakerMonitoringScheduleMonitoringScheduleConfigScheduleConfig;
export 'src/sagemaker/aws_sagemaker_notebook_instance.dart'
    show
        AwsSagemakerNotebookInstance,
        SagemakerNotebookInstanceInstanceMetadataServiceConfiguration;
export 'src/sagemaker/aws_sagemaker_notebook_instance_lifecycle_configuration.dart'
    show AwsSagemakerNotebookInstanceLifecycleConfiguration;
export 'src/sagemaker/aws_sagemaker_pipeline.dart'
    show
        AwsSagemakerPipeline,
        SagemakerPipelineParallelismConfiguration,
        SagemakerPipelinePipelineDefinitionS3Location;
export 'src/sagemaker/aws_sagemaker_project.dart'
    show
        AwsSagemakerProject,
        SagemakerProjectServiceCatalogProvisioningDetails,
        SagemakerProjectServiceCatalogProvisioningDetailsProvisioningParameter;
export 'src/sagemaker/aws_sagemaker_servicecatalog_portfolio_status.dart'
    show AwsSagemakerServicecatalogPortfolioStatus;
export 'src/sagemaker/aws_sagemaker_space.dart'
    show
        AwsSagemakerSpace,
        SagemakerSpaceOwnershipSettings,
        SagemakerSpaceSpaceSettings,
        SagemakerSpaceSpaceSettingsCodeEditorAppSettings,
        SagemakerSpaceSpaceSettingsCodeEditorAppSettingsAppLifecycleManagement,
        SagemakerSpaceSpaceSettingsCodeEditorAppSettingsAppLifecycleManagementIdleSettings,
        SagemakerSpaceSpaceSettingsCodeEditorAppSettingsDefaultResourceSpec,
        SagemakerSpaceSpaceSettingsCustomFileSystem,
        SagemakerSpaceSpaceSettingsCustomFileSystemEfsFileSystem,
        SagemakerSpaceSpaceSettingsJupyterLabAppSettings,
        SagemakerSpaceSpaceSettingsJupyterLabAppSettingsAppLifecycleManagement,
        SagemakerSpaceSpaceSettingsJupyterLabAppSettingsAppLifecycleManagementIdleSettings,
        SagemakerSpaceSpaceSettingsJupyterLabAppSettingsCodeRepository,
        SagemakerSpaceSpaceSettingsJupyterLabAppSettingsDefaultResourceSpec,
        SagemakerSpaceSpaceSettingsJupyterServerAppSettings,
        SagemakerSpaceSpaceSettingsJupyterServerAppSettingsCodeRepository,
        SagemakerSpaceSpaceSettingsJupyterServerAppSettingsDefaultResourceSpec,
        SagemakerSpaceSpaceSettingsKernelGatewayAppSettings,
        SagemakerSpaceSpaceSettingsKernelGatewayAppSettingsCustomImage,
        SagemakerSpaceSpaceSettingsKernelGatewayAppSettingsDefaultResourceSpec,
        SagemakerSpaceSpaceSettingsSpaceStorageSettings,
        SagemakerSpaceSpaceSettingsSpaceStorageSettingsEbsStorageSettings,
        SagemakerSpaceSpaceSharingSettings;
export 'src/sagemaker/aws_sagemaker_studio_lifecycle_config.dart'
    show AwsSagemakerStudioLifecycleConfig;
export 'src/sagemaker/aws_sagemaker_training_job.dart'
    show
        AwsSagemakerTrainingJob,
        SagemakerTrainingJobAlgorithmSpecification,
        SagemakerTrainingJobAlgorithmSpecificationMetricDefinitions,
        SagemakerTrainingJobAlgorithmSpecificationTrainingImageConfig,
        SagemakerTrainingJobAlgorithmSpecificationTrainingImageConfigTrainingRepositoryAuthConfig,
        SagemakerTrainingJobCheckpointConfig,
        SagemakerTrainingJobDebugHookConfig,
        SagemakerTrainingJobDebugHookConfigCollectionConfigurations,
        SagemakerTrainingJobDebugRuleConfigurations,
        SagemakerTrainingJobExperimentConfig,
        SagemakerTrainingJobInfraCheckConfig,
        SagemakerTrainingJobInputDataConfig,
        SagemakerTrainingJobInputDataConfigDataSource,
        SagemakerTrainingJobInputDataConfigDataSourceFileSystemDataSource,
        SagemakerTrainingJobInputDataConfigDataSourceS3DataSource,
        SagemakerTrainingJobInputDataConfigDataSourceS3DataSourceHubAccessConfig,
        SagemakerTrainingJobInputDataConfigDataSourceS3DataSourceModelAccessConfig,
        SagemakerTrainingJobInputDataConfigShuffleConfig,
        SagemakerTrainingJobMlflowConfig,
        SagemakerTrainingJobModelPackageConfig,
        SagemakerTrainingJobOutputDataConfig,
        SagemakerTrainingJobProfilerConfig,
        SagemakerTrainingJobProfilerRuleConfigurations,
        SagemakerTrainingJobRemoteDebugConfig,
        SagemakerTrainingJobResourceConfig,
        SagemakerTrainingJobResourceConfigInstanceGroups,
        SagemakerTrainingJobResourceConfigInstancePlacementConfig,
        SagemakerTrainingJobResourceConfigInstancePlacementConfigPlacementSpecifications,
        SagemakerTrainingJobRetryStrategy,
        SagemakerTrainingJobServerlessJobConfig,
        SagemakerTrainingJobSessionChainingConfig,
        SagemakerTrainingJobStoppingCondition,
        SagemakerTrainingJobTensorBoardOutputConfig,
        SagemakerTrainingJobVpcConfig;
export 'src/sagemaker/aws_sagemaker_user_profile.dart'
    show
        AwsSagemakerUserProfile,
        SagemakerUserProfileUserSettings,
        SagemakerUserProfileUserSettingsCanvasAppSettings,
        SagemakerUserProfileUserSettingsCanvasAppSettingsDirectDeploySettings,
        SagemakerUserProfileUserSettingsCanvasAppSettingsEmrServerlessSettings,
        SagemakerUserProfileUserSettingsCanvasAppSettingsGenerativeAiSettings,
        SagemakerUserProfileUserSettingsCanvasAppSettingsIdentityProviderOauthSettings,
        SagemakerUserProfileUserSettingsCanvasAppSettingsKendraSettings,
        SagemakerUserProfileUserSettingsCanvasAppSettingsModelRegisterSettings,
        SagemakerUserProfileUserSettingsCanvasAppSettingsTimeSeriesForecastingSettings,
        SagemakerUserProfileUserSettingsCanvasAppSettingsWorkspaceSettings,
        SagemakerUserProfileUserSettingsCodeEditorAppSettings,
        SagemakerUserProfileUserSettingsCodeEditorAppSettingsAppLifecycleManagement,
        SagemakerUserProfileUserSettingsCodeEditorAppSettingsAppLifecycleManagementIdleSettings,
        SagemakerUserProfileUserSettingsCodeEditorAppSettingsCustomImage,
        SagemakerUserProfileUserSettingsCodeEditorAppSettingsDefaultResourceSpec,
        SagemakerUserProfileUserSettingsCustomFileSystemConfig,
        SagemakerUserProfileUserSettingsCustomFileSystemConfigEfsFileSystemConfig,
        SagemakerUserProfileUserSettingsCustomPosixUserConfig,
        SagemakerUserProfileUserSettingsJupyterLabAppSettings,
        SagemakerUserProfileUserSettingsJupyterLabAppSettingsAppLifecycleManagement,
        SagemakerUserProfileUserSettingsJupyterLabAppSettingsAppLifecycleManagementIdleSettings,
        SagemakerUserProfileUserSettingsJupyterLabAppSettingsCodeRepository,
        SagemakerUserProfileUserSettingsJupyterLabAppSettingsCustomImage,
        SagemakerUserProfileUserSettingsJupyterLabAppSettingsDefaultResourceSpec,
        SagemakerUserProfileUserSettingsJupyterLabAppSettingsEmrSettings,
        SagemakerUserProfileUserSettingsJupyterServerAppSettings,
        SagemakerUserProfileUserSettingsJupyterServerAppSettingsCodeRepository,
        SagemakerUserProfileUserSettingsJupyterServerAppSettingsDefaultResourceSpec,
        SagemakerUserProfileUserSettingsKernelGatewayAppSettings,
        SagemakerUserProfileUserSettingsKernelGatewayAppSettingsCustomImage,
        SagemakerUserProfileUserSettingsKernelGatewayAppSettingsDefaultResourceSpec,
        SagemakerUserProfileUserSettingsRSessionAppSettings,
        SagemakerUserProfileUserSettingsRSessionAppSettingsCustomImage,
        SagemakerUserProfileUserSettingsRSessionAppSettingsDefaultResourceSpec,
        SagemakerUserProfileUserSettingsRStudioServerProAppSettings,
        SagemakerUserProfileUserSettingsSharingSettings,
        SagemakerUserProfileUserSettingsSpaceStorageSettings,
        SagemakerUserProfileUserSettingsSpaceStorageSettingsDefaultEbsStorageSettings,
        SagemakerUserProfileUserSettingsStudioWebPortalSettings,
        SagemakerUserProfileUserSettingsTensorBoardAppSettings,
        SagemakerUserProfileUserSettingsTensorBoardAppSettingsDefaultResourceSpec;
export 'src/sagemaker/aws_sagemaker_workforce.dart'
    show
        AwsSagemakerWorkforce,
        SagemakerWorkforceCognitoConfig,
        SagemakerWorkforceOidcConfig,
        SagemakerWorkforceSourceIpConfig,
        SagemakerWorkforceWorkforceVpcConfig;
export 'src/sagemaker/aws_sagemaker_workteam.dart'
    show
        AwsSagemakerWorkteam,
        SagemakerWorkteamMemberDefinition,
        SagemakerWorkteamMemberDefinitionCognitoMemberDefinition,
        SagemakerWorkteamMemberDefinitionOidcMemberDefinition,
        SagemakerWorkteamNotificationConfiguration,
        SagemakerWorkteamWorkerAccessConfiguration,
        SagemakerWorkteamWorkerAccessConfigurationS3Presign,
        SagemakerWorkteamWorkerAccessConfigurationS3PresignIamPolicyConstraints;
