name: terradart_example_network_security_backend_auth_quickstart
description: Network Security backend authentication config end-to-end example.
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  terradart_core: ^0.25.3
  terradart_google: ^0.25.3

dev_dependencies:
  lints: ^6.0.0
